### ISSUE TITLE
Non-unimod modifications

### ISSUE THREAD

**Issue by willems533** [vdemichev/DiaNN#10]
Hey,

Is there any possibility of specifying non-unimod listed modifications, e.g. by specifying the delta mass? Or does the --mod does not require the 'UniMod:xx,' ? 

Thanks in advance

**Comment by vdemichev** [comment]
Hi willems533, yes it is possible, --mod accepts arbitrary modification names. Btw, when using a spectral library, it's no longer necessary (in DIA-NN 1.7.1) to specify modifications - libraries with any modifications are supported as is.

**Comment by willems533** [comment]
Ok thanks :-)
