### ISSUE TITLE
Question in output

### ISSUE THREAD

**Issue by gukongxin** [vdemichev/DiaNN#1009]
Hi Vadim,

What is the relationship between 'Proteotypic' and 'proteinA; proteinB' in the report? I thought that Proteotypic == 1 meant no shared proteins, but the results are not consistent.

> df <- read.csv("SW400-900_1.9Dx264_Ac20ms_C7s.pr_matrix.tsv",sep = "\t")
> df %>% filter(!grepl(";",Protein.Group)) %>% nrow()
[1] 33483
> df %>% filter(Proteotypic==1) %>% nrow()
[1] 31477

**Comment by vdemichev** [comment]
Hi,

The meaning of 'Proteotypic' depends on the protein inference setting and by default means that the peptide is specific to a particular gene.

Best,
Vadim
