### ISSUE TITLE
1_8_2 beta 42

### ISSUE THREAD

**Issue by Giu-F** [vdemichev/DiaNN#1020]
Hi, I generated a library from a fasta file in this version. Then I tried searching my raw files with this library in the same version. And I get an error message saying that the speclib version of my library is not supported in this version…

**Comment by enonimos** [comment]
I can confirm that I get the same message when generating an in silico library using beta 42.  However, if I use a library generated from a previous DIA-NN version, the search will process as expected.

**Comment by vdemichev** [comment]
Hi Giulia,

Just forgot to update library version in one of the functions. So please don't use beta 42 for in silico lib generation.

Best,
Vadim

**Comment by animesh** [comment]
any updates @vdemichev on release will be apprecitate 💯

**Comment by vdemichev** [comment]
This evening :)
