### ISSUE TITLE
Quantification strategy for benchmarking

### ISSUE THREAD

**Issue by Li5459000** [vdemichev/DiaNN#1021]
Hi,

For a benchmarking sample of a mixed proteome from E. coli, human, and yeast, I'm aiming to assess quantitative accuracy of my method. 

In DIA-NN, the default quantification strategy is 'robust LC (high precision)'. Should I switch to 'high accuracy' instead?"

Li

**Comment by vdemichev** [comment]
Hi Li,

We recommend using QuantUMS, I would suggest to either use 1.8.2 beta 27, or wait for a new official release in a few days.

Best,
Vadim
