### ISSUE TITLE
Linux CLI manual and file streaming

### ISSUE THREAD

**Issue by an-altosian** [vdemichev/DiaNN#1065]
Dear DiaNN authors,

Thank you very much for developing such a nice tool. 

I am trying to run DIA-NN from a linux server using your CLI. I noticed that there is no helping messages, i.e., `--help` flag, describing the available parameters and the default values. This makes it slightly difficult to setup a pipeline that can take parameter values as the inputs as I found some descrepancy between the log.txt file and the parameters listed in the log.txt file, for example the `--qvalue` and `--min-corr` parameters are not listed in the README. So, do you think it is possible to provide a command line manual that refects the up-to-date parameters?

Another question is, as the current linux version of DIANN could not process `.RAW` files, I have to convert my files first to mxML, which can take enormous disk space. As a workaround, do you think it is possible for DIANN CLI to take a file stream as an alternative of its `--f` parameter?

Best.

**Comment by vdemichev** [comment]
Thank you for pointing this out, indeed seems some parameters are missing in the command line reference.

About mzML: it's usually OK size-wise, if you use 32-bit format, i.e. please see the recommended conversion settings: https://github.com/vdemichev/DiaNN?tab=readme-ov-file#raw-data-formats.

About a stream: not sure, most likely not. What's planned though is native .raw support under Linux.

Best,
Vadim

**Comment by vdemichev** [comment]
No definitive timeline for this yet, but almost definitely not in the upcoming update (1.9.1).
