### ISSUE TITLE
Premature exit DIA-NN Astral

### ISSUE THREAD

**Issue by ds2268** [vdemichev/DiaNN#1076]
DIA-NN run on Astral data (dilution series, 18 files) exited after 1st pass (after loading spec lib). No errors were given and no log was written. The system had 120GB of memory and 32 threads.

`report-100pct-first-pass.tsv`  was 5.8GB and `report-lib-100pct.tsv`  was 13GB

<img width="1173" alt="image" src="https://github.com/vdemichev/DiaNN/assets/25041003/6afd21b0-c742-4d7c-b4b3-03bd3120f64e">

<img width="1168" alt="image" src="https://github.com/vdemichev/DiaNN/assets/25041003/62d118b6-6749-483d-af39-cd3017f6d365">

Another run exited after the 2nd pass, at quantification (yeast KO, 312 files). The r`eport-100pct-first-pass.tsv` was 34GB. `report-lib-100pct.tsv`  was 6.4GB

<img width="1173" alt="image" src="https://github.com/vdemichev/DiaNN/assets/25041003/f504389a-15cc-4563-a0e4-c40062d29e0d">

Any idea what is going on? All the RAW Astral files were converted to mzML. One other Astral run succeeded without problems.

**Comment by vdemichev** [comment]
Thank you for letting me know. Here the size of the empirical library being generated is clearly abnormal. Can you please share the full logs, including for the generation of report-lib.predicted.speclib? 

Were the raw files converted to .mzML using MSConvert GUI and the recommended settings https://github.com/vdemichev/DiaNN?tab=readme-ov-file#raw-data-formats? In general, DIA-NN should work fine with .raw files directly, no conversion necessary.

**Comment by ds2268** [comment]
This particular Astral file did not work from .raw so needed to convert it. It could indeed be a memory issue, as I was running 2 runs on the same VM and saw that memory consumption increased in some steps. Re-running it now with just 1 job.

Yes, I saw that the number of precursors does not increase drastically by going from 1%, 20% FDR to 100% FDR for example (500k, 700k, 900k). The majority of precursor IDs are in 1% FDR, which was surprising to me.

**Comment by vdemichev** [comment]
Yes, migth be that error that got reported in another thread, it will be fixed in 1.9.1 to be released soon.

"Is there any other downside of running at > 5% FDR" - just worse results - until 50% FDR (so long as you filter the output afterwards). If you set to 100%, I am not sure if the output will be reliable - it's never been tested. In the update, I will make DIA-NN always filter the library at least at 50%.
