### ISSUE TITLE
Quantity.Quality filter and maxLFQ quantitation

### ISSUE THREAD

**Issue by topitsch** [vdemichev/DiaNN#1091]
Hi, 

I want to use a quantity.quality filter (of >= 0.5) on the precursors before getting the PG.maxLFQ quantitation values. It seems that simply filtering the report before using diann_matrix() is not helping, because the maxLFQ values have already been calculated on all precursors, right? Is the only way to do this to filter the report and then use diann_maxlfq() on precursor.normalised? Or is there another way?

Thanks for your help!

**Comment by vdemichev** [comment]
Hi,

The PG.MaxLFQ, when calculated with QuantUMS (Quantity.Quality is only good with QuantUMS), already takes Quantity.Quality into account, and you can filter for better values using PG.MaxLFQ.Quality. However if you want to recalculate protein quantities after filtering precursors, you currently will need to use the iq R package, which calculates regular MaxLFQ, not QuantUMS protein quantities.

Best,
Vadim
