### ISSUE TITLE
How to get information about the pdf report in edit format, such as csv.

### ISSUE THREAD

**Issue by Mnago** [vdemichev/DiaNN#111]
Hi Vadim,

How to get information about the pdf report in edit format, such as CSV.

We want to batch extract the info such as Mean peak FWHM, (in ms2 scans) from the pdf report.

![Snipaste_2021-05-27_21-08-13](https://user-images.githubusercontent.com/52949420/119831303-bc647380-bf2f-11eb-881f-d1511099b478.png)

Looking forward to your reply.

**Comment by vdemichev** [comment]
Hi Winnie,

PDF report is created based on .stats.tsv and the main .tsv reports. So for basic quality control you can use these (in particular the .stats.tsv file which contains all the main metrics). But it's not possible to directly access the information in the PDF report.

Best wishes,

Vadim

**Comment by Mnago** [comment]
Thanks Vadim.
