### ISSUE TITLE
.dia format generated from Bruker .d folder 

### ISSUE THREAD

**Issue by wenronchen** [vdemichev/DiaNN#1119]
Hi Vadim,

I am trying to output all the information in the .dia format file. When reading a .dia format file generated from dia-PASEF data, is it possible to retrieve Frame information? If so, what specific details (attribute and data type) about the Frame are written in the .dia file?

Thank you for your time in advance.

Best,

Wenrong

**Comment by vdemichev** [comment]
Hi Wenrong,

The .dia format is not open and is only supposed to be read by DIA-NN itself. What would be the motivation in this case?

Best,
Vadim

**Comment by vdemichev** [comment]
Hi Wenrong,

Maybe the best would be to use alphatims or timsrust.

Best,
Vadim
