### ISSUE TITLE
MSP spectral library

### ISSUE THREAD

**Issue by Dmorgen** [vdemichev/DiaNN#112]
Hi,

can I ask for an sample MSP file from you? i've seen a few libraries that are slightly different from one another, and I would like to make sure mine is suitable. thanks!
David.

**Comment by vdemichev** [comment]
Hi David,

For example, 
`Name: AAAAAAAAAAAAAAAAGATCLER/2
MW: 971.991805370135
Comment: Parent=971.991805370135 Collision_energy=30.0 Mods=1/19,C,Carbamidomethyl ModString=AAAAAAAAAAAAAAAAGATCLER//Carbamidomethyl@C20/2
Num peaks: 39
175.118952167	0.26417816	"y1/0.0ppm"
36.525833467	0.0040389355	"b1^2)/0.0ppm"
304.161545167	0.06535776	"y2/0.0ppm"
417.245609167	0.0474335	"y3/0.0ppm"
209.126442817	0.0014933042	"y3^2)/0.0ppm"
214.118618467	0.16820636	"b3/0.0ppm"
577.2762578906	0.08811053	"y4/0.0ppm"
285.155732467	0.32001495	"b4/0.0ppm"
678.3239368906001	0.19702087	"y5/0.0ppm"
356.192846467	0.49937883	"b5/0.0ppm"
749.3610508906	0.15518452	"y6/0.0ppm"
427.22996046699996	0.7034843	"b6/0.0ppm"
806.3825148906001	0.9180764	"y7/0.0ppm"
498.26707446699993	0.89894366	"b7/0.0ppm"
877.4196288906	0.6934223	"y8/0.0ppm"
569.3041884669999	0.9111778	"b8/0.0ppm"
948.4567428906	0.87182397	"y9/0.0ppm"
640.3413024669999	0.92008233	"b9/0.0ppm"
1019.4938568906	0.9157743	"y10/0.0ppm"
711.3784164669999	0.8307481	"b10/0.0ppm"
1090.5309708906002	1.0	"y11/0.0ppm"
782.4155304669998	0.6099293	"b11/0.0ppm"
1161.5680848906002	0.989866	"y12/0.0ppm"
853.4526444669998	0.4116958	"b12/0.0ppm"
1232.6051988906001	0.8836881	"y13/0.0ppm"
924.4897584669998	0.25164416	"b13/0.0ppm"
462.7485174669999	0.0029533808	"b13^2/0.0ppm"
1303.6423128906001	0.7627059	"y14/0.0ppm"
995.5268724669997	0.1125279	"b14/0.0ppm"
498.2670744669999	0.0030043465	"b14^2/0.0ppm"
1374.6794268906	0.6251431	"y15/0.0ppm"
1066.563986467	0.049291115	"b15/0.0ppm"
533.7856314669999	0.0019362338	"b15^2/0.0ppm"
1445.7165408906	0.44130313	"y16/0.0ppm"
1137.601100467	0.02479308	"b16/0.0ppm"
569.3041884669999	0.0004616311	"b16^2/0.0ppm"
1516.7536548906	0.23366536	"y17/0.0ppm"
1194.6225644669998	0.008709005	"b17/0.0ppm"
1587.7907688906	0.105200484	"y18/0.0ppm"
Name: AAAAAAAAAAAAAAAAGATCLER/3
MW: 648.33029573568
Comment: Parent=648.33029573568 Collision_energy=30.0 Mods=1/19,C,Carbamidomethyl ModString=AAAAAAAAAAAAAAAAGATCLER//Carbamidomethyl@C20/3
Num peaks: 59
175.118952167	0.118962914	"y1/0.0ppm"
304.161545167	0.055386826	"y2/0.0ppm"
143.081504467	0.036400136	"b2/0.0ppm"
417.245609167	0.068843134	"y3/0.0ppm"
214.118618467	0.06747491	"b3/0.0ppm"
577.2762578906	0.12831993	"y4/0.0ppm"
285.155732467	0.07523013	"b4/0.0ppm"
678.3239368906001	0.28362942	"y5/0.0ppm"
356.192846467	0.089202315	"b5/0.0ppm"
749.3610508906	0.22496076	"y6/0.0ppm"
427.22996046699996	0.104876846	"b6/0.0ppm"
806.3825148906001	1.0	"y7/0.0ppm"
403.69489567880004	0.0053056045	"y7^2)/0.0ppm"
498.26707446699993	0.14028811	"b7/0.0ppm"
877.4196288906	0.5336292	"y8/0.0ppm"
439.2134526788	0.013610783	"y8^2)/0.0ppm"
569.3041884669999	0.19659525	"b8/0.0ppm"
285.15573246699995	0.010913419	"b8^2)/0.0ppm"
948.4567428906	0.3215273	"y9/0.0ppm"
474.7320096788	0.004131916	"y9^2)/0.0ppm"
640.3413024669999	0.26681018	"b9/0.0ppm"
320.67428946699994	0.101756945	"b9^2)/0.0ppm"
1019.4938568906	0.17732085	"y10/0.0ppm"
711.3784164669999	0.26000974	"b10/0.0ppm"
356.1928464669999	0.28889298	"b10^2/0.0ppm"
1090.5309708906002	0.07193149	"y11/0.0ppm"
782.4155304669998	0.1926407	"b11/0.0ppm"
391.7114034669999	0.44983152	"b11^2/0.0ppm"
261.47669446699996	0.00046056107	"b11^3/0.0ppm"
1161.5680848906002	0.015118658	"y12/0.0ppm"
853.4526444669998	0.18367782	"b12/0.0ppm"
427.2299604669999	0.46777692	"b12^2/0.0ppm"
285.15573246699995	0.0022019926	"b12^3/0.0ppm"
616.8062376788	0.00092646864	"y13^2/0.0ppm"
924.4897584669998	0.13139194	"b13/0.0ppm"
462.7485174669999	0.28516653	"b13^2/0.0ppm"
308.83477046699994	0.0017660611	"b13^3/0.0ppm"
652.3247946788	0.0023823057	"y14^2/0.0ppm"
995.5268724669997	0.067030825	"b14/0.0ppm"
498.2670744669999	0.12482756	"b14^2/0.0ppm"
332.51380846699993	0.0013076963	"b14^3/0.0ppm"
1066.563986467	0.029849593	"b15/0.0ppm"
533.7856314669999	0.057529286	"b15^2/0.0ppm"
356.192846467	0.0005073514	"b15^3/0.0ppm"
723.3619086788	0.0012012473	"y16^2/0.0ppm"
1137.601100467	0.003793083	"b16/0.0ppm"
569.3041884669999	0.023583472	"b16^2/0.0ppm"
758.8804656788	0.0023432446	"y17^2/0.0ppm"
597.8149204669999	0.0119196335	"b17^2/0.0ppm"
794.3990226788	0.0011558689	"y18^2/0.0ppm"
633.3334774669999	0.0067375745	"b18^2/0.0ppm"
683.8573169669999	0.003870431	"b19^2/0.0ppm"
763.8726413287999	0.0025424592	"b20^2/0.0ppm"
509.58418637486665	2.899121e-05	"b20^3/0.0ppm"
820.4146733287998	0.002275345	"b21^2/0.0ppm"
547.2788743748666	0.0005419623	"b21^3/0.0ppm"
1768.8646631905997	0.0036787994	"b22/0.0ppm"
884.9359698287998	0.00052104524	"b22^2/0.0ppm"
590.2930720415333	0.00021250545	"b22^3/0.0ppm"
`
(this is Prosit output)

You can also just convert any library format to DIA-NN's .tsv (just select "Generate spectral library") - this will reflect how DIA-NN sees it. So can use it to check if it reads the lib correctly. 

Best,
Vadim

**Comment by Dmorgen** [comment]
Hi Vadim,

Thanks for the answer! Could you also supply an TSV example please?

Thanks!
David.

**Comment by vdemichev** [comment]
[iRTassays.txt](https://github.com/vdemichev/DiaNN/files/6585724/iRTassays.txt)

**Comment by Dmorgen** [comment]
Thanks again! Awesome!

D.
