### ISSUE TITLE
diann1.8.1 vs. 1.9

### ISSUE THREAD

**Issue by wangss3** [vdemichev/DiaNN#1145]
Hi，

Thank you for this excellent software and your updates and maintenance.
I analyzed the same data with 1.8.1 and 1.9, respectively, and found the protein intensities are quite different. 
Do you have any comments？
![intensity](https://github.com/user-attachments/assets/3a72e1c4-baee-4eee-8276-55683eb90a21)

Wang

**Comment by vdemichev** [comment]
Hi Wang,

Any DIA software tool aims to perform 'relative quantification' of proteins, i.e. estimate, as precisely as possible, the fold changes of each detected protein between runs. However quantities of different proteins are not meant to be comparable. So when comparing different DIA-NN versions, it would make more sense to look at fold changes reported for proteins between two conditions, and how these fold changes (not the quantities themselves) are similar/different between DIA-NN versions. 

Best,
Vadim
