### ISSUE TITLE
Ion injection time from report

### ISSUE THREAD

**Issue by LKittinun** [vdemichev/DiaNN#1158]
Thank you for your wonderful project! My issue is how to get the ion injection time from the DIA-NN report. I cannot find the respective column related to this variable.

Regards,
Kittinun

**Comment by vdemichev** [comment]
Hi Kittinun,

This information is currently not reported, as it's not being read from the raw data file. So to get it I guess the best would be to access the raw file through some R package (a number can read mzML, and Thermo data can be converted to mzML) and match the RT reported by DIA-NN to the spectra in the raw file.

Best,
Vadim

**Comment by LKittinun** [comment]
Thank you so much for your prompt suggestion, Vadim.

Best,
Kittinun
