### ISSUE TITLE
Can we get diann to output generated decoy proteins in the report.tsv?

### ISSUE THREAD

**Issue by patruong** [vdemichev/DiaNN#117]
Hi,

Is it possible to output the decoy:s generated from DIA-NN:s build-in decoy generation algorithm when using a spectral library without decoy? 

Thanks!

**Comment by vdemichev** [comment]
Hi Patrick,

No, unfortunately it's not possible. Btw, DIA-NN does not generate 'protein decoys', but rather decoys for each peptide, please see the DIA-NN paper for the description of how it's done.

Best,
Vadim
