### ISSUE TITLE
multi-run analysis

### ISSUE THREAD

**Issue by jflucier** [vdemichev/DiaNN#1177]
Hi,

I have used DIANN multiple times to analyse DIA-PASEF data on a single run.

I use this command for analysis:
```
diann --threads 40 --verbose 2 \
--f ... \
--f ... \
...
--temp $SLURM_TMPDIR/temp \
--cut K*,R* --missed-cleavages 2 --met-excision \
--fasta "$SLURM_TMPDIR/UP000000589_10090_combo.fasta" --fasta-search \
--out-lib "$SLURM_TMPDIR/out/report-lib.tsv" --out-lib-copy \
--out "$SLURM_TMPDIR/out/report.tsv" \
--mass-acc-ms1 20 --mass-acc 20 \
--min-pep-len 7 --max-pep-len 30 \
--min-pr-charge 1 --max-pr-charge 5 \
--min-pr-mz 100 --max-pr-mz 1700 \
--min-fr-mz 100 --max-fr-mz 1500 \
--predictor --reanalyse --matrices --smart-profiling --pg-level 1 \
--unimod4 --unimod35 --var-mod UniMod:1,42.010565,*n,ntermacetyl
```

For my next analysis, I have to analyse a second run "B" with new samples and compare results with a run "A" performed a month ago. I was wandering what is the best way to do this with DIANN, 

1 - Run DIANN on both run independently and combine both output matrix for post-analysis
or
2 - Run DIANN on using run A and B acquisition in a single DIANN call and use the combined output for post-analysis

Thanks for your help,

**Comment by jflucier** [comment]
forgot to mention, I have looked in issues and documentation but can't seem to find answer to my question.
Thank again for your help

**Comment by vdemichev** [comment]
Hi Jean-Francois,

Best is to reanalyse all the data all together, i.e. option 2. 'Combining' different analyses, in contrast, should only be done with specific settings used to ensure OK-to-compare quantities and is a good option only for cases such as patient samples arriving over a period of > year, please see section on incremental data processing in https://github.com/vdemichev/DiaNN?tab=readme-ov-file#frequently-asked-questions.

Best,
Vadim

**Comment by jflucier** [comment]
Thanks so much for your quick answer and explanation.

I will for sure take a look at your reference for incremental data processing
