### ISSUE TITLE
Stats report missing in output folder when running DIANN 1.9.1

### ISSUE THREAD

**Issue by rolivella** [vdemichev/DiaNN#1192]
### Description

Hi, I'm encountering an issue while running DIANN version 1.9.1. I noticed that the expected stats report (*.output.stats.tsv) is not being generated in the output folder, even though the process completes successfully without any errors.

I’ve used previous versions of DIANN (e.g., 1.8.1), and the stats report was always generated. However, when running the same workflow with DIANN 1.9.1, the stats report is missing.

### Steps to Reproduce

1. Run DIANN 1.9.1 with the following command line:
    ```bash
    singularity exec -e docker://proteomicsunitcrg/dia-nn:1.9.1 /diann-1.9.1/diann-linux -cfg path/to/astral.cfg
    ```

2. Check the output folder after the run completes.
3. The stats report is missing, but other expected outputs (e.g., processed data, results, etc.) are present.

### Expected Behavior

A stats report should be generated in the output folder, similar to how it was in previous versions like DIANN 1.8.1.

### Actual Behavior

The stats report is missing from the output folder, even though all other expected files (such as result files) are correctly generated.

### Environment

- **DIANN version**: 1.9.1
- **Execution platform**: Singularity
- **Docker image used**: `proteomicsunitcrg/dia-nn:1.9.1`
- **Host OS**: Ubuntu 22.04

### Logs and Configurations

Please find attached:
- Configuration file used: [astral-tests-4-with-1.9.1.cfg.zip](https://github.com/user-attachments/files/17192240/astral-tests-4-with-1.9.1.cfg.zip)

- Console output from the DIANN run: [rsDIANNsubmission.output.log.zip](https://github.com/user-attachments/files/17192256/rsDIANNsubmission.output.log.zip)

### Question

Is there a change in DIANN 1.9.1 that affects the generation of the stats report? If so, are there new options or parameters that need to be specified in the command line or configuration file to ensure the stats report is created?

Any guidance would be greatly appreciated. Thank you!

**Comment by vdemichev** [comment]
Hi Roger,

This is a know error: DIA-NN 1.9.1 on Linux terminates immediately after trying to save a manifest file, if --matrices is specified. The solution so far is to not use --matrices on Linux, this will be fixed in 1.9.2.

Please also note that the log also contains a warning that an in silico library must be generated in a separate pipeline step, i.e. without the raw data specified.

Best,
Vadim
