### ISSUE TITLE
GCC compilation instructions

### ISSUE THREAD

**Issue by wasade** [vdemichev/DiaNN#1194]
I apologize if I missed it, but are there compilation instructions for Linux ideally relative to GCC?

**Comment by vdemichev** [comment]
Hi Daniel,

DIA-NN is not open source since version 1.7.12. For 1.7.12 and previous versions there's a 'linux-build-gcc' bash file for compiling.

Best,
Vadim

**Comment by wasade** [comment]
Okay thanks
