### ISSUE TITLE
Gene names empty except cRAP with MBR

### ISSUE THREAD

**Issue by bfurtwa** [vdemichev/DiaNN#1206]
If I follow these steps, the columns "Genes" and "Protein.Names" in report.parquet are empty except for the cRAP entries.

- generate predicted library from FASTA with contaminants activated (the library contains all gene names)
- search raw files with the library with contaminants activated using MBR (the MBR library and report.first-pass contain the gene names, but the final results only contain cRAP gene names)

DIA-NN 1.9.1

**Comment by vdemichev** [comment]
Hi,

How do the logs (library generation & the analysis) look like?

Best,
Vadim

**Comment by bfurtwa** [comment]
[report-lib.log.txt](https://github.com/user-attachments/files/17333888/report-lib.log.txt)
[report.log.txt](https://github.com/user-attachments/files/17333887/report.log.txt)

**Comment by vdemichev** [comment]
Main FASTA uniprotkb_proteome_UP000005640_AND_revi_2024_07_08.fasta was not specified during the analysis, hence no protein annotation.

**Comment by bfurtwa** [comment]
ah thanks, easy fix. I wasn't aware that this was needed
