### ISSUE TITLE
How can we set number of logical processors?

### ISSUE THREAD

**Issue by educhicano** [vdemichev/DiaNN#121]
Hi Vadim,
congrats for this amazing software.
I was wondering how to increase the number of logical processors as we have a server here with 52 cores (104 logical processors) but I'm currently using the half of them. 
Attached I send you a capture where it shows what is happening. I've tried to change this usage by setting with --threads 100 but logically, I've only 52, and still runs with the half of logical cores:

DIA-NN 1.7.16 (Data-Independent Acquisition by Neural Networks)
Compiled on Mar 27 2021 21:34:06
Current date and time: Wed Jun 16 10:23:27 2021
CPU: GenuineIntel Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
SIMD instructions: AVX AVX2 AVX512CD AVX512F FMA SSE4.1 SSE4.2 
Logical CPU cores: 52

Is there any way to set the logical processors instead the threads?
Thanks in advance!
<img width="471" alt="Captura de pantalla 2021-06-16 a las 10 39 57" src="https://user-images.githubusercontent.com/21240536/122192052-94639280-ce93-11eb-81a9-993a023d9f57.png">

**Comment by vdemichev** [comment]
Hi Edu,

Thanks!
I think it's been reported that 64 is a limit imposed by Windows. 
So I would suggest either running 2 instances of DIA-NN in parallel, analysing different experiments - that would be more efficient computationally anyway (multi-threading implementation in DIA-NN is good, but the scaling is still not 100%). Or can just use as is, running multiple threads per core - it does not seem to provide a significant boost anyway.

Best,
Vadim

**Comment by educhicano** [comment]
Hi Vadim,
thanks for your quick reply!
In that case, how can we boost the performance of DIANN when we are in this situations? I'm running DIA experiments with over 100 samples and I want to use the best settings I can use... :)

**Comment by vdemichev** [comment]
Can you maybe share a sample log file? I will take a look.
Btw, there will be a new DIA-NN release very soon, which is faster in most scenarios.

**Comment by educhicano** [comment]
Yes of course! Here is the log. It is from a "medium" size experiment, 39 samples, TIMSTOFPro + Evosep combo.
Thanks!
[vadim_log.txt](https://github.com/vdemichev/DiaNN/files/6667743/vadim_log.txt)

**Comment by vdemichev** [comment]
Hi Edu,

The main delay here is clearly in loading the .d run. We are working in making this faster, but for now it is as it is. Increasing the number of threads is unlikely to help here. The thing is, for whatever reason some .d runs are loaded quickly, while some are not. What can help for now is converting .d to .dia and then working with dia files (note that .dia can be up to 3x larger in size than .d though).

Best,
Vadim

**Comment by educhicano** [comment]
Hi Vadim,
thanks for your help! We will try to do it with dia files and lets see how it works!
Best,
Edu

**Comment by dardanus-u** [comment]
Yes indeed, I think I got ahead of myself there. Next time I will at least take a look at the code before saying anything
