### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by ABanaeiEsfahani** [vdemichev/DiaNN#122]
Hello,

I was about to install DIANN on a linux cluster but I got the following error. Could you please help me with this? Thanks.

ar rcs libmstoolkitlite.a adler32.o compress.o crc32.o deflate.o inffast.o inflate.o infback.o inftrees.o trees.o uncompr.o zutil.o xmlparse.o xmlrole.o xmltok.o mzp.MSNumpress.o mzp.mzp_base64_lite.o mzp.BasicSpectrum_lite.o mzp.mzParser_lite.o mzp.RAMPface_lite.o mzp.saxhandler_lite.o mzp.saxmzmlhandler_lite.o mzp.saxmzxmlhandler_lite.o mzp.Czran_lite.o mzp.mz5handler_lite.o mzp.mzpMz5Config_lite.o mzp.mzpMz5Structs_lite.o mzp.BasicChromatogram_lite.o mzp.PWIZface_lite.o Spectrum.o MSObject.o mzMLWriter.o pepXMLWriter.o MSReaderLite.o
g++ -o ../diann-linux ../src/diann.cpp -static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++17 -lstdc++fs -fpermissive -O3 -mfpmath=sse -msse2 -march=core2 -w -L. -lmstoolkitlite -I. -I./include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DGCC -DHAVE_EXPAT_CONFIG_H
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [all] Error 1
[banamacc@vl90369 mstoolkit]$ 

Best regards,
Amir

**Comment by vdemichev** [comment]
Hi Amir,

The source code on github is for the older DIA-NN versions. The next DIA-NN version (to be released very soon) will come also with pre-built Linux packages.

Best,
Vadim

**Comment by ABanaeiEsfahani** [comment]
Hi Vadim,

Thanks. Do you know when it will be available?

Best,
Amir

**Comment by vdemichev** [comment]
Released!

**Comment by ABanaeiEsfahani** [comment]
Congrats :)

**Comment by vdemichev** [comment]
Thanks!
