### ISSUE TITLE
License clarification, meaning of "Use in the cloud"

### ISSUE THREAD

**Issue by mriffle** [vdemichev/DiaNN#1222]
Vadim, following up on our brief Twitter exchange:

Nextflow workflows depend on the availability of containerized (e.g., Docker or apptainer) images of the software being run. It is best practice for these container images to be in a central repository, such as Docker Hub or quay.io. When a step like DIA-NN is being run, the image is pulled down from the repository and run locally. When done, the local image may be deleted (depending on the exact infrastructure running the workflow). If these steps are being run on a local computer, these images are still typically pulled from a central repository at least once. Would this qualify as "use in the cloud"? What if instead of the local computer, it was being run on a departmental cluster? What if that cluster was actually set up using a cloud infrastructure, such as AWS or Google, but only the lab members had access to it? At what point does this become the cloud?

Note, it is often _much_ more cost effective to use a system like AWS Batch as a cluster provider, since all resources are ephemeral and only spun up when jobs need to run. This system is still limited to a given lab, and is no different than a cluster consisting of servers within the lab itself, except in terms of cost to purchase and maintain.

I certainly want to honor the spirit of the meaning of the license for DIA-NN 1.9+, so am really hoping for clarification of that. Right now, we are still using 1.8 since I don't think the 1.9 license allows for our use case.

**Comment by vdemichev** [comment]
Hi Michael,

I assume 'cloud' should apply in the most broad sense, i.e. anything that can be considered cloud falls into this category, but I am not a lawyer, I cannot give a qualified commentary here. Please give us some time, as you can imagine, academic cloud licensing, and whether we want this to be free or paid, is something which we do consider quite important, but we are not yet ready to give a definitive answer.

Best,
Vadim

**Comment by mriffle** [comment]
Fair enough, that's how I was operating already so as to not violate the spirit of the license. I look forward to further developments, thanks.
