### ISSUE TITLE
match between run diabled

### ISSUE THREAD

**Issue by Li5459000** [vdemichev/DiaNN#1229]
Hi,

Thank you for developing such amazing software.

I have raw data files  A,B,C, and when I analyze them separately using DIA-NN, the results differ from when I analyze them together with match between runs disabled.

I understand that, in most cases, enabling match between runs is recommended.

**Comment by vdemichev** [comment]
Hi,

This will be like this if any of mass accuracies and the scan window are left at 0. Is this the case?

Best,
Vadim
