### ISSUE TITLE
Proteins.Identified == 0 in stats.tsv and pdf (1.9.2)

### ISSUE THREAD

**Issue by Kokoushin** [vdemichev/DiaNN#1231]
Hi Vadim,

The number of Proteins.Identified is 0 in stats.tsv and pdf report.
But pg.matrix is normal.
[diann.log.txt](https://github.com/user-attachments/files/17550701/diann.log.txt)

And I’m very surprised analysis speed is much faster than before.

Best,
Ko

**Comment by vdemichev** [comment]
Hi Ko,

Happens because of this:

> WARNING: protein inference is enabled but no FASTA provided - is this intended?

Best,
Vadim

**Comment by vdemichev** [comment]
Would you please be able to upload LFQ_Orbitrap_AIF_Condition_A_Sample_Alpha_02.raw somewhere, I will take a look?

**Comment by Kokoushin** [comment]
After re-copying the file, it was solved.
Thank you so much.

Best,
Ko
