### ISSUE TITLE
Producing predicted library from a tsv file

### ISSUE THREAD

**Issue by yangkl96** [vdemichev/DiaNN#1235]
Hi Vadim,

I am trying to predict a library with a given input tsv to produce a predicted.bin with the newest DIA-NN. I get the following error on Windows and Linux machines as of version 1.9.1. Versions 1.9 and earlier work fine. How can I fix this?

`2024-10-30 10:51:59 [INFO] - diann-linux --lib spectraRT.tsv --predict --threads 11 --strip-unknown-mods --predict-n-frag 100`
`2024-10-30 10:52:00 [INFO] - DIA-NN 1.9.2 (Data-Independent Acquisition by Neural Networks)`
`2024-10-30 10:52:00 [INFO] - Compiled on Oct 20 2024 02:59:53`
`2024-10-30 10:52:00 [INFO] - Current date and time: Wed Oct 30 10:52:00 2024`
`2024-10-30 10:52:00 [INFO] - Logical CPU cores: 32`
`2024-10-30 10:52:00 [INFO] - Predicted spectra will be saved in a binary format`
`2024-10-30 10:52:00 [INFO] - Thread number set to 11`
`2024-10-30 10:52:00 [INFO] - WARNING: unrecognised option [--strip-unknown-mods]`
`2024-10-30 10:52:00 [INFO] - Deep learning predictor will predict 100 fragments`
`2024-10-30 10:52:00 [INFO] - WARNING: protein inference is enabled but no FASTA provided - is this intended?`
`2024-10-30 10:52:00 [INFO] -`
`2024-10-30 10:52:00 [INFO] - 0 files will be processed`
`2024-10-30 10:52:00 [INFO] - [0:00] Loading spectral library spectraRT.tsv`
`2024-10-30 10:52:00 [INFO] - [0:00] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)`
`2024-10-30 10:52:00 [INFO] - [0:00] Spectral library loaded: 0 protein isoforms, 0 protein groups and 20771 precursors in 18425 elution groups.`
`2024-10-30 10:52:00 [INFO] - ERROR: library contains fragments with invalid/unspecified charges`

My spectraRT.tsv looks like this:
`peptide	charge`
`SPAAAAALIFPG	3`

Thanks,
Kevin

**Comment by vdemichev** [comment]
Hi Kevin,

Thanks for letting me know, I will look into this. What happens is that in the --predict mode (special for FragPipe) DIA-NN just loads a precursor list and not the whole library, and then sometime after that a check for inappropriate fragment info kicks in. Will fix.

Best,
Vadim

**Comment by vdemichev** [comment]
Hi Kevin, will be fixed in the upcoming release. Was just a particular flag not being set when predicting for FragPipe.

Best,
Vadim
