### ISSUE TITLE
Spectral library generation difference between 1.91 and 1.9.2

### ISSUE THREAD

**Issue by 3399R** [vdemichev/DiaNN#1241]
Hello,

First off, thank you for developing such a great DIA tool.  I recently updated to 1.9.2 and while generating a spectral library I noticed that the file size is nearly half of what it is with the exact same fasta files in the same order with the same settings in 1.9.1.  Is this to be expected (1.9.2 = 0.86 GB, 1.9.1 = 1.5 GB)?  I noticed in the release notes it states "More than twice reduction of memory usage for the internal representation of the spectral library," but I'm not sure if that's how this would manifest.  Is this to be expected?  I also noticed that generating a spectral library no longer automatically saves the log file.  Is there a command that can be entered into the additional options that would fix this?  Not a big deal, but I don't always trust myself to remember to save it manually before starting to analyze my data.

Thank you

**Comment by vdemichev** [comment]
Yes :) We are working hard on making things compact!

>  I also noticed that generating a spectral library no longer automatically saves the log file.

Our oversight, we will fix in the next release.

> Not a big deal, but I don't always trust myself to remember to save it manually before starting to analyze my data.

We ourselves primarily rely on having this as a pipeline step, but yes, auto log is very helpful, will get it back.

**Comment by 3399R** [comment]
Great!  Thank you for the quick response.
