### ISSUE TITLE
diann stop working (1.9.2)

### ISSUE THREAD

**Issue by Kokoushin** [vdemichev/DiaNN#1251]
Hi,

I have a old spare windows pc, and I’d like to use it to run some DIA data analyses but it shows the error as follow (version 1.9.2).
The 1.8.1 works fine at this pc.
![图片1](https://github.com/user-attachments/assets/d6874623-2c9f-495e-b749-8bcb4a0bf494)

Best,
Ko

**Comment by vdemichev** [comment]
Hi Ko,

Maybe some incompatibility with Windows 7. What output do you see if you launch diann.exe from the command line?

Best,
Vadim

**Comment by Kokoushin** [comment]
Thank you for the reply.

Launch diann.exe from the command line like this?
![Picture1](https://github.com/user-attachments/assets/e409bd1d-8c38-4e61-92e1-54d91229ded5)

**Comment by Kokoushin** [comment]
It shows as follow.
![图片1](https://github.com/user-attachments/assets/b67de55f-2f68-4be6-b6f5-b824d9362682)
![图片2](https://github.com/user-attachments/assets/8e837f40-1fc4-4db1-8a83-9ff0491e1e4d)

**Comment by vdemichev** [comment]
OK, thank you for letting me know, some incompatibility with Windows 7.

Best,
Vadim
