### ISSUE TITLE
Wrong DiaNN Version in README

### ISSUE THREAD

**Issue by hollenstein** [vdemichev/DiaNN#1254]
Hi,

This is not a big issue. I just wanted to let you know that the download link at the beginning of the README is still for version 1.9.1 instead of 1.9.2 (I noticed because I accidently installed the old version first =)

**Text in README:**
_Download: https://github.com/vdemichev/DiaNN/releases/tag/1.9.1 (it's recommended to use the latest version - DIA-NN 1.9.1)_

Thanks for this great software and have a nice day.

Best,
David

**Comment by vdemichev** [comment]
Hi David,

Thanks for spotting this!

Best,
Vadim

**Comment by hollenstein** [comment]
Looks good, thanks for fixing it. I guess you can close the issue =).
