### ISSUE TITLE
Transferring DNN model from one run to another?

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#126]
Is it possible to save the DNN model from one run and apply it for another run? I would like to use this approach to address the case where the number of confident IDs is not sufficient to generate a DNN model.

**Comment by vdemichev** [comment]
No, it's not, although it's technically possible to implement this. But it happens vey rarely and only on very specific samples that NNs are not trained properly, and in those cases DIA-NN automatically reverts to a linear classifier.
