### ISSUE TITLE
Where is version 1.8?

### ISSUE THREAD

**Issue by caldodge** [vdemichev/DiaNN#127]
I downloaded the tarball offered by the site for version 1.8.  But diann.cpp says it's version 1.7.12.

So where do I download version 1.8?

**Comment by vdemichev** [comment]
Please use this link 
![image](https://user-images.githubusercontent.com/30595084/124294974-ff35ee80-db60-11eb-9622-80c6fdf43d43.png)
https://github.com/vdemichev/DiaNN/releases/tag/1.8

**Comment by vdemichev** [comment]
It's only available as an installer, without the source code.
