### ISSUE TITLE
When will 1.8 source be available?

### ISSUE THREAD

**Issue by caldodge** [vdemichev/DiaNN#128]
The source found in release 1.8 is actually the 1.7.12 version. This is also true of the source obtained through "git clone".
We tried to use the 1.8 rpm, but are encountering severe difficulties in building the required dependency (glibc 2.27) on Centos 7.5.

Will the actual 1.8 source be available soon?

**Comment by vdemichev** [comment]
The source will not be released. Glibc 2.27 is essential for C++ 17 support, and DIA-NN does rely on it heavily. It would not be easy for me to adapt it not to use C++17, thus, unfortunately, need to require glibc. I wonder, would running it under Docker solver the problem? Can just run it under the standard Docker Ubuntu image I guess (I think it's 18.04 they have).

Best,
Vadim

**Comment by guoci** [comment]
@vdemichev If you can send me the source code. I can compile DIA-NN against an older Glibc to make it available to more users.
We are planning to release FragPipe with DIA-NN soon, so it would be great if we can resolve the Glibc issue.
