### ISSUE TITLE
Should CAMthiopropanoyl-Modification Be Set as a Dynamic or Static Modification?

### ISSUE THREAD

**Issue by 95dari** [vdemichev/DiaNN#1280]
Hi,

I did cell surface protein enrichment experiment using Pierce™ Cell Surface Protein Isolation Kit.
I used Sulfo-NHS-SS-Biotin, so the cleaved biotin modification is CAMthiopropanoyl (MW= 145.020 Daltons).
And I ran DIA and wanted to search using DIA-NN.

should I CAMthiopropanoyl be set as dynamic(variable) mod or static(fixed) mod? 

And How can I interpret the data?

If I put CAMthiopropanoyl as a variable mod, then could I used report.pg_martix for identifying and quantifying for cell surface enriched protein? or should I do any data processing using report.tsv? 

I set the parameter for this experiment, is it correct? 
![image](https://github.com/user-attachments/assets/970bf095-c4c2-4422-844c-460cf450cb02)

I'm looking forward to a great answer. Thank you!

Dayeon

**Comment by vdemichev** [comment]
Hi Dayeon,

> should I CAMthiopropanoyl be set as dynamic(variable) mod or static(fixed) mod?

If you are only interested in peptides with modification present, and you expect modification occupancy to be high, then fixed.

> or should I do any data processing using report.tsv?

Always recommended to use the main .parquet report. The only reason not to use it is if you only work in Excel.

> I set the parameter for this experiment, is it correct?

No, predicted lib generation needs to be done in a separate pipeline step.
Precursor charge range: limit to 3 or 4.
Scan window: fix to the value DIA-NN recommends for your experiment.
Max var mods: better set to 1 or 2.

Best,
Vadim

**Comment by szabzola** [comment]
Hi Dayeon,
In my experience this modification has low occupancy, so I always use variable modification. Especially, if you do enrichment at protein level (before digestion), which is not clear from your description (only extracellular peptides of transmembrane proteins are modified).
Optimal setup (importance of modification) also depends on your aim: whether you are intereseted in peptide topology (you search for modified peptides) or protein quantification (unmodified/intracellular peptides may be more suitable, with lower variance and missed cleavage).
/But also, if you are interested in identification of modified peptides, I would measure with higher upper m/z limit (because of +145/z shift AND missed Trypsin cleavage caused by modification)./
Best regards,
Zoltan

**Comment by 95dari** [comment]
> Hi Dayeon,
> 
> > should I CAMthiopropanoyl be set as dynamic(variable) mod or static(fixed) mod?
> 
> If you are only interested in peptides with modification present, and you expect modification occupancy to be high, then fixed.
> 
> > or should I do any data processing using report.tsv?
> 
> Always recommended to use the main .parquet report. The only reason not to use it is if you only work in Excel.
> 
> > I set the parameter for this experiment, is it correct?
> 
> No, predicted lib generation needs to be done in a separate pipeline step. Precursor charge range: limit to 3 or 4. Scan window: fix to the value DIA-NN recommends for your experiment. Max var mods: better set to 1 or 2.
> 
> Best, Vadim

**Comment by 95dari** [comment]
> Hi Dayeon, In my experience this modification has low occupancy, so I always use variable modification. Especially, if you do enrichment at protein level (before digestion), which is not clear from your description (only extracellular peptides of transmembrane proteins are modified). Optimal setup (importance of modification) also depends on your aim: whether you are intereseted in peptide topology (you search for modified peptides) or protein quantification (unmodified/intracellular peptides may be more suitable, with lower variance and missed cleavage). /But also, if you are interested in identification of modified peptides, I would measure with higher upper m/z limit (because of +145/z shift AND missed Trypsin cleavage caused by modification)./ Best regards, Zoltan

Thank you for kind reply :)

What is mean that measuring with higher upper m/z limit? 

Best regards,
Dayeon
