### ISSUE TITLE
DIA-NN 1.9.2 only generating first-pass reports

### ISSUE THREAD

**Issue by SahilCh95** [vdemichev/DiaNN#1284]
Hi Vadim,

I've been having some trouble getting the main report.tsv file at the end of my DIA-NN run. 

Maybe I'm doing something incorrectly, so I'll first just give you a step-by-step explanation of what I did. I first generated an in-silico spectral library using a FASTA file in the first run. Following this, I then removed the FASTA files, and loaded in the .spec.lib file that was generated. I then loaded in my .RAW MS files (68 in total), selected my output folder, and an output folder for the DIA-based library (.parquet file). I added the "--report-lib-info" flag in the additional options box because I wanted fragment intensities in the final report. 

I ran this overnight, but I didn't see a final report.tsv file or the report.pdf file (this box was also ticked). I only saw the first-pass.tsv files. Strangely enough, I ran DIA-NN again, just using only one of my MS files this time (using the same predicted spectral library) and it generated a report.tsv file. The only thing I think I did differently is I check-marked the "Generate Spectral Library" option in the output section (see attached screenshot). I'm trying to process all my samples again, to see if this fixes the issue, but I was wondering if this is a known issue? I unfortunately did not save the log for the first run, but I have attached a log for the run that is currently in progress (don't know if this will help). I should also mention that I have successfully analyzed these samples on a previous version of DIA-NN (1.8.2). Any help will be appreciated!

Thanks,
Sahil

[November 27th 2024 In-Progress Log.txt](https://github.com/user-attachments/files/17940038/November.27th.2024.In-Progress.Log.txt)

![November 27th 2024 - Image](https://github.com/user-attachments/assets/a1850fbe-2754-490e-8f01-670a37963e09)

**Comment by vdemichev** [comment]
Hi Sahil,

This is a crash, is it possible that DIA-NN ran out of RAM? 
I can suggest the following to work around this at the moment:
1. Run the analysis of the raw files with "D:\Sahil Data\MS Data\SC024\DIA-NN\November 27th 2024\Spectral Library from SC024 Sample Runs\November 27th 2024 - Sample Spectral Library.parquet" as the spectral library and with MBR disabled. This will allow for almost instant reanalysis by reusing quant files and help me troubleshoot if it crashes again.
2. If still crashes, try with (2.1) normalisation disabled or (2.2) QuantUMS disabled (legacy quant mode) - this will help to figure out what's the reason. Can you please let me know the results?

Best,
Vadim

**Comment by SahilCh95** [comment]
Hi Vadim,

I tried doing another run yesterday. This time I also reinstalled a different MSFileReader version (I had 3.1, I think the documentation recommends 3.0), to see if that fixes my issue. Turns out it crashed again. 

I tried what you suggested, I replaced the spec.lib file generated from the FASTA with the .parquet file generated from the the sample runs. Also I disabled MBR, and left the "Reuse .quant files" box unchecked (I tried enabling it, but it would not run and gave me an error saying the .quant files were generated with a different spectral library). This run doesn't seem like it crashed, it generated a final report file. I am attaching the full log, as well as the log I used for the spectral library generation (.spec.lib file). Do you think it's a RAM-related issue? I was monitoring this run, and it was hitting around 13 GB out of the 16 GB that this computer has. Also is this report.tsv file good to use for downstream data-analysis, or would you recommend trouble-shooting the crash first, and then using non-crash run generated report file?


[Library Generation Log.txt](https://github.com/user-attachments/files/17962623/Library.Generation.Log.txt) 
[November 29th 2024 - Full Log.txt](https://github.com/user-attachments/files/17962622/November.29th.2024.-.Full.Log.txt)

**Comment by vdemichev** [comment]
> Do you think it's a RAM-related issue? I was monitoring this run, and it was hitting around 13 GB out of the 16 GB that this computer has. 

Oh yes, that's very little. Either that or (i) a bug in DIA-NN or (ii) something incorrect about input (settings are correct, but like corrupted file and issufficient QC of input in DIA-NN).
