### ISSUE TITLE
ERROR: C:\diann\src\diann.cpp: 2527: unknown modification: Phospho

### ISSUE THREAD

**Issue by wabash2011** [vdemichev/DiaNN#129]
Vadim, 
Thanks for keeping improving the performance of DIA-NN. We are using spectral libraries generated from Spectronaut. And DIA-NN older version (1.7.10 or 1.7.12) has no problem in recognizing all the modifications in the spectral library generated from Spectronaut.  But reprocessing the DIA RAW files with the new version 1.7.16 or 1.8 always ends in early exit. Some error messages were listed as below:
ERROR: C:\diann\src\diann.cpp: 2527: unknown modification: Acetyl (Protein N-term)
ERROR: C:\diann\src\diann.cpp: 2527: unknown modification: Phospho

Is there any way to fix the errors?

**Comment by vdemichev** [comment]
Hi, please share the full log, cannot really tell what's happening without it. In general, this kind of error messages should not occur. However if they do, all you need is declare the modifications using the --mod command https://github.com/vdemichev/DiaNN#command-line-reference.

Best,
Vadim

**Comment by wabash2011** [comment]
Thanks @vdemichev . Now DIA-NN works fine, when the specified modifications were declared.

**Comment by vdemichev** [comment]
Can you please still share the full log without specifying the modifications? To figure out what was not working?
