### ISSUE TITLE
Protein Inference

### ISSUE THREAD

**Issue by SahilCh95** [vdemichev/DiaNN#1290]
Hi Vadim,

I had a quick question about using protein inference while doing an in-silico library-based search. I was going through the log, and I see this warning - "WARNING: protein inference is enabled but no FASTA provided - is this intended?" 

Should I be turning protein inference off while doing a library-based search? Will leaving it on affect the final results? 

Also, what is the "No protein annotation detected,  skipping q value calculation" message referring to? I notice it show up for my samples when the samples are being compared to the sample spectral library. Is that an error?

I'm attaching the full log with this post.
[SC024 - December 2nd 2024 - Report.log.txt](https://github.com/user-attachments/files/17985085/SC024.-.December.2nd.2024.-.Report.log.txt)

Thanks, 
Sahil

**Comment by vdemichev** [comment]
Hi Sahil,

In general it's just best ti provide the FASTA.

Best,
Vadim

**Comment by SahilCh95** [comment]
Hi Vadim,

So you mean even when doing a library-based search, the FASTA should be provided?

-Sahil

**Comment by vdemichev** [comment]
If the library already contains properly assembled and annotated protein groups - no. In all other cases FASTA needs to be provided.

**Comment by vdemichev** [comment]
Yes, you still need FASTA.
You will not get any warning messages if you provide the FASTA.

**Comment by SahilCh95** [comment]
Okay that sounds good! Thanks Vadim!
