### ISSUE TITLE
Clarification how "isoforms" are parsed from Fasta-header (pg-level 0 vs pg-level 1)

### ISSUE THREAD

**Issue by jjGG** [vdemichev/DiaNN#1291]
Hello Vadim and Community,

We are frequently using DIANN as our search-and-quant-tool. More and more often we do use this for also non-uniprot databases (e.g. in case of Metaproteomics projects where the AA-fasta was generated from sequencing data directly).

My question:
- you mention that for non-uniprot databases one should always use "pg-levle 0" (aka "isoforms")
`--pg-level [N] controls the protein inference mode, with 0 - isoforms, 1 - protein names (as in UniProt), 2 - genes`

Given the uniprot fasta header information page (https://www.uniprot.org/help/fasta-headers)
`>db|UniqueIdentifier|EntryName ProteinName OS=OrganismName OX=OrganismIdentifier [GN=GeneName ]PE=ProteinExistence SV=SequenceVersion`

Can you quickly elaborate what DIANN is taking into account here as "isoform"? Is this simply the "UniqueIdentifer|EntryName"

or is it trying to parse isoforms differently from the fasta header?

Best regards
jonas

**Comment by vdemichev** [comment]
Hi Jonas,

'isoform' in DIA-NN means the unique sequence identifier.

Best,
Vadim

**Comment by jjGG** [comment]
Hei Vadim, 

Thanks for the clarification. This is what I was hoping ;).
