### ISSUE TITLE
Question about Q-values and MBR

### ISSUE THREAD

**Issue by SahilCh95** [vdemichev/DiaNN#1297]
Hi Vadim,

Firstly thank you for taking time out of your day to answer my queries, and I apologize for the constant barrage of questions! 

I had 3 quick clarifying question about the precursor Q-values that are included in main report file as well as a couple of questions about MBR.

1) Do Q-values convey the confidence with which a particular precursor has been mapped to a specific peptide, or are they meant to convey some other kind of information as well?

2) When enabling MBR, we should be relying on the Lib.Q.Values instead of the Global ones, am I correctly understanding this?

3) Is it okay to ignore the "Warning: MBR has been off, 2 or more files required", when generating a spectral library from a FASTA file? As per my understanding you want MBR to be turned off when generating spectral libraries and only want to turn it on when doing the actual quantification. So in this case, MBR being turned off is the correct scenario?

Thanks,
Sahil

**Comment by vdemichev** [comment]
Hi Sahil,

1. In a sense: please note the difference between q-values and PEPs (posterior error probabilities).
2. Please see https://github.com/vdemichev/DiaNN?tab=readme-ov-file#match-between-runs.
3. All OK, just tells you that MBR (automatically checked by GUI) will be deactivated - which of course makes total sense here, it's not related to in silico prediction.

Best
Vadim

**Comment by SahilCh95** [comment]
Thanks Vadim!
