### ISSUE TITLE
Linux version reads in a limited number of precursors from fasta.

### ISSUE THREAD

**Issue by MatteoLacki** [vdemichev/DiaNN#130]
Hi,

First of all, thank you for a great software and trying to make it work on Linux.
I have a question: somehow we cannot run the command line version without getting into problems with (most likely) poor parsing of the fasta file.

We are essentially trying to do fasta-search.
We have installed the binaries.
I have data locally at /data/external/bruker/ (6 raw folders from Bruker)
I have a fasta file containing only human proteins downloaded today from uniprot.
Here is the first entry to confirm the format is OK:

>sp|P18440|ARY1_HUMAN Arylamine N-acetyltransferase 1 OS=Homo sapiens OX=9606 GN=NAT1 PE=1 SV=2
MDIEAYLERIGYKKSRNKLDLETLTDILQHQIRAVPFENLNIHCGDAMDLGLEAIFDQVV
RRNRGGWCLQVNHLLYWALTTIGFETTMLGGYVYSTPAKKYSTGMIHLLLQVTIDGRNYI
VDAGFGRSYQMWQPLELISGKDQPQVPCVFRLTEENGFWYLDQIRREQYIPNEEFLHSDL
LEDSKYRKIYSFTLKPRTIEDFESMNTYLQTSPSSVFTSKSFCSLQTPDGVHCLVGFTLT
HRRFNYKDNTDLIEFKTLSEEEIEKVLKNIFNISLQRKLVPKHGDRFFTI

We have made the mass-accuracy lower to be sure that no stringent filtering is in place that would minimize the number of precursors, but it is stil there.

Here is the command:

/usr/diann/1.8/diann-1.8 --f /data/external/bruker/HYE_A_200ng_100min_dia_Slot1-46_1_5000.d --f /data/external/bruker/HYE_A_200ng_100min_dia_Slot1-46_1_5001.d --f /data/external/bruker/HYE_A_200ng_100min_dia_Slot1-46_1_5002.d --f /data/external/bruker/HYE_A_200ng_100min_dia_Slot1-46_1_5000.d --f /data/external/bruker/HYE_B_200ng_100min_dia_Slot1-47_1_5005.d --f /data/external/bruker/HYE_B_200ng_100min_dia_Slot1-47_1_5005.d --fasta /home/matteo/Projects/DiaNN/homo_sapiens.fasta --out /home/matteo/Projects/DiaNN/TEST/demo_report.tsv --lib --threads 128 --verbose 1 --qvalue 0.01 --matrices --predictor --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut K,R,!*P --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --reanalyse --smart-profiling --pg-level 2 --species-genes --mass-acc 50 --mass-acc-ms1 25 --peak-center -window 20 --mod UniMod:4,57.021464

I really hope that this is something totally stupid on my side and we can quickly fix it ;)

I attach the log files.
[log_diann_1.8.txt](https://github.com/vdemichev/DiaNN/files/6764413/log_diann_1.8.txt)

Best wishes,

Matteo Lacki,
TENZER LAB
Mainz

**Comment by vdemichev** [comment]
Hi Matteo,

All FASTA entries should start with '>', that is ">sp|..." - most likely that is the problem. Please let me know if this is the case. If any other problems with the FASTA occur, please try to see if it's OK with a standard UniProt reference proteome.

Best,
Vadim

**Comment by vdemichev** [comment]
50ppm is crazily high. Will indeed result in slightly less missing fragment ion signals, but will also lead to a significant increase in the number of interfering signals - it might be that like >90% of the extra non-zero signals will actually originate from interferences. So most likely it will be strongly detrimental to the performance, unless really need to avoid zero signals for some very specific purpose.

Vadim

**Comment by MatteoLacki** [comment]
Hello Vadim,

I am afraid that simply swapping  ">sp|"  for ">"  does not work.
[log_no_sp.txt](https://github.com/vdemichev/DiaNN/files/6765657/log_no_sp.txt)
What do you mean when you mention "standard UniProt reference proteome"?
I simply download human proteins from Uniprot with
wget -O human.fasta "http://www.uniprot.org/uniprot/?query=reviewed:yes+AND+organism:9606&format=fasta"

Already on `human.fasta` I do not get any precursors on Linux: on Windows we do.
I would be ultimately interested in running `DIAnn` on a mixture of human + yeast + ecoli + contaminants, as in:

```{bash}
wget -O human.fasta "http://www.uniprot.org/uniprot/?query=reviewed:yes+AND+organism:9606&format=fasta"
wget -O yeast.fasta "http://www.uniprot.org/uniprot/?query=organism:643680&format=fasta"
wget -O ecoli.fasta "http://www.uniprot.org/uniprot/?query=reviewed:yes+AND+organism:83333&format=fasta"
wget -O contaminants.fasta "https://raw.githubusercontent.com/MatteoLacki/protein_contaminants/master/contaminants.fasta"
cat human.fasta yeast.fasta ecoli.fasta contaminants.fasta > hye.fasta
```
i.e. use `hye.fasta` instead.

Best wishes,

**Comment by vdemichev** [comment]
The digest specificity should be --cut K*,R*,!*P. It looks like as is (--cut K,R,!*P) it basically disables the digest, so those ~200 precursors generated come from short (<=30 aa) proteins only. I would suggest to just copy the correct command from either the Windows version of Windows version run with Wine (you can run the GUI (DIA-NN.exe) with Wine too). 

Best,
Vadim

**Comment by MatteoLacki** [comment]
OK, this indeed results in a significant change!
```
6 files will be processed
[0:00] Loading FASTA /home/matteo/Projects/DiaNN/human_no_sp.fasta
[0:02] Processing FASTA
[0:07] Assembling elution groups
[0:11] 4049812 precursors generated
[0:11] Gene names missing for some isoforms
[0:11] Library contains 5029 proteins, and 5029 genes
[0:11] Encoding peptides for spectra and RTs prediction
[0:17] Predicting spectra and IMs
```
I was almost sure that we have been copying the output from Windows though: I will have a second look at it tomorrow and report back. Thanks a lot for you extremely helpful comments.

**Comment by vdemichev** [comment]
Cool! Sure, happy to help, please don't hesitate to contact if there are any questions.

**Comment by MatteoLacki** [comment]
Hi,

we have traced back the error: it was entirely on our side and somewhat funny.
The thing is, that `*,R*` in  `-cut K*,R*,!*P` was translated to _,R_ by Mattermost, which we use as communication channel :)

Best wishes and sorry for trouble!
