### ISSUE TITLE
Mass Accuracy Calculation

### ISSUE THREAD

**Issue by SahilCh95** [vdemichev/DiaNN#1303]
Hi Vadim,

Couple of quick questions about the DIA-NN suggested mass accuracy settings. 

I wanted to figure out the optimal MS1 and MS2 accuracies for my data, so I followed what was suggested in the documentation. I loaded in my spectral library, along with my MS files (.RAW files, data acquired on an Exploris480). I set the mass accuracies to 0 ppm and selected the "Unrelated Runs" options so that the mass accuracies are calculated for all of my samples. In the first pass the averaged optimal mass accuracies were 30 ppm for MS2 and 10 ppm for MS1. For the second pass, DIA-NN suggested 32 ppm for MS2 and 10 ppm for MS1.

I also manually calculated the average MS1 and MS2 mass accuracies by taking the average of the all the individual optimal mass accuracies suggested by DIA-NN and I got ~26 ppm for MS2, ~10 ppm for MS1 in the first pass, and ~28 ppm for MS2 and ~10 ppm for MS1 in the second pass.

So based on this, I decided to go with 30 ppm MS2 and 10 ppm MS1 for my actual quantification since these value seemed to be somewhat in the middle of all the averaged mass accuracies. My questions/concerns are as follows - 

1) Have I gone about calculating the optimal mass accuracies in the correct manner?

2) Is the 30 ppm MS2 accuracy setting okay to use for DIA-NN analysis? The reason I ask is because to me it seems to be fairly high.

Thanks,
Sahil

**Comment by vdemichev** [comment]
Hi Sahil,

What you are doing seems a very sensible approach, all is correct. However, 30ppm indeed looks very strange for Exploris. Something is off. What's the gradient length and MS/MS resolution? Is this a single cell-like sample?

Best,
Vadim

**Comment by vdemichev** [comment]
One possible reason: incorrect masses in your spectral library. What's the source of the library?

**Comment by SahilCh95** [comment]
The gradient length is 90 minutes, and the spectral library was generated from a Human proteome FASTA file from Uniprot. I just added a couple of additional proteins (contaminants like streptavidin and trypsin) in there. 

These samples are turboID pulldowns.

**Comment by vdemichev** [comment]
> and the spectral library was generated from a Human proteome FASTA file from Uniprot.

By DIA-NN?

**Comment by SahilCh95** [comment]
Yes I did notice a lot of fluctuation in the optimal mass accuracies reported by DIA-NN, especially the MS2 accuracies. For some samples it would be around 15 ppm but for some it would maybe go up to 25-30 ppm. I did look at the data, and the percent CVs of data look fairly good (around 12-15% for most samples). 

Do you think from a publication standpoint, the use of these mass accuracies is justifiable? I have seen mass accuracies of up to 50 ppm used for Orbitrap instruments, however, this was for a phosphoprotein study.

**Comment by vdemichev** [comment]
> Do you think from a publication standpoint, the use of these mass accuracies is justifiable?

Absolutely no problem.

**Comment by SahilCh95** [comment]
Sorry Vadim, just wanted to clarify so you think the data generated using the 10 ppm MS1 and 30 ppm MS2 accuracies is okay for downstream processing and publication? 

(Also wanted to clarify, that for this turboID data we were not looking at any special PTMs or modifications, I only had N term Methionine excision and Cysteine methylation as the modifications)

Thanks,
Sahil

**Comment by SahilCh95** [comment]
Okay that sounds good. Thanks a lot for your prompt responses, I really appreciate it!

-Sahil

**Comment by SahilCh95** [comment]
Hi Vadim,

Sorry just wanted to follow-up on this quickly. Could I get your opinion on whether I'm generating my spectral library correctly? I just want to be sure the high MS2 accuracy is not because of some error on my part during the library generation step (i.e. wrong settings). I'm attaching the whole log for my library generation + quantification (Note - these were done in separate steps). I just realized that the "--report-lib-info" flag was in the additional options box during library generation and quantification (only meant to add it during the quantification stage), I wonder if that may affect the library generation?

(The library generation log is at the start of the text file)

Thanks again,
Sahil


[SC024 - December 4th 2024 - Full Log.txt](https://github.com/user-attachments/files/18106715/SC024.-.December.4th.2024.-.Full.Log.txt)

**Comment by vdemichev** [comment]
Hi Sahil,

Seems correct.

Best,
Vadim

**Comment by SahilCh95** [comment]
Okay so no problem with the spectral library generation?

Also I'm guessing mass accuracies and additional options set during library generation don't really affect the library?

**Comment by vdemichev** [comment]
I cannot see any problem in the settings. What is the MS/MS Orbitrap resolution setting?

**Comment by vdemichev** [comment]
Hi Sahil,

Yes, I assume 15k resolution may be the reason for poor mass acc.
Your data are perfectly fine, but it's most likely that better numbers could be obtained by copying some method for the instrument (e.g. published or from colleagues) that is know to perform well.

Best,
Vadim

**Comment by SahilCh95** [comment]
Hi Vadim,

That sounds good. I'll look into using a different MS2 resolution and see if that improves the mass accuracies. Thanks for your help!

-Sahil
