### ISSUE TITLE
results differ in combined and single file runs

### ISSUE THREAD

**Issue by animesh** [vdemichev/DiaNN#1317]
I am trying to compare results [reportcmd.gg_matrix - Copy.txt](https://github.com/user-attachments/files/18208894/reportcmd.gg_matrix.-.Copy.txt) from a combined search

```
C:\Program Files\DIA-NN\1.9.2>diann.exe --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAc_Slot1-28_1_9292.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAb_Slot1-28_1_9290.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAa_Slot1-28_1_9288.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAc_Slot1-29_1_9298.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAb_Slot1-29_1_9296.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAa_Slot1-29_1_9294.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_200ngHelaQC_DIA_Slot1-54_1_9286.d" --lib "F:\promec\FastaDB\UP000005640_9606_unique_gene_C24_MC1_P735_MZ1001700_Mod3.predicted.speclib" --threads 32 --verbose 1 --out "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\DIANN1p9p2\reportcmd.tsv" --qvalue 0.01 --matrices  --min-corr 2.0 --corr-diff 1.0 --time-corr-only --extracted-ms1 --reannotate --fasta camprotR_240512_cRAP_20190401_full_tags.fasta --cont-quant-exclude cRAP- --fasta "F:\promec\FastaDB\UP000005640_9606_unique_gene.fasta" --met-excision --min-pep-len 7 --max-pep-len 35 --min-pr-mz 100 --max-pr-mz 1700 --min-pr-charge 2 --max-pr-charge 4 --cut K*,R* --missed-cleavages 1 --unimod4 --var-mods 3 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --individual-mass-acc --individual-windows --peptidoforms --rt-profiling --direct-quant --no-norm
```
and just running the same over the [241217_20ngHelaQC_DIAc_Slot1-28_1_9292reportcmd.gg_matrix - Copy.txt](https://github.com/user-attachments/files/18208890/241217_20ngHelaQC_DIAc_Slot1-28_1_9292reportcmd.gg_matrix.-.Copy.txt) , the first file

```
C:\Program Files\DIA-NN\1.9.2>diann.exe --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAc_Slot1-28_1_9292.d" --lib "F:\promec\FastaDB\UP000005640_9606_unique_gene_C24_MC1_P735_MZ1001700_Mod3.predicted.speclib" --threads 64 --verbose 1 --out "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\DIANN1p9p2\241217_20ngHelaQC_DIAc_Slot1-28_1_9292reportcmd.tsv" --qvalue 0.01 --matrices  --min-corr 2.0 --corr-diff 1.0 --time-corr-only --extracted-ms1 --reannotate --fasta camprotR_240512_cRAP_20190401_full_tags.fasta --cont-quant-exclude cRAP- --fasta "F:\promec\FastaDB\UP000005640_9606_unique_gene.fasta" --met-excision --min-pep-len 7 --max-pep-len 35 --min-pr-mz 100 --max-pr-mz 1700 --min-pr-charge 2 --max-pr-charge 4 --cut K*,R* --missed-cleavages 1 --unimod4 --var-mods 3 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --individual-mass-acc --individual-windows --peptidoforms --rt-profiling --direct-quant --no-norm 
```

and getting difference in results
![image](https://github.com/user-attachments/assets/4749c6d5-526e-4f80-9c1e-b4cb92cd59ac)

scatter plot looks like

![image](https://github.com/user-attachments/assets/f825de94-13fd-4058-8f17-a0b04ccfcad2)

 what could be the issue here? i m guessing it must be the wrong way of invoking diann.exe, some switch is wrong maybe? Library was generated using following command line

```
#wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/Eukaryota/UP000005640/UP000005640_9606.fasta.gz
#gunzip UP000005640_9606.fasta.gz
#mv UP000005640_9606.fasta UP000005640_9606_unique_gene.fasta
diann.exe --lib "" --threads 32 --verbose 1 --out "C:\/Temp/report.tsv" --qvalue 0.01 --matrices  --out-lib "F:\promec\FastaDB\UP000005640_9606_unique_gene_C24_MC1_P735_MZ1001700_Mod3.parquet" --gen-spec-lib --predictor --fasta camprotR_240512_cRAP_20190401_full_tags.fasta --cont-quant-exclude cRAP- --fasta "F:\promec\FastaDB\UP000005640_9606_unique_gene.fasta" --fasta-search --min-fr-mz 100 --max-fr-mz 1700 --met-excision --min-pep-len 7 --max-pep-len 35 --min-pr-mz 100 --max-pr-mz 1700 --min-pr-charge 2 --max-pr-charge 4 --cut K*,R* --missed-cleavages 1 --unimod4 --var-mods 3 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --individual-mass-acc --individual-windows --peptidoforms --relaxed-prot-inf --rt-profiling

```

**Comment by vdemichev** [comment]
Hi Ani,

No reason why they should be the same. There are quite a number of cross-run algorithms in DIA-NN, including global FDR filters (applied to all the matrices) and selection of fragments for quant.

Best,
Vadim

**Comment by animesh** [comment]
Thanks @vdemichev , is there a way to ensure getting same results?

**Comment by vdemichev** [comment]
Yes, please see the parts of https://github.com/vdemichev/DiaNN?tab=readme-ov-file#frequently-asked-questions on incremental processing.

**Comment by animesh** [comment]
Thanks again @vdemichev , so i should add `--no-norm --no-maxlfq` to the command-line? Should i also remove the 
<img width="552" alt="image" src="https://github.com/user-attachments/assets/c8ec2639-7354-4cd0-af5b-e6e7fbd790b0" /> ?

**Comment by vdemichev** [comment]
Hi Ani, normally this 'incremental processing' is only needed when you process batches of patient samples arriving over a year+ period. In all other cases best is not to do this.

**Comment by animesh** [comment]
Yes @vdemichev , the data will be collected inctementally over coming years 🤞

**Comment by vdemichev** [comment]
Then there are two options: either make results really identical - disable everything cross-run in DIA-NN. Or just process batch by batch and apply batch correction (but at least fragment choice you want the same). So in either case you'd want to have a DIA-based lib with annotation which fragments to use for quant and inferred protein groups.

**Comment by animesh** [comment]
Yes @vdemichev that is what i am trying to do and the results are getting closer using the `--no-norm --no-maxlfq ` but i think i am still missing some switches as there are differences even at the level of Precursor.id, for example ran a single file  [report20ngHelaQC_DIAc.pr_matrix - Copy.txt](https://github.com/user-attachments/files/18217836/report20ngHelaQC_DIAc.pr_matrix.-.Copy.txt)


```
diann.exe --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAc_Slot1-28_1_9292.d"  --lib "F:\promec\FastaDB\UP000005640_9606_UP000087266_8030_unique_gene_C24_MC1_P735_MZ1001700_Mod3.predicted.speclib" --threads 32 --verbose 1 --out "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\DIANN1p9p2\Salmon\report20ngHelaQC_DIAc.tsv" --qvalue 0.01 --matrices  --min-corr 2.0 --corr-diff 1.0 --time-corr-only --extracted-ms1 --unimod4 --var-mods 3 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --individual-mass-acc --individual-windows --peptidoforms --relaxed-prot-inf --rt-profiling --direct-quant --no-norm --no-maxlfq
```

and then threw is bunch of other files from the same batch [report.pr_matrix - Copy.txt](https://github.com/user-attachments/files/18217835/report.pr_matrix.-.Copy.txt)


```

diann.exe --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAc_Slot1-28_1_9292.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAb_Slot1-28_1_9290.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_20ngHelaQC_DIAa_Slot1-28_1_9288.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAc_Slot1-29_1_9298.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAb_Slot1-29_1_9296.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_2ngHelaQC_DIAa_Slot1-29_1_9294.d" --f "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\241217_200ngHelaQC_DIA_Slot1-54_1_9286.d" --lib "F:\promec\FastaDB\UP000005640_9606_UP000087266_8030_unique_gene_C24_MC1_P735_MZ1001700_Mod3.predicted.speclib" --threads 32 --verbose 1 --out "F:\promec\TIMSTOF\LARS\2024\241219_Hela_DDA_DIA\dia\DIANN1p9p2\Salmon\report.tsv" --qvalue 0.01 --matrices  --min-corr 2.0 --corr-diff 1.0 --time-corr-only --extracted-ms1 --unimod4 --var-mods 3 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --individual-mass-acc --individual-windows --peptidoforms --relaxed-prot-inf --rt-profiling --direct-quant --no-norm --no-maxlfq
```

and below is the scatter i get at Precursor.id level

![image](https://github.com/user-attachments/assets/d3c5b718-249b-4858-946f-3d4b3cbaaa31)


so i am guessing there is still some cross-run going on? If so, what all switches i should use or not use to disable it? or i am just comparing wrong thing?

**Comment by vdemichev** [comment]
Hi Ani,

Can you please show the full logs? 
Btw, this is not the reason, but for your scenario it makes sense to use an empirical and not predicted lib and to keep mass accuracies & scan window fixed.

Best,
Vadim

**Comment by animesh** [comment]
Of course, [report20ngHelaQC_DIAc.log.txt](https://github.com/user-attachments/files/18217849/report20ngHelaQC_DIAc.log.txt) and [report.log.txt](https://github.com/user-attachments/files/18217850/report.log.txt) for single and bunch runs respectively 🤞

**Comment by vdemichev** [comment]
Thank you, 

> WARNING: protein inference is enabled but no FASTA provided - is this intended?

Will make protein q-value and quantities different.

**Comment by animesh** [comment]
These are Precursor.id though?

**Comment by vdemichev** [comment]
Yes, and the reason is lack of --no-fr-selection.

**Comment by vdemichev** [comment]
With 1.9.1 and later it's very easy with 100% same quant:
just use --export-quant and you get raw fragment quantities in convenient format in the .parquet report.

**Comment by animesh** [comment]
OK, so i remove `--peptidoforms --relaxed-prot-inf` and add  ` --mass-acc 20.0 --mass-acc-ms1 20  --export-quan --no-fr-selection ` or...?

**Comment by vdemichev** [comment]
Can keep --peptidoforms and --relaxed-prot-inf, but need an empirical lib.

**Comment by animesh** [comment]
BTW why do we need to provide the fasta file, is the header not preserved in predicted lib?

**Comment by vdemichev** [comment]
> BTW why do we need to provide the fasta file, is the header not preserved in predicted lib?

Not fully.

**Comment by animesh** [comment]
OK so by empirical lib you mean the lib+Fasta file used to create the lib or...?

**Comment by vdemichev** [comment]
A DIA-based lib, i.e. searching raw data with a predicted lib with 'Generate spectral library' produces an empirical lib in .parquet format.

**Comment by animesh** [comment]
That worked @vdemichev 💯 Thanks a tonne for your (en)lightening-speedy and very helpful response 👍🏽 
<img width="451" alt="image" src="https://github.com/user-attachments/assets/82e36793-ba29-4da0-835e-0884a60efbeb" />

**Comment by vdemichev** [comment]
Super :) !
