### ISSUE TITLE
DIA-NN exits after library step

### ISSUE THREAD

**Issue by L4ft2di3** [vdemichev/DiaNN#137]
Dear Vadim,

I encountered an issue with the newest DIA-NN version. After the library development step, DIA-NN exits and i get a notification window with the corresponding message. I already tried a program restart and reinstall and different files to be analyzed, however without success. Do you have a suggestion, what might be the issue here?

Best regards
Thorben

Logfile text:

C:\DIA-NN\1.8\DiaNN.exe --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011502_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011529_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011561_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011609_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011612_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011618_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011620_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011704_1.wiff
" --f "E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011734_1.wiff
" --lib "" --threads 16 --verbose 1 --out "E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\report.tsv" --qvalue 0.01 --matrices  --out-lib "E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\test_report.tsv" --gen-spec-lib --predictor --fasta "E:\02_Fasta_Databases\20200624 Human Swiss-Prot.fasta" --fasta-search --min-fr-mz 350 --max-fr-mz 1250 --met-excision --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --reanalyse --smart-profiling 
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 14:55:31
Current date and time: Mon Jul 12 10:52:18 2021
CPU: GenuineIntel Intel Xeon Processor (Cascadelake)
SIMD instructions: AVX AVX2 AVX512CD AVX512F FMA SSE4.1 SSE4.2 
Logical CPU cores: 16
Thread number set to 16
Output will be filtered at 0.01 FDR
Precursor/protein x samples expression level matrices will be saved along with the main report
A spectral library will be generated
Deep learning will be used to generate a new in silico spectral library from peptides provided
Library-free search enabled
Min fragment m/z set to 350
Max fragment m/z set to 1250
N-terminal methionine excision enabled
In silico digest will involve cuts at K*,R*
Maximum number of missed cleavages set to 1
Min peptide length set to 7
Max peptide length set to 30
Min precursor m/z set to 300
Max precursor m/z set to 1800
Min precursor charge set to 1
Max precursor charge set to 4
Cysteine carbamidomethylation enabled as a fixed modification
A spectral library will be created from the DIA runs and used to reanalyse them; .quant files will only be saved to disk during the first step
When generating a spectral library, in silico predicted spectra will be retained if deemed more reliable than experimental ones
DIA-NN will optimise the mass accuracy automatically using the first run in the experiment. This is useful primarily for quick initial analyses, when it is not yet known which mass accuracy setting works best for a particular acquisition scheme.

9 files will be processed
[0:00] Loading FASTA E:\02_Fasta_Databases\20200624 Human Swiss-Prot.fasta
[0:06] Processing FASTA
[0:16] Assembling elution groups
[0:25] 4226804 precursors generated
[0:25] Gene names missing for some isoforms
[0:25] Library contains 20329 proteins, and 20121 genes
[0:25] Encoding peptides for spectra and RTs prediction
[0:35] Predicting spectra and IMs
[51:04] Predicting RTs
[57:36] Decoding predicted spectra and IMs
[57:43] Decoding RTs
[57:49] Saving the library to E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\test_report.predicted.speclib
[58:01] Initialising library

[58:03] First pass: generating a spectral library from DIA data
[58:03] File #1/9
[58:03] Loading run E:\01_Projects\01_Intern\Serum_FR_FT\Raw Files\FR\011502_1.wiff

DIA-NN exited
DIA-NN-plotter.exe "E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\report.stats.tsv" "E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\report.tsv" "E:\01_Projects\01_Intern\Serum_FR_FT\Results\test\report.pdf"
PDF report will be generated in the background

**Comment by vdemichev** [comment]
Hi Thorben,

Please follow the instructions here https://github.com/vdemichev/DiaNN#raw-data-formats on how to enable .wiff support. Please let me know if this helps.

Best,
Vadim

**Comment by L4ft2di3** [comment]
Hi Vadim,

damn, I totally forgot the ProteoWizard files. This, indeed did the trick.
As always, thank you for your swift answers.

All the best
Thorben
