### ISSUE TITLE
config file format

### ISSUE THREAD

**Issue by kevinkovalchik** [vdemichev/DiaNN#140]
Hello,

When we pass a config file using the `--config` argument, what is the expected format of the file? I tried a few basic formats but didn't find one that worked, and I did not see an example anywhere.

Thanks!
Kevin

**Comment by vdemichev** [comment]
Hi Kevin,

Please see the documentation here https://github.com/vdemichev/DiaNN, it's been significantly expanded with the release of DIA-NN 1.8. The command is '--cfg [file name]' (without quotes, e.g. --cfg my_config.txt), the file can contain commands/options, syntax is the same as when using the 'Additional options' textbox. 

Best,
Vadim

**Comment by kevinkovalchik** [comment]
Hi Vadim,

Thanks for the quick response. So the format would simply be the command line arguments inside a text file with no other formatting? I tried this but am getting an error:
```
/usr/diann/1.8/diann-1.8 --cfg /Data/Development/Validator/validation_experiments/library-free-dia/convert-to-dia-format.cfg 
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Wed Jul 14 09:44:02 2021
Logical CPU cores: 12
WARNING: failed to open cfg file

0 files will be processed
```
Here are the contents of the config file:
```
--convert --dir /Data/Development/Validator/validation_experiments/library-free-dia/
```

I am using Linux, by the way (Ubuntu 20.04).

Thanks,
Kevin

**Comment by vdemichev** [comment]
Maybe the path is specified incorrectly? I would try "Data/" instead of "/Data", or just use an absolute path.

**Comment by kevinkovalchik** [comment]
I know it looks kind of weird, but I have a drive mounted at "/Data" so it is an absolute path.
Just to double check I tried to read the file from the terminal using the path I provided to `--cfg` and I was able to do so, so the path is okay.

**Comment by vdemichev** [comment]
I would try to see if a different path would work. Can also try putting the path in  " " double quotes.

**Comment by vdemichev** [comment]
Right/permissions for the .cfg file? Try chmod/running sudo?

**Comment by vdemichev** [comment]
Hi Kevin, any update, have you managed to make it work?

**Comment by kevinkovalchik** [comment]
Hi Vadim,

Sorry for not getting back to you about it. I did not figure out a solution. It wasn't a problem with permissions.

When I don't try to use a config file everything runs fine, so I ended up just using a bash script to make sure I used the same commands for each analysis.

Kevin

**Comment by zhanxw** [comment]
I experienced the same issue as @kevinkovalchik , and I ended up with a similar solution. e.g., 

    /usr/diann/1.8/diann-1.8 `cat /Data/Development/Validator/validation_experiments/library-free-dia/convert-to-dia-format.cfg`

**Comment by cpanse** [comment]
@vdemichev same problem --cfg option is not working on Linux

```
cpanse@fgcz-r-033:/scratch/cpanse/vib > /usr/diann/1.8.1/diann-1.8.1 --cfg plate1-config.txt 
DIA-NN 1.8.1 (Data-Independent Acquisition by Neural Networks)
Compiled on Apr 15 2022 08:45:18
Current date and time: Tue Dec 20 07:58:02 2022
Logical CPU cores: 128
WARNING: failed to open cfg file

0 files will be processed
```

workaround ?
```
/usr/diann/1.8.1/diann-1.8.1 $(cat plate1-config.txt)
```

**Comment by fcyu** [comment]
It might be due to a bug: https://github.com/vdemichev/DiaNN/pull/222 

In FragPipe, we have to create the file with a space at the end of the file name: https://github.com/Nesvilab/FragPipe/blob/3e0189ecb8478ed8ce614bfd8bbcdee98ea05b5c/MSFragger-GUI/src/com/dmtavt/fragpipe/cmd/CmdDiann.java#L225

Hope this will be helpful.

Best,

Fengchao
