### ISSUE TITLE
library-free search

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#150]
I have two questions regarding spectral library generation function in DIA-NN.

1. To generate a spectral library for library-free search, is it possible to use a FASTA that contains only peptide sequences and use "no protease" or "no digestion" option?
2. I have a dataset that contains chemically labeled peptides but the modification unimod ID is not recognized by DIA-NN. and I think the modification is not supported by deep learning MS/MS predictor anyway. However, we expect to see no change on MS/MS pattern for those labeled peptides and only corresponding b/y fragment m/z will be shifted. Is it possible to adjust DIA-NN's spectral library generation module to shift fragment m/z for those labeled peptides?

**Comment by vdemichev** [comment]
1. Yes.
2. Can just declare the modification with --fixed-mod and apply deep learning in combination with --strip-unknown-mods. For just shifting the masses in the spectral library can use --lib-fixed-mod [mod name], where the modification was previously declared with --fixed-mod.
