### ISSUE TITLE
Analyze one file against multiple .speclib files?

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#161]
Can we analyze one file by multiple .speclib library files? Basically, combining the libraries and evaluate FDR at once?
Or is there any tool that we can use to combine multiple .speclib files into a single library file?

**Comment by vdemichev** [comment]
You can convert the .speclib libraries to .tsv and then just load all of
them at once, by specifying multiple --lib commands (one per library) in
the Additional options text box.

Best,
Vadim

**Comment by cctsou** [comment]
Thanks a lot!!
