### ISSUE TITLE
The difference in qualitative and quantitative strategies of different ways to submit several files to DIANN queue.

### ISSUE THREAD

**Issue by Mnago** [vdemichev/DiaNN#163]
Hi Vadim,

I wondering if the following cases have any different qualitative and quantitative strategies.

1st,
Several files were submitted one by one.

2nd,
Several files were submitted together but using the  "unrelated runs parameter.

Best regards,

**Comment by vdemichev** [comment]
HI Mnago, 

Identification will be the same. And you don't even need 'unrelated runs' for this, if you fix the values for mass accuracies and the scan window. However the quantities will only be the same if you turn off cross-run normalisation and also use --restrict-fr in combination with --no-fr-selection. Protein inference will not work the same way.

Best,
Vadim

**Comment by Mnago** [comment]
Vadim,

OK, thanks.

Mnago

**Comment by Mnago** [comment]
Hi Vadim,

I have checked there is no option to turn off cross-run normalization on DIANN1.7.15. I am wondering whether it is ok to use - -no-norm to disabled the cross-run analysis.

Best regards,

Mnago

**Comment by vdemichev** [comment]
Please use DIA-NN 1.8.

**Comment by vdemichev** [comment]
But yes, --no-norm has the same effect as disabling normalisation in the GUI.
