### ISSUE TITLE
 library free search for  DIA phosphopeptide

### ISSUE THREAD

**Issue by miaohaofei** [vdemichev/DiaNN#175]
Dear Vadim,

I would like to do a phosphopeptide DIA library free search for thermo DIA data, I wonder if newest DIA-NN version 1.8.0 support it? If yes, how to set up the parameters? Thank you!

Miao

**Comment by vdemichev** [comment]
Hi Miao,

Yes, phosphoproteomics if fully supported. All you need to do is select the "Phospho" checkbox in the 'Precursor ion generation' panel.

Best,
Vadim

**Comment by miaohaofei** [comment]
thanks a lot ,  I have another question : the speed for the search of phosphopeptide by DIA-NN is very slow, does it normal? Do you have any suggestion to solve this problem?

**Comment by vdemichev** [comment]
Please see "How to reduce memory usage/speed up DIA-NN when analysing in library-free mode?" section here https://github.com/vdemichev/DiaNN#frequently-asked-questions
