### ISSUE TITLE
small curiosity

### ISSUE THREAD

**Issue by giorgiolivi** [vdemichev/DiaNN#189]
Hi Vadim,
Thank you for develop DIA-NN!!

I was wondering If I could retrive few protein features on the protein.group table.

For example I am looking for:
Unique Protein (number)
Sequence Coverage (%)
Mol. weight [kDa]
Protein Score (0 to 1)
Contaminant (+)

Thanks in advance.

I am watching Brett's video https://video.ucdavis.edu/playlist/dedicated/0_4jkc4swu/0_q62bphba
and we can replicate it with our data using DIA-NN on our Bruker machines.

Best,
Giorgio

**Comment by vdemichev** [comment]
Hi Giorgio,

Number of unique gene names: unique(df$Genes[df$Protein.Q.Value <= 0.01 & df$Proteotypic == 1])
Sequence coverage & molecular weight & whether it is a contaminant: this is not recorded, but this kind of info will be implemented in the future. Not sure what a protein score is.

Best,
Vadim

**Comment by giorgiolivi** [comment]
Perfect Vadim,
Thanks a lot!
Giorgio
