### ISSUE TITLE
Demultiplexing Overlapping Windows

### ISSUE THREAD

**Issue by singjc** [vdemichev/DiaNN#190]
Hi Vadim,

Great easy to use software!!

I was wondering if DIA-NN does any demultiplexing of the data internally? For example for QExactive Plus DIA data that has overlapping windows.

1. If using the raw thermo vendor files, does DIA-NN handle the demultiplexing?

2. If using msconvert to centroid and convert the vendor data to mzML (using the suggested parameters in the manual), does DIA-NN handle the demultiplexing?

3. If using msconvert to demultiplex, centroid and convert the data to mzML, would this still work as expected in DIA-NN?

Best,

Justin

**Comment by vdemichev** [comment]
Hi Justin,

DIA-NN fully supports overlapping windows, and it uses an algorithm which does not require demultiplexing. So it's recommended to analyse the data with DIA-NN directly, without any pre-processing.

Best,
Vadim

**Comment by singjc** [comment]
Hi Vadim,

Thank you for the info, that's great to know!

Best,

Justin
