### ISSUE TITLE
Cmd-line snakemake?

### ISSUE THREAD

**Issue by CptChiler** [vdemichev/DiaNN#2]
Hello,

is it possible to implement DiaNN in a snakemake workflow if not is it planned ?

cheers

Chris

**Comment by vdemichev** [comment]
> Hello,
> 
> is it possible to implement DiaNN in a snakemake workflow if not is it planned ?
> 
> cheers
> 
> Chris

Hi Chris,

I have just briefly read about snakemake, looks like DIA-NN should be fully compatible with snakemake workflows.

Best wishes,

Vadim
