### ISSUE TITLE
SpectraST  libraries

### ISSUE THREAD

**Issue by wabash2011** [vdemichev/DiaNN#20]
Hi, I noticed that DIA-NN 1.7.8 provides support for NIST .msp and SpectraST .sptxt libraries. But I was never able to sadd the libraries in the format .SPLIB file (generated by FragPipe-MSFragger)  in DIA 1.7.8 or 1.7.7, with or without your suggestion (addition of “"--library-headers *,*,*,*,*,*,Protein ID,Entry Name” to the Additional options text box). Always the warning: WARNING: cannot find column  ModifiedPeptide LabeledSequence FullUniModPeptideName "FullUniModPeptideName" modification_sequence. Any other suggestions? Please.

**Comment by vdemichev** [comment]
Hi, wabash2011. Currently I don't recommend using NIST/SpectraST libraries unless there's just no way to convert them. For example, when using these libraries DIA-NN will not use retention time information, this leading to lower identification numbers. Proper support for these libraries will be added soon though. However, FragPipe does produce a library in the OpenSWATH format (I think the default name is sth like "con_lib.tsv"), which is fully compatible with DIA-NN. If you'd still like to use the .splib file, please try renaming the extension to .sptxt. When analysing, please also add a FASTA database and click "Reannotate".

**Comment by wabash2011** [comment]
Thanks for the clarification. I did use the file (con_lib.tsv), and it worked in DIA-NN. I had thought that .SPLIB file was better since its file size is about double the size of the .tsv file. Thanks for pointing out the differences!
