### ISSUE TITLE
How protein quantification results from Spectronaut were generated in DIA-NN paper?

### ISSUE THREAD

**Issue by jinaanna** [vdemichev/DiaNN#206]
Hi, Vadim

Sorry t bother you again, but I didn't figure out one question and I would like to consult you again. How do you compare the protein quantification precision using LFQbench with the peptide quantification results in Spectronaut?  Does LFQbench support the extraction of protein quantification results from peptide results ? Could you please give me some guidance?

Jina

**Comment by vdemichev** [comment]
Can see if our scripts uploaded for the dia-PASEF preprint are suitable?

**Comment by jinaanna** [comment]
OK. Thank you! I'll try it!


| |
jina
|
|
***@***.***
|
签名由网易邮箱大师定制
On 10/7/2021 15:38，Vadim ***@***.***> wrote：

Can see if our scripts uploaded for the dia-PASEF preprint are suitable?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
