### ISSUE TITLE
Strange string 'unknown' in frag.info column of main report 

### ISSUE THREAD

**Issue by MarcIsak** [vdemichev/DiaNN#207]
Hi Vadim, 

I generated some spectral libraries in Fragpipe, and used them to analyze some DIA files in DIA-NN v.1.8. When I looked into the main report and the column **Frag.Info**, I saw the string '-unknown" which I have never seen before. An example from one row in the main report is:

[1] "y8-unknown^1/630.3317871;b5-unknown^1/398.2033997;b4-unknown^1/327.1662903;b3-unknown^1/256.1291809;y10-unknown^1/772.4060059;b6-unknown^1/469.2405396;y9-unknown^1/701.3688965;y11-unknown^1/843.4431152;y6-unknown^1/488.2575684;b7-unknown^1/540.2776489;y7-unknown^1/559.2946777;y12-unknown^1/914.4802856;"

I just wonder what '-unknown' in this case means? Can I simply remove this string and everything will be alright? I have never experienced this when I have generated libraries in DIA-NN or in other ways.

Best,

Marc

**Comment by vdemichev** [comment]
Hi Marc,

This refers to the neutral loss. Apparently, the one in the library is not recognsied by DIA-NN. This should not affect performance in any way, unless you are generating a spectral library from DIA data while using Smart or Full profiling library generation mode.

Best,
Vadim
