### ISSUE TITLE
Use library-free search, how to obtain retention time in library 

### ISSUE THREAD

**Issue by Allen188** [vdemichev/DiaNN#21]
I  use library-free search DIA(version 1.7.3), generated a  spectral library, but there is no information about the retention time. How to obtain retention time in library

**Comment by vdemichev** [comment]
Hi Allen188,

DIA-NN versions until 1.7.4 had a bug which manifested as retention times not being saved to the resulting spectral library when library-free mode was used without a training library (not recommended unless looking for PTMs). Please let me know if using the latest DIA-NN version solves the problem: RTs will be in the Tr_recalibrated column.

The latest DIA-NN versions also use deep learning for high quality spectra/RTs prediction. This dramatically improves identification numbers in the library-free mode.
