### ISSUE TITLE
speed up with .quant files

### ISSUE THREAD

**Issue by DanaHein** [vdemichev/DiaNN#220]
Hey Vadim!

We want to speed up the analysis and preprocess the raw and diaPASEF files with our default settings. The resulting .quant files we then want to use for faster analysis. To compare the runtime and the results we did the following:
1. independent DIA-NN runs for files A, B, C and D.
2. a DIA-NN run of A,B,C and D with the quant files (--use-quant)
3. one DIA-NN run of A,B,C and D without quant files

When comparing the results of steps 2 and 3, we noticed that more peptides were identified without the .quant files than with the .quant files.

Is this normal? And if so, can you explain it to us?

Thanks in advance!

Best, 
Dana

[without_quantfiles.log.txt](https://github.com/vdemichev/DiaNN/files/7390356/without_quantfiles.log.txt)
[with_quantfiles.txt](https://github.com/vdemichev/DiaNN/files/7390359/with_quantfiles.txt)

**Comment by cissarow** [comment]
Hi everyone

I am running DIA-NN in the clusterm but I stopped it to increase the cores. Now I want to start running from where it stopped, but I am not sure how to do that. Can someone help if there is a command  that can do the job so that I don't have to start running from scratch? Thanks

**Comment by vdemichev** [comment]
Please use --use-quant
