### ISSUE TITLE
acrylamide methylation for library free?

### ISSUE THREAD

**Issue by PatrickvanZalm** [vdemichev/DiaNN#226]
Hi Vadim, 

My colleague (who doesnt have a Github account) is trying to use DIA-NN for library free protein identification & quantification on timsTOF files. 

She used acrylamide for methylation, but she states propionamide is not an option in the software.

Could we add this manually? Or which would be the best parameters for this search?

Best,
Patrick

**Comment by vdemichev** [comment]
Hi Patrick,

This is solvable, please see https://github.com/vdemichev/DiaNN#library-free-search and also the --strip-unknown-mods command.

Best,
Vadim
