### ISSUE TITLE
Reading .dia files?

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#230]
Hi,

Would you consider releasing the data format for .dia files? 
We would like to see if it's possible for us to use .dia files for other applications, so we don't have to convert raw files into other formats and reduce the data storage.

**Comment by vdemichev** [comment]
Maybe some time in the future... What applications do you have in mind?

**Comment by cctsou** [comment]
All our DIA data have been converted to .dia format and repetitively analyzed by DIA-NN with different spectral libraries. For the IDs we would like to do some visualization on the spectral data, such as peak group XICs. Currently, we are using mzXML format but would be great that if we can do that directly from .dia files so we can save some storage, and presumably the data extraction would be faster than dealing with .mzXML format.

**Comment by vdemichev** [comment]
You can use --vis command in DIA-NN. But yes, it has its limitations.
