### ISSUE TITLE
relaxed-prot-inf option warning in GUI v1.8

### ISSUE THREAD

**Issue by edunivers** [vdemichev/DiaNN#231]
In the GUI "Additional Options" the --relaxed-prot-inf seems to be not recognized in v1.8. It says: "WARNING: unrecognised option [--relaxed-prot-inf]". Is this expected? How should we indicate this parameter in the GUI?

**Comment by vdemichev** [comment]
Works for me... Can you please share a screenshot where it prints this?

**Comment by edunivers** [comment]
My apologies. It doesn't work in 1.7.x but it is fixed and working very well in 1.8.
