### ISSUE TITLE
Are fragment ions normalised? 

### ISSUE THREAD

**Issue by MarcIsak** [vdemichev/DiaNN#235]
Hi, 

I tested MaxLFQ with the R package iq today, and I used the column "Fragment.Quant.Corrected" in the DIA-NN report as the input quantitative column. I just wonder, are these fragment ion intensities normalised? I know that the column Precursor.Normalised reports normalised intensities at least. 

Best,

Marc

**Comment by vdemichev** [comment]
No, these quantities are not normalised.

**Comment by vdemichev** [comment]
Hi Marc,

"Fragment.Quant.Corrected" are not normalised.

Best,
Vadim

**Comment by MarcIsak** [comment]
Thanks Vadim! Much appreciated!

Best,

Marc
