### ISSUE TITLE
No-Digestion Library Free

### ISSUE THREAD

**Issue by PatrickvanZalm** [vdemichev/DiaNN#237]
Hi Vadim,

I'm trying to use the library free method that DIA-NN offers. Based on a post of your [earlier post](https://github.com/vdemichev/DiaNN/issues/150) I tried to create a library without any type of digestion by leaving the --cut flag empty.

To my surprise, it only  contains 291 proteins.

If I run the same code but with --cut K*,R* it does import my 20k+ proteins in the FASTA.

Am I missing something?

Ive attached the code I am using currently.

`.\DiaNN.exe --threads 32 --verbose 1 --out "D:\Patrick\UC_IR\DIA_NN\results.tsv" --qvalue 0.01 --matrices  --out-lib "D:\Patrick\UC_IR\BuildLibrary\results2.tsv" --gen-spec-lib --predictor --fasta "D:\Patrick\UC_IR\BuildLibrary\UP000005640_9606_SARS_COV_2_BJOERN.fasta" --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --double-search --reanalyse --smart-profiling --peak-center --no-ifs-removal `

Best regards,
Patrick

**Comment by vdemichev** [comment]
Hi Patrick,

No digest  = whole proteins treated as peptides. The standard peptide length range is 7 - 30. Are there 291 proteins with length <= 30? I guess this would explain this.

Best,
Vadim

**Comment by PatrickvanZalm** [comment]
Thanks for the (very) prompt reply!!

Well, that makes a lot of sense. I would to make a peptidomics type of library. I guess to set that up I would have to do a --cut G*,A*,V*,L*,I*,D*,E*,N*,Q*,P*,F*,W*,K*,C*,M*,Y*,R*,H*,S*,T* ?

**Comment by vdemichev** [comment]
You mean non-specific digest? --cut *,*
But I don't think it's gonna work well with DIA at all... Huge search space, huge memory requirements, probably will crash any reasonable PC... If you'd like just semi-tryptic, this is supported by FragPipe 17, which now features a DIA version of MSFragger and an integrated DIA-NN for targeted extraction.

**Comment by PatrickvanZalm** [comment]
Thats the one I meant yes.

I too am afraid for the issues you raise.. Computational power isnt the issue though so I guess ill just give it a shot, and see what happens.

**Comment by PatrickvanZalm** [comment]
To my surprise, it still seems to not fully take all the proteins (1534 out of 20k+). With --cut K*,R* it does take all.

I did remove the "--missing-cleavages 1", assuming it wouldnt matter when doing non-specific digest. Could that potentially have an effect?

`DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 14:55:31
Current date and time: Fri Nov 12 16:34:40 2021
CPU: GenuineIntel Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
SIMD instructions: AVX AVX2 AVX512CD AVX512F FMA SSE4.1 SSE4.2 
Logical CPU cores: 32
C:\DIA-NN\1.8\DiaNN.exe --lib D:\Patrick\UC_IRvine\ONLY_URS\library.tsv --threads 32 --verbose 1 --out D:\Patrick\UC_IRvine\DIA_NN_Test3_ONLYURS\results.tsv --qvalue 0.01 --matrices --out-lib D:\Patrick\UC_IRvine\BuildLibraryPeptidomics\results2.tsv --gen-spec-lib --predictor --fasta B:\fragpipe17\FASTA\2020-09-17-decoys-reviewed-isoforms-contam-UP000005640.fas --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut *,* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --double-search --reanalyse --smart-profiling --peak-center --no-ifs-removal 

Thread number set to 32
Output will be filtered at 0.01 FDR
Precursor/protein x samples expression level matrices will be saved along with the main report
A spectral library will be generated
Deep learning will be used to generate a new in silico spectral library from peptides provided
Library-free search enabled
Min fragment m/z set to 200
Max fragment m/z set to 1800
N-terminal methionine excision enabled
Maximum number of missed cleavages set to 1
Min peptide length set to 7
Max peptide length set to 30
Min precursor m/z set to 300
Max precursor m/z set to 1800
Min precursor charge set to 1
Max precursor charge set to 4
Neural networks will be used for peak selection
A spectral library will be created from the DIA runs and used to reanalyse them; .quant files will only be saved to disk during the first step
When generating a spectral library, in silico predicted spectra will be retained if deemed more reliable than experimental ones
Fixed-width center of each elution peak will be used for quantification
Interference removal from fragment elution curves disabled
WARNING: MBR turned off, two or more raw files are required

0 files will be processed
[0:00] Loading FASTA B:\fragpipe17\FASTA\2020-09-17-decoys-reviewed-isoforms-contam-UP000005640.fas
[0:53] Loading spectral library D:\Patrick\UC_IRvine\ONLY_URS\library.tsv
[0:56] Spectral library loaded: 1534 protein isoforms, 1534 protein groups and 39962 precursors in 32704 elution groups.
WARNING: the option to combine a spectral library with a FASTA digest is experimental. Forcing <= 1 NN pass
[0:56] Processing FASTA
[0:56] Assembling elution groups
[0:57] Finding proteotypic peptides (assuming that the list of UniProt ids provided for each peptide is complete)
[0:57] 40357 precursors generated
[0:57] Gene names missing for some isoforms
[0:57] Library contains 1589 proteins, and 1589 genes
[0:57] [0:57] [1:06] [1:09] [1:09] [1:09] Saving the library to D:\Patrick\UC_IRvine\BuildLibraryPeptidomics\results2.predicted.speclib
[1:09] Initialising library

`

**Comment by vdemichev** [comment]
"--cut " in the above disables digest. So makes sense.
Please don't combine a library with FASTA digest, see the warning DIA-NN prints.

**Comment by PatrickvanZalm** [comment]
--cut *,* gives the same. Perhaps it just cuts everywhere until there's only 1 aminoacid long peptides (which would not be included due to the --min-pep-len flag)? Except peptides where where lysine/arginine meet proline for example.

Thanks, Ill turn of the combine library.

**Comment by vdemichev** [comment]
Sorry, I am confused, what's the ultimate purpose of modifying the --cut setting?

**Comment by PatrickvanZalm** [comment]
Im trying to do a library-free peptidomics analysis using DIA-NN. For exampe, when working with DDA data I would use fragpipe and use the non-specific parameters, limiting peptide lengths between 7 and 65.

**Comment by vdemichev** [comment]
So some peptides, but you don't know which? I am really not sure if DIA in general is a good idea for this. But can try FragPipe 17, which has the DIA version of MSFragger & integrated DIA-NN for quant.

**Comment by PatrickvanZalm** [comment]
Oh I fully agree with you it might not be the best idea. Nontheless Id like to give it a shot.

I recently did download Fragpipe17 and saw DIA-NN was included. So if I am correct; I can use database specific settings in there that will push it to DIA-NN for library-free generation?

**Comment by vdemichev** [comment]
Well, maybe it will work. Never tried non-specific digests myself

**Comment by vdemichev** [comment]
Library-free search will be done by MSFragger-DIA. It will then generate a library out of DIA data which will be used DIA-NN for a second-pass search & quantification.

**Comment by PatrickvanZalm** [comment]
Ok! Ill play around with it.

Thanks a ton Vadim!!

**Comment by L4ft2di3** [comment]
Dear Patrick,
would you be willing to share some experiences with me regarding the use of fragpipe and DIA-NN for non-specific search?
How did it go and any obstactles which are handy to know about?

Cheers
Thorben

**Comment by PatrickvanZalm** [comment]
Hi Thorben,

I dont check Github everyday. Feel free to reach out to me over email: patrick.vanzalm@childrens.harvard.edu
