### ISSUE TITLE
merging of spectral libraries)

### ISSUE THREAD

**Issue by msmedus** [vdemichev/DiaNN#26]
Dear Vadim,

Is there any way to merge different spectral libraries generated by DIA-NN within DIA-NN?
Thanks for your response!
Martin

**Comment by vdemichev** [comment]
Hi Martin,

Unfortunately not. However any libraries saved by DIA-NN can be simply merged together in R/Python/Excel (just make sure to filter out duplicate precursors).

Best wishes,
Vadim

**Comment by msmedus** [comment]
Thankd Vadim!
Maybe worth implementing in a future version of DIA-NN :-)
cheers!
