### ISSUE TITLE
DiaNN does not see MS2 spectra in mzML from WIFF2

### ISSUE THREAD

**Issue by chambm** [vdemichev/DiaNN#261]
https://github.com/ProteoWizard/pwiz/blob/master/pwiz/data/vendor_readers/ABI/Reader_ABI_Test.data/swath.api-sample-centroid.mzML?raw=true

```
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 14:55:31

...

[43:55] File #1/1
[43:55] Loading run C:\pwiz.git\pwiz\pwiz\data\vendor_readers\ABI\Reader_ABI_Test.data\swath.api-sample-centroid.mzML
No MS2 spectra: aborting
ERROR: cannot load the file, skipping
```

The first cycle from the file:
<HTML>
<BODY>
<TABLE><Tr><Th>Sample</Th><Th>Period</Th><Th>Cycle</Th><Th>Experiment</Th><Th>Spectrum type</Th><Th>MS level</Th><Th>Data Points</th><Th>Scan Time (min)</Th><Th>Isolation window</Th></Tr><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>1</TD><TD>MS1 spectrum</TD><TD>1</TD><TD>765</TD><TD>0.004183333333</TD><TD>n/a</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>2</TD><TD>MSn spectrum</TD><TD>2</TD><TD>4450</TD><TD>0.00635</TD><TD>[600-625]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>3</TD><TD>MSn spectrum</TD><TD>2</TD><TD>1507</TD><TD>0.008066666667</TD><TD>[624-650]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>4</TD><TD>MSn spectrum</TD><TD>2</TD><TD>557</TD><TD>0.0098</TD><TD>[649-675]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>5</TD><TD>MSn spectrum</TD><TD>2</TD><TD>1057</TD><TD>0.011516666667</TD><TD>[674-700]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>6</TD><TD>MSn spectrum</TD><TD>2</TD><TD>597</TD><TD>0.01325</TD><TD>[699-725]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>7</TD><TD>MSn spectrum</TD><TD>2</TD><TD>1323</TD><TD>0.014966666667</TD><TD>[724-750]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>8</TD><TD>MSn spectrum</TD><TD>2</TD><TD>726</TD><TD>0.016683333333</TD><TD>[749-775]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>9</TD><TD>MSn spectrum</TD><TD>2</TD><TD>402</TD><TD>0.018416666667</TD><TD>[774-800]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>10</TD><TD>MSn spectrum</TD><TD>2</TD><TD>357</TD><TD>0.020133333333</TD><TD>[799-825]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>11</TD><TD>MSn spectrum</TD><TD>2</TD><TD>7055</TD><TD>0.021866666667</TD><TD>[824-850]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>12</TD><TD>MSn spectrum</TD><TD>2</TD><TD>761</TD><TD>0.023583333333</TD><TD>[849-875]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>13</TD><TD>MSn spectrum</TD><TD>2</TD><TD>337</TD><TD>0.025316666667</TD><TD>[874-900]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>1</TD><TD>14</TD><TD>MSn spectrum</TD><TD>2</TD><TD>390</TD><TD>0.027033333333</TD><TD>[899-925]</TD></TR><TR><TD>1</TD><TD>1</TD><TD>2</TD><TD>1</TD><TD>MS1 spectrum</TD><TD>1</TD><TD>1677</TD><TD>0.031683333333</TD><TD>n/a</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by vdemichev** [comment]
For reading .mzML DIA-NN uses https://github.com/mhoopmann/mstoolkit. Apparently, some incompatibility? Was it converted using the recommended MSConvert settings? Also, does DIA-NN read the wiff2 directly?

**Comment by chambm** [comment]
Ah, it was because the file isn't indexed. Mstoolkit apparently doesn't support that. But I'm not seeing the error message I would expect: https://github.com/mhoopmann/mstoolkit/blob/4cb705d1e3beb2d5636043bd920a37f0ab08995f/src/mzParser/saxmzmlhandler.cpp#L604

Which would have made the problem immediately apparent.

**Comment by chambm** [comment]
Oh, and no, none of the WIFF1 APIs can read WIFF2, and vice versa (so far). I'm hopefully they add WIFF1 support in the WIFF2 API.

**Comment by vdemichev** [comment]
Our 7600 produces both .wiff and .wiff2 files. So we just use .wiff with DIA-NN. What kind of instrument produces .wiff2 only?

**Comment by chambm** [comment]
X500 I think. IIRC the WIFF2 API they gave us ONLY supports the X500 right now.
