### ISSUE TITLE
Mapping between speclib and main report

### ISSUE THREAD

**Issue by chambm** [vdemichev/DiaNN#262]
On a Skyline thread you said:

> the main report does not contain spectra. But it can be used to supplement the information stored in the .tsv library: just need to match the pairs [file name - precursor name] between the report and the library (easy to do in R).

I've looked at doing this but I'm not sure it's possible if the speclib and report contain results from multiple input files. Since I don't have filename in the speclib (not the TSV), I can't do what you suggest. Perhaps you meant using the TSV, but I'm trying to avoid having to touch the TSV since it's huge and highly redundant. Any way to do it with the speclib?

**Comment by vdemichev** [comment]
Hi Matt, OK, I see the problem. Can you please remind me what's the ultimate purpose of doing this matching in the first place?

**Comment by chambm** [comment]
Getting RT.Start and RT.End was the original goal, but since then I've realized I'm actually getting iRT from speclib instead of the spectrum's actual RT (which isn't in the speclib unless the user does --out-measured-rt), and the iIM isn't the spectrum's actual IM (but it's much closer than the iRT is to the real RT).

**Comment by vdemichev** [comment]
Oh, yes. But why RT.Start and RT.End are needed in the speclib? THey are save din the report, and naturally, they are run-specific.

**Comment by chambm** [comment]
IIRC, Skyline uses them to bracket the RT range to integrate peak area over. Quoting Brendan from the Skyline support thread:

> One thing we have done with other tools like EncyclopeDIA and OpenSWATH is to use the actual integration boundaries they came up with and not just the detection RT (presumably the apex or central retention time of the integrated peak). If there were a way to get these from DIA-NN, we could do the same for it. Skyline now has a checkbox in its library setup form for whether integration boundaries in the library should be applied to the data in Skyline

But you raise a good point about them being run-specific since the library only contains a single spectrum per precursor. @brendanx67 , how are start/end RT used from the library if they are run-specific?

**Comment by chambm** [comment]
OK I was wrong; I had forgotten that BiblioSpec's library keeps track of retention times, boundaries, and scores for all input files. But it only keeps the best scoring spectrum's peaks and drops the others.

But I don't need them in the speclib if I can map the speclib entries to the report so I can get that RT info for each file.

**Comment by chambm** [comment]
I was able to fix this without considering which file the speclib peaks came from. I use the speclib for peaks, keyed by Precursor.Id. I get the Run, Precursor.Id, QValue, RT, RTStart, RTStop, and IM values from the report TSV. 

rying to find the report TSV automatically in the same directory as the speclib file turned out to be the hardest part (considering there might be other TSV files or even other reports there, and that users can change the report and speclib output filenames).
