### ISSUE TITLE
Will adding `--no-quant-files` flag change the result?

### ISSUE THREAD

**Issue by fcyu** [vdemichev/DiaNN#265]
To prevent DIA-NN from generating `*.quant` file, I would like to use the `--no-quant-files` flags. Would there be any difference in terms of results, speed, and memory usage?

Thanks,

Fengchao

**Comment by vdemichev** [comment]
Hi Fengchao,

There should be an insignificant increase in memory used, but other than that no difference.

Best,
Vadim

**Comment by fcyu** [comment]
Hi Vadim,

Thank you very much for your prompt reply.

Best,

Fengchao
