### ISSUE TITLE
Installatiion of Linux version problem

### ISSUE THREAD

**Issue by vcoyne1** [vdemichev/DiaNN#267]
Hi Vadim,

I downloaded the Linux version (.deb) and installed it in Linux Mint 20.2 Cinnamon. The package was installed in the appropriate directory. However, I am unable to run the program. 

The contents of the directory are:
diann-1.8
libc10.so
libgomp-75eea7e8.so.1
libtimsdata.so
libtorch.so
libtorch_cpu.so
unimod.obo

Glibc 2.31 is installed.

Please could you assist me with this - I am certain that I'm missing something basic, but have no ide what.

Thanks in advance,

### Discussed in https://github.com/vdemichev/DiaNN/discussions/257

<div type='discussions-op-text'>

<sup>Originally posted by **cjhjhj** December  1, 2021</sup>
Hello Vadim,

I have downloaded the linux version of version 1.8 (rpm file) and installed it. However, when I executed it, it was shown as version 1.7.12 and looked like not supporting Bruker's .d directory (i.e., timsTOF data). Is there any way to run DIA-NN for timsTOF diaPASEF data in Linux?

Thank you.</div>

**Comment by vdemichev** [comment]
"However, I am unable to run the program" - how does this manifest? What exactly do you type and see in the terminal?

**Comment by vcoyne1** [comment]
I download the .deb package.

In the terminal, I type sudo dpkg -i diann_1.8.deb

This installs the package in the usr/diann/1.8 directory.

From here, I go to usr/diann/1.8 and click on diann-1.8 and get message "Unknown file type" File has no known programs associated with it.

So the issue is, how does one run the installed program?

**Comment by vdemichev** [comment]
In Linux one cannot launch binaries by clicking on them. Need to launch them from the command line. This is an unfortunate (and I personally think ridiculous) property of Linux.

**Comment by vcoyne1** [comment]
But what command do I use to launch diann_1.8 from the command line in the terminal?

**Comment by vdemichev** [comment]
try "./diann_1.8"?

**Comment by vdemichev** [comment]
Can you please cd to  /usr/diann/1.8, type 'ls', try to launch the DIA-NN binary, copy all the contents of the terminal (from all three steps) and paste them here?

**Comment by vcoyne1** [comment]
vernon@vernon-K52JT:/$ cd /usr/diann/1.8
vernon@vernon-K52JT:/usr/diann/1.8$ ls
diann-1.8  libgomp-75eea7e8.so.1  libtorch_cpu.so  unimod.obo
libc10.so  libtimsdata.so         libtorch.so
vernon@vernon-K52JT:/usr/diann/1.8$ diann-1.8
diann-1.8: command not found
vernon@vernon-K52JT:/usr/diann/1.8$ ./diann-1.8
DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Tue Dec 14 16:33:01 2021
Logical CPU cores: 8

0 files will be processed
vernon@vernon-K52JT:/usr/diann/1.8$

**Comment by vcoyne1** [comment]
It seems to me that there is no binary for launching the program. I tried typing diann-1.8 as well as ./diann-1.8, neither of which was successful

**Comment by vdemichev** [comment]
But you just posted how you launched it succesfully. The native binary is a command line tool only, to use the GUI under Linux need to use Wine

**Comment by vcoyne1** [comment]
I think the confusion is, as I understand it, is that the .exe version (windows) can be run using Wine on Linux. However, the .deb package can be run as a straight Linus application.

**Comment by vcoyne1** [comment]
Clearly not the case
