### ISSUE TITLE
DIA-NN on Linux using Wine 

### ISSUE THREAD

**Issue by vcoyne1** [vdemichev/DiaNN#268]
I have not been able to run the Linus version of Dia-NN and so have tried running on Linux using Wine. Unfortunately the software exits as soon as the run is implemented. A typical log output:

diann.exe --f "C:\users\vernon\My Documents\CPGR_MariHealth_proteomics_data\1451Pilot\FASP\1451_18_Temp12hr1.raw
" --lib "" --threads 4 --verbose 1 --out "C:\DIA-NN\1.8\report.tsv" --qvalue 0.01 --matrices  --out-lib "C:\DIA-NN\1.8\report-lib.tsv" --gen-spec-lib --predictor --fasta "C:\users\vernon\My Documents\Databases\Mollusca_April2018.fasta" --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --reanalyse --smart-profiling 

DIA-NN exited
DIA-NN-plotter.exe "C:\DIA-NN\1.8\report.stats.tsv" "C:\DIA-NN\1.8\report.tsv" "C:\DIA-NN\1.8\report.pdf"
PDF report will be generated in the background

Any assistance with this will be greatly appreciated.

Thanks in advance,
Vernon

**Comment by vdemichev** [comment]
Thermo MSFileReader not installed - needs to be installed under Wine.

**Comment by vdemichev** [comment]
Hi Vernon,

Thermo MSFileReader https://thermo.flexnetoperations.com/control/thmo/login?nextURL=%2Fcontrol%2Fthmo%2Fdownload%3Felement%3D6306677 not installed - needs to be installed under Wine. 

Best,
Vadim
