### ISSUE TITLE
WARNING: incorrectly recorded isolation window margins for .d DIA-PASEF files

### ISSUE THREAD

**Issue by anfoss** [vdemichev/DiaNN#269]
I have approx 60 DIA-PASEF file ran in a single batch. For 10ish or so DIA-NN cannot extract anything from the library and throws a warning for incorrectly recorded isolation window margins. Is there a fix? The TimsTOF was calibrated at the beginning of the batch (both TIMS and TOF) and the files that fail are in between files that work.

**Comment by vdemichev** [comment]
Hi Andrea,

Can you maybe share one of the runs (the smallest one) for which there's a problem - please send a link via email, and I will see if I can troubleshoot?

Best,
Vadim
