### ISSUE TITLE
Windows vs Linux unclear

### ISSUE THREAD

**Issue by vcoyne1** [vdemichev/DiaNN#271]
The confusion is that the Github page implies that the .exe version (windows) can also be run using Wine on Linux. However, the .deb package should run as a straight Linus application, but in fact it does not. There should be no need to run this using Wine. Even if this is command line driven, it cannot be launched as such in the Linux terminal.

_Originally posted by @vcoyne1 in https://github.com/vdemichev/DiaNN/issues/267#issuecomment-993608339_

**Comment by vdemichev** [comment]
The .deb package once installed does run as a Linux command line application. It can be launched is such and the terminal output you posted is correct and expected.

**Comment by vcoyne1** [comment]
But how do I use it? It would be great if there was a "manual" that provided info on how to add the various commands/options required to set up an analysis.

**Comment by vdemichev** [comment]
Please see https://github.com/vdemichev/DiaNN#command-line-tool
