### ISSUE TITLE
Default to longest common prefix for output filepaths

### ISSUE THREAD

**Issue by chambm** [vdemichev/DiaNN#272]
Suppose I have a set of files like:
```
D:\test\DIA\collinsb_X1803_171-A.mzML
D:\test\DIA\collinsb_X1803_172-B.mzML
D:\test\DIA\collinsb_X1803_173-A.mzML
D:\test\DIA\collinsb_X1803_174-B.mzML
D:\test\DIA\collinsb_X1803_175-A.mzML
D:\test\DIA\collinsb_X1803_176-B.mzML
```
It would be nice if, after picking this set of input files when the file list is currently blank, DIA-NN would set the main output and output library text boxes to `D:\test\DIA\collinsb_X1803_17-report.tsv` and `D:\test\DIA\collinsb_X1803_17-lib.tsv`. Some tokenization could refine it further (e.g. split off the `_17` part because it's separated by `_` and `-`), but the longest common prefix would be a much more convenient starting point than the executable's directory.

**Comment by vdemichev** [comment]
Hi Matt, yes, this would be convenient in many cases, but the problem with setting this as default is that in many scenarios the raw data folder is write-protected.

**Comment by chambm** [comment]
In that case at least the prefix from the filenames would be there. Then only the path part would need to be replaced.
