### ISSUE TITLE
DIA-NN1.8 could not analyze FAIMS-DIA data.

### ISSUE THREAD

**Issue by Mnago** [vdemichev/DiaNN#275]
Hi Vadim,

FAIMS-DIA files could not be analyzed by DIA-NN1.8 even in spectral library-based or library-free strategy.  The log file is attached. I tried to split a FAIMS-DIA file into different files by CV voltage, and which could be go through by DIA-NN. But I have no idea how to combine the quantitation info from those files. The 
![image](https://user-images.githubusercontent.com/52949420/147853430-f7dd5914-7a67-4dca-a59c-ed67088d7a45.png)

**Comment by vdemichev** [comment]
Please install MSFileReader again - exactly the version by the link in the documentation.

**Comment by vdemichev** [comment]
Any update?

**Comment by Mnago** [comment]
Hi Vadim, 
I have gone through FAIMS-DIA analysis by DIA-NN 1.8 after I reinstalled proteowizard. Thanks.
