### ISSUE TITLE
ERROR: C:\diann\src\diann.cpp: 17316: Cannot load spectral library

### ISSUE THREAD

**Issue by lolaakinlaja** [vdemichev/DiaNN#278]
Can someone please explain to me why this error keeps popping up when I try to do DIA quant through frapipe? Maybe there's something simple I'm missing but I'm not sure. Thanks for any help I can get with this.

**Comment by vdemichev** [comment]
HI, I would suggest asking on the FragPipe github: https://github.com/Nesvilab/FragPipe, they usually respond very quickly. Please then also share the log with them.

Best,
Vadim
