### ISSUE TITLE
Installation on Linux - possible to provide binaries compatible with Centos7?

### ISSUE THREAD

**Issue by llniu** [vdemichev/DiaNN#279]
Hi Vadim, thank you for the software. I was trying to install it but found that the distributed binary packets (RPM) provided on the website for DIA-NN version 1.8 doesn't work on our system. Is it possible to provide binaries compatible with Centos7? Thanks a lot in advance. 

Best,
Lili

**Comment by vdemichev** [comment]
Hi Lili,

The Linux system must have glibc 2.27 or later (for example, Ubuntu 18.04 or CentOS 8 and later versions are fine). I guess CentOS 7 does not. Unfortunately, it's a technical restriciton related to C++ 17 support, cannot do anything about it really.

Best,
Vadim
