### ISSUE TITLE
How to understand the main output of DIA-NN?

### ISSUE THREAD

**Issue by Mnago** [vdemichev/DiaNN#280]
Hi Vadim,

I have three questions. 
1. From the closed issue, why use the values from Fragment.Quant.Raw instead of Precursor.Quantity for MS2 level quantitation? What is the difference between Precursor.Quantity and Fragment.Quant.Raw?  https://github.com/vdemichev/DiaNN/issues/262
2. How to get the cirt information such as peptide sequence from the DIA-NN output? I want to get the retention time-related information to evaluate the LC stability of different runs? Any recommendation?
3. How to understand the value of Total.Quantity and MS1.Signal and MS2.Signal from stats report?

**Comment by vdemichev** [comment]
1. Hi, Fragment.Quant.Raw are fragment quantities, not precursor. I don't recommend using them for anything, except maybe for some special purposes.
2. Stripped.Sequence column is the peptide sequence. Retention time - see RT and Predicted.iRT
3. Sum of quantities of precursors at 1% FDR, total MS1 and MS2 signals recorded in the mass spec run (sums of all peak intensities).

**Comment by Mnago** [comment]
1. I want to get the MS1 peak area and MS2 peak area of each peptide precursor. So Precursor.Quantity could be used  for MS1  and fragment.Quant.Raw could be used for MS2, right?
2. How to get peptide sequece of cirt used for retention time calibration?
3.  What is the differernce between MS1 quantity and MS1.Area?

**Comment by vdemichev** [comment]
1. MS1 - Ms1.Area, MS2 - Fragment.Quant.Raw
2. DIA-NN uses endogenous peptides, not cirt
3. Ms1.Area is the MS1 quantity

**Comment by Mnago** [comment]
Sorry, I mean the difference between precursor.quantity column and MS1.Area column from mainoutput?

**Comment by vdemichev** [comment]
Precursor.Quantity is MS2 based

**Comment by Mnago** [comment]
Thanks!
