### ISSUE TITLE
How to re-write the reports after error reporting?

### ISSUE THREAD

**Issue by chliu1992** [vdemichev/DiaNN#283]
Hi,
An error like this:
![image](https://user-images.githubusercontent.com/61834501/150059280-e1a4ad90-a427-4c41-8f95-083f47598637.png)

The database searching has finished,   Is there any other method to re-write the reports files?

**Comment by vdemichev** [comment]
Please select 'Use existing .quant files' and press 'Run', provided the settings in teh GUi are exactly the same.
