### ISSUE TITLE
How to get the actual retention time of peptide precursor from DIA-NN report?

### ISSUE THREAD

**Issue by Mnago** [vdemichev/DiaNN#288]
Hi Vadim,

I used Skyline to view the peptide precursors with high MS1.area identified by DIA-NN. The retention time of these precursors extracted by skyline was inconsistent with the result extracted by DIA-NN, and the skyline result was similar to that from the instrument company's own software.
How to get the actual retention time of peptide precursor from the DIA-NN report?

**Comment by vdemichev** [comment]
Hi, I would trust DIA-NN's identifications. I think Skyline uses a very simple algorithm for identifying putative peaks in its viewer, which is meant for dealing with peaks that are identified with high confidence and does not involve FDR estimation. So it's great if the peak is easily identifiable, but if not, need to correct Skyline's peak boundaries.

DIA-NN reports the retention time in the RT column of the main report.
