### ISSUE TITLE
Difference in nr of protein groups between manual filtering of report and pg.matrix

### ISSUE THREAD

**Issue by anfoss** [vdemichev/DiaNN#292]
I have a large plasma dataset and was looking at different ways to preprocess it at various levels to ultimately end up with a protein matrix file. When I filter the report using 0.01 precursor-level q-value, 0.005 precursor-level library q-value and 0.05 protein group-level q-value (copying what done here  https://www.cell.com/cell-systems/fulltext/S2405-4712(20)30197-6#secsectitle0075) the data shape goes from 1979177 to 1902585.
After this, the sample with the highest nr of protein groups has 646 (defined here as just taking the nr of unique proteins groups after removing NAN in the Genes.Quantity column). However, the same sample in the pg.matrix file has 694 protein.groups (extracted as non-NAN entries in the column) and in the pg.matrix file there is a sample with 717 proteins which only has 620 from the report filtering.

How come there are more protein.groups than the ones in the report for the sample sample?

**Comment by vdemichev** [comment]
Hi Andrea,

pg_matrix is obtained by default using global protein q-value filtering only. So if you get a different result from the main report, this is caused by different filtering applied. Please note that the old papers were produced with older DIA-NN versions, I would suggest to follow the recommendations in the DIA-NN documentation rather than the filtering used in papers.

Best,
Vadim

**Comment by anfoss** [comment]
Hi Vadim,

If I understand it correctly, then I am a bit puzzled by the following.


```
manual_filter = pd.read_csv('data/main_report.tsv', sep='\t')
manual_filter = df[df['Global.PG.Q.Value'] <= 0.01]
autom_filter = pd.read_csv('data/main_report.pg_matrix.tsv', sep='\t')

print(len(set(manual_filter['Protein.Groups])),len(set(autom_filter['Protein.Group']))
```


prints 605 and 837. Is there any additional filtering applied?

**Comment by vdemichev** [comment]
Main report generated at precursor FDR < 5%? MBR used? If with MBR, need to filter using Lib.PG.Q.Value instead of Global.PG.Q.Value. 

Vadim

**Comment by anfoss** [comment]
Ok now the numbers are consistent, thanks for the explanation!
