### ISSUE TITLE
Spectral library generation from pre-digested fasta.

### ISSUE THREAD

**Issue by masaver** [vdemichev/DiaNN#293]
Hi Vladim,

Thanks for developing  this software and for its detailed documentation! I have succesfully used DIA-NN to run some quantifications. However, I have the following question:

I wanted to generate a spectral library from a pre-digested fasta file, which looks something like this:
`
>sp|P62258
RIISSIEQKEENKGGEDKLKMIREY
>sp|P62258
KAASDIAMTELPPTHPIRLGLALNF
>sp|Q04917
RVISSIEQKTMADGNEKKLEKVKAY
>sp|P61981
RVISSIEQKTSADGNEKKIEMVRAY
>sp|P61981
SEAHEISKEHMQPTHPIRLGLALNY
>sp|P31947
RVLSSIEQKSNEEGSEEKGPEVREY`

When running dia-nn, I included the option `--fasta-search` to indicate that I want to generate the spectral library from the fasta file, and since it is pre-digested, I also included `--cut` without any protease specificities. However, when I run dia-nn, i get this message:
`0 files will be processed
[0:00] Loading FASTA /working_dir/Data_Task/uniprot_sprot_2021-07-01_HUMAN_Proteosome_digested_7aa_25aa.fasta
[0:03] Processing FASTA
[0:03] Assembling elution groups
[0:03] 0 precursors generated
[0:03] Library contains 0 proteins, and 0 genes
[0:03] Saving the library to /working_dir/Results/MHC_I_II_uniprot_predicted_library.predicted.speclib
[0:03] Initialising library

[0:03] Log saved to /working_dir/Results/MHC_I_II_uniprot_predicted_library.log.txt
Finished`.

If I specify a proteolytic activity via the --cut option, for example `--cut K*,R*`, a predicted spectral library is produced as expected.

In both cases ( with the exception of the `--cut` flag, the complete list of command line options I used is as follows:
`
/usr/diann/1.8/diann-1.8  --threads ${num_threads} --gen-spec-lib --strip-unknown-mods --fasta-search --cut --duplicate-proteins --fasta /working_dir/Data_Task/${FASTA_FILE_NAME} --temp /working_dir/Data_Task/ --out-lib /working_dir/Results/${OUTPUT_LIB_NAME} --out /working_dir/Results/${analysisname}cohort_report.tsv --use-quant --verbose 3 --reannotate --min-fr-mz 200 --max-fr-mz 1800 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --met-excision --unimod4 --var-mods 2 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --monitor-mod UniMod:1 --reanalyse --smart-profiling --predictor --matrices --qvalue 0.01`

Do you have an idea of what might be happening? 

Let me know if there any other details you might need to know.

Thanks a lot in advance !

Best,

-Mathias

**Comment by vdemichev** [comment]
Hi Mathias, 

I guess the problem is that DIA-NN expects each FASTA entry to start with '>'. Ideally the FASTA file should be formatted similar to UniProt entries.

Best,
Vadim

**Comment by masaver** [comment]
I'm sorry, but there must have been a parsing error when I created this post. The actual file looks like this:
![image](https://user-images.githubusercontent.com/25987663/152003340-58a04b4f-53b2-4c81-a28a-21f9ab80cfc0.png)

**Comment by masaver** [comment]
Taking the command you previously suggested, and since I was originally working on a ubuntu system, the command I tested was:
`/usr/diann/1.8/diann-1.8 --lib "" --threads 16 --verbose 3 --out /working_dir/Results/${analysisname}cohort_report.tsv --qvalue 0.01 --matrices --out-lib /working_dir/Results/${OUTPUT_LIB_NAME}.tsv --gen-spec-lib --predictor --fasta /working_dir/Data_Task/${FASTA_FILE_NAME} --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --var-mods 2 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --monitor-mod UniMod:1 --reanalyse --smart-profiling --cut --duplicate-proteins`
which showed the same behavior as before: no spectral library is generated. However, yesterday I tried the equivalent command, but now running DiaNN via the command prompt on my windows local machine, and was able to succesfully generate a ~3Gb spectral library. The exact command was:
`& 'C:\DIA-NN\1.8\DiaNN.exe --lib "" --threads 4 --verbose 3 --out C:\working_dir\Results\report.tsv --qvalue 0.01 --matrices --out-lib C:\working_dir\Data_Task\MHC_I_II_uniprot_predicted_library.tsv --gen-spec-lib --predictor --fasta C:\working_dir\Data_Task\uniprot_sprot_2021-07-01_HUMAN_Proteosome_digested_7aa_25aa.fasta --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --var-mods 2 --var-mod UniMod:35,15.994915,M --var-mod UniMod:1,42.010565,*n --monitor-mod UniMod:1 --reanalyse --smart-profiling --cut --duplicate-proteins'
`
Would you have an idea as to why the same command does not work in the ubuntu release ?

Furthermore, when I moved the the library I generated on my windows machine into my linux system, and tried to run a quantification of 3 files, I got the following message indicating that the library could not be read:
`DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Thu Feb  3 11:48:34 2022
Logical CPU cores: 32
Existing .quant files will be used
Thread number set to 30
Existing .quant files will be used
Library precursors will be reannotated using the FASTA database
WARNING: unrecognised option [--miss-cleavages 1 \]
Min fragment m/z set to 200
Max fragment m/z set to 1800
Min peptide length set to 7
Max peptide length set to 30
Min precursor m/z set to 300
Max precursor m/z set to 1800
Min precursor charge set to 1
Max precursor charge set to 4
N-terminal methionine excision enabled
Cysteine carbamidomethylation enabled as a fixed modification
Maximum number of variable modifications set to 2
Modification UniMod:35 with mass delta 15.9949 at M \ will be considered as variable
Modification UniMod:1 with mass delta 42.0106 at *n \ will be considered as variable
A spectral library will be created from the DIA runs and used to reanalyse them; .quant files will only be saved to disk during the first step
When generating a spectral library, in silico predicted spectra will be retained if deemed more reliable than experimental ones
Deep learning will be used to generate a new in silico spectral library from peptides provided
Precursor/protein x samples expression level matrices will be saved along with the main report
Output will be filtered at 0.01 FDR
DIA-NN will optimise the mass accuracy automatically using the first run in the experiment. This is useful primarily for quick initial analyses, when it is not yet known which mass accuracy setting works best for a particular acquisition scheme.
WARNING: no FASTA, cannot reannotate the library

3 files will be processed
[0:00] Loading spectral library /working_dir/Data_Task/MHC_I_II_uniprot_predicted_library.speclib
cannot read the file
ERROR: src/diann.cpp: 17316: Cannot load spectral library
`
Do you why this happens, and/or a workaround this ?

Thanks again for your help !

Best,

-Mathias

**Comment by vdemichev** [comment]
Hi Mathias,

'cannot read the file' means that file is not accessible to DIA-NN. Can happen if some file permissions are set in such a way as to prevent access. I would try to create a new folder and copy this file into that folder.

Best,
Vadim

**Comment by masaver** [comment]
Hi Vladim,

Yeah, I ended running `chmod 777` on the library I got from my windows machine, and then I was able to use it as expected on my linux server.

Still, I would like to politely suggest investigating why this library generation works with the Windows release but not with the linux release.

Thanks a lot for your help !

Best,
Mathias.
