### ISSUE TITLE
Merge columns intensities from sample fractionnation analyzed in DIA

### ISSUE THREAD

**Issue by KR-15** [vdemichev/DiaNN#299]
Hi,

In our lab we have analyzed some plasma and wanted to try plasma **HpH peptide fractionation** and analyzed the fractions in DIA in our tims-TOF pro intrument in order to make a large DIA library.

With this purpose in mind, I would like to first compare the results of this kind of strategy compared for instance to directly inject plasma in DIA to know if the gain is so much better or not. 

Therefore , I am wondering if there is a way to merge the column intensities into one column. I was thinking about implementing the same classic way to analyze fractionated samples with MaxQuant when we set the same _Experiment_ name for all fractions to get only one intensity column at the end and to do the same with DIA-NN.

Is there a way to do it ?

Thanks for your help.

KR

**Comment by vdemichev** [comment]
Hi KR,

I would suggest to do the merging using R or Python.

Best,
Vadim
