### ISSUE TITLE
Phosphorylation modification DIA

### ISSUE THREAD

**Issue by UKQIDA** [vdemichev/DiaNN#3]
Hi Vadim,

I wonder if DIA-NN support phosphorylation modification DIA data anlaysis. How should I use it if it is supported? For unsupported modifications, is there any way for me to add them as extra parameters to the command line?

We have compared the results between DIA-NN and Spectronaut on two datasets. The identification are well overlap in one set and almost without overlap in another set. Do you have any explanation on such discrepancy.

Regards,
Da

**Comment by vdemichev** [comment]
Hi Da,

Phosphorylation (as well as any other PTMs) is supported in spectral library-based mode without the need to manually specify any modifications. 

Could you please give some details about the nature of that dataset on which the IDs of DIA-NN and Spectronaut don't overlap? Maybe I can have a look at it?

Best wishes,

Vadim

**Comment by UKQIDA** [comment]
Hi Vadim,

Thanks for your quick response. How can I send you the results via email?

Regards,
Da

**Comment by vdemichev** [comment]
Hi Da,

Yes, let's move the conversation from github. Please email me vadim.demichev [at] gmail.com. 

Best wishes,
Vadim
