### ISSUE TITLE
questions about hardware configuration when runing DIN-NN

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#30]
Hi,
 Today I use my laptop to run the DIA data in DIN-NN(1.7.10).Unfortunately,when it went about 8 hours,the laptop crashed.I wonder if it's owing to my low setup in the haedware.Is it there any requirment  in the hardware configuration?
Thanks very much if you could reply to me.
Best wishes!
Clover

**Comment by vdemichev** [comment]
Hi Clover, 

Cannot really say anything concrete without further details. For spectral library-based searches DIA-NN typically uses little memory and should run fine on any modern laptop. It would typically spend less than a minute or several minutes at worst per run, so 8 hours would be really excessive. In library-free mode, of course, it's possible to choose settings which would increase memory consumption significantly and might cause the system to run out of memory.

If the error keeps occurring, please try to save the full DIA-NN log obtained when using the Log level = 3 setting and attach it to the message.

Best wishes,

Vadim

**Comment by Clovernana** [comment]
Hi Vadim，
I have been recently  using the DIA-NN to perform DIA analysis with my test data.And does DIN-NN support mutiple runs at the same time?For example，a data containing the experimental and control groups ,and can I search them at the same time?And the second question,if I have a data that containing 3 replicates,can I search them at the same time,and how the output files look like?Counld you please give me some guidlines? And the last question,DIA-NN supports both the library based and library free search method.Have you compare the effect of the two methods for the same DIA data? Which method is more recommanded?And if using the library free method,I use the FASTA file downloaded from Swiss Prot Human database(The experimental target in my experiment is human).And I just find that the time spending on the predicted spectra library is just so long ,and is it there better method?In other words,if everytime I use the same FASTA files,can I just predict once the spectra and for the later runs just use this already predicted libarary?And Give me some specific guidlines about it!Thanks so much!


Best Wishes!
Clover
| |
姜娜
|
|
16622080827@163.com
|
签名由网易邮箱大师定制
On 5/3/2020 20:51，Vadim Demichev<notifications@github.com> wrote：

Hi Clover,

Cannot really say anything concrete without further details. For spectral library-based searches DIA-NN typically uses little memory and should run fine on any modern laptop. It would typically spend less than a minute or several minutes at worst per run, so 8 hours would be really excessive. In library-free mode, of course, it's possible to choose settings which would increase memory consumption significantly and might cause the system to run out of memory.

If the error keeps occurring, please try to save the full DIA-NN log obtained when using the Log level = 3 setting and attach it to the message.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
Hi Clover,

- DIA-NN supports simultaneous analysis of arbitrary number of runs. It's indeed recommended to always analyse runs in one go, if you'd like to compare quantities between these. It's actually essential to do that unless you normalise between analyses yourself using R/Python.

- Please see the manual on the output format, DIA-NN can produce both lists of identifications (in one table for many runs) as well as precursor/protein x samples matrices.

- Very good project specific library > Very good large public library > library-free > mediocre public library.

- Ourselves we just use uniprot reference proteomes (uncompressed FASTA). Any FASTA in UniProt format is OK. For other formats recognition of protein names is not guaranteed.

- Yes, you are right, every time DIA-NN predicts spectra, it saves them in a file ending with .predicted.speclib (and writes the file name in the log). You can just reuse this as a spectral library for all further analyses, in order not to spend time on prediction again.

Please don't hesitate to contact me if there any other questions!

Best wishes,

Vadim
