### ISSUE TITLE
Can DIA-NN process BoxCar scans?

### ISSUE THREAD

**Issue by llniu** [vdemichev/DiaNN#301]
Hi Vadim, thanks for your continuous support. I acquired a dataset with the following settings within each DIA cycle: 1 full scan followed by two BoxCar scans followed by a number of DIA scans. Can DIA-NN process such spectra data? Thanks! It was Thermo instrument .raw. 
Best,
Lili

**Comment by vdemichev** [comment]
Hi Lili, as far as I know it does, but I don't know how effectively it benefits from BoxCar.

Best,
Vadim
