### ISSUE TITLE
Fasta Format

### ISSUE THREAD

**Issue by Maithy15** [vdemichev/DiaNN#302]
Hi,

Should the Fasta format be strictly UniProt? our fast currently looks like this

>Zm00001eb100900_P002
MRSRQMKRRSRCGVDVDSPTLPLSSSSAFAWSYTPLDPRTVLDTVSSPKTCTCVVVEGTA
AEEEQEEEAADGGDCDADDESEAFFSVKSFFTRSTSRAATVASSACMLTDPPPPTLRSPE
AWERFRDCEGWPFGLCRRPRPAVLPLPPLPSTPADSWKWRKSVGSLAASPAPAYRHKITT
AAPASSK

This will still be fine right?

**Comment by vdemichev** [comment]
FASTA header must start with >. Then all is gonna be fine, but of course not gene annotation, etc - just the sequence ID.
