### ISSUE TITLE
Generating Spectral library from input files

### ISSUE THREAD

**Issue by masaver** [vdemichev/DiaNN#303]
Hi Vladim,

I read on the DIA-NN documentations that spectral libraries can be generated from input files (.mzML files in my case).

I tried the following command:
`/usr/diann/1.8/diann-1.8 \
--gen-spec-lib \
--out-lib /working_dir/Data_Task/PREDICTED_LIB.speclib \
--temp "/working_dir/Data_Task/" \
--use-quant \
--out /working_dir/Results/report.tsv \
--threads ${num_threads} \
--f /working_dir/Data_Task/Sample1.mzML \
--f /working_dir/Data_Task/Sample2.mzML \
--f /working_dir/Data_Task/Sample3.mzML \
--use-quant \
--verbose 3 \
--min-fr-mz 200 \
--max-fr-mz 1800 \
--min-pep-len 7 \
--max-pep-len 30 \
--min-pr-mz 200 \
--max-pr-mz 1800 \
--min-pr-charge 1 \
--max-pr-charge 4 \
--met-excision \
--unimod4 \
--var-mods 2 \
--var-mod UniMod:35,15.994915,M \
--var-mod UniMod:1,42.010565,*n \
--monitor-mod UniMod:1 \
--reanalyse \
--smart-profiling \
--predictor \
--matrices \
--qvalue 0.01`

After executing that command I get the following error message (see below) and nothing else happens.
`DIA-NN 1.8 (Data-Independent Acquisition by Neural Networks)
Compiled on Jun 28 2021 10:59:57
Current date and time: Thu Feb 10 09:50:57 2022
Logical CPU cores: 32
A spectral library will be generated
Existing .quant files will be used
Thread number set to 30
Existing .quant files will be used
Min fragment m/z set to 200
Max fragment m/z set to 1800
Min peptide length set to 7
Max peptide length set to 30
Min precursor m/z set to 200
Max precursor m/z set to 1800
Min precursor charge set to 1
Max precursor charge set to 4
N-terminal methionine excision enabled
Cysteine carbamidomethylation enabled as a fixed modification
Maximum number of variable modifications set to 2
Modification UniMod:35 with mass delta 15.9949 at M will be considered as variable
Modification UniMod:1 with mass delta 42.0106 at *n will be considered as variable
A spectral library will be created from the DIA runs and used to reanalyse them; .quant f>
When generating a spectral library, in silico predicted spectra will be retained if deeme>
Deep learning will be used to generate a new in silico spectral library from peptides pro>
Precursor/protein x samples expression level matrices will be saved along with the main r>
Output will be filtered at 0.01 FDR
DIA-NN will optimise the mass accuracy automatically using the first run in the experimen>
The following variable modifications will be scored: UniMod:1

3 files will be processed`

What are the correct options/ command I'd need to use to generate a spectral library from mzML files ?

Best,
-Mathias.

**Comment by vdemichev** [comment]
Hi Mathias, DIA-NN needs to know what peptides to look for in the raw data, so need to specify either a spectral library or a FASTA database.

Vadim
