### ISSUE TITLE
Clarity on DIANN .pg_matrix numbers vs. DIANN.stats protein numbers

### ISSUE THREAD

**Issue by jdeyarmin** [vdemichev/DiaNN#304]
Hi Vadim, 

I've noticed that the DIANN.pg_matrix reports a different number of protein groups per sample than the PDF output or the `proteins.identified column' in the DIANN.stats file reports. Could you help me understand the differences between what is reported in each file, as well as help me understand what files I can use to compare the the different protein group results I am getting within the same analysis? 

Thanks in advance for your help! 

Cheers,
Jared

**Comment by vdemichev** [comment]
Hi Jared,

Please see the docs here https://github.com/vdemichev/DiaNN#output for info on what is being reported in each case. We ourselves use the main report file, but also fine to use pg_matrix for downstream analyses / comparisons between samples.

Best,
Vadim

**Comment by vegesnam** [comment]
For performing downstream analyses using tools such as MapDIA and MSStats, from the main report which column should we use for intensity values? I have been using Fragment.Quant.Raw for fragment level intensities, but there is a column for precursor level intensities (Precursor.Quantity), is that what I should be using instead?

**Comment by vdemichev** [comment]
I don't really remeber how exactly MapDIA and MSStats work, what I would suggest though is just use precursor-level or even protein-level information. The respective normalised quantities are Precursor.Normalised, PG.MaxLFQ or (if interested in gene quantities) Genes.MaxLFQ.

Best,
Vadim

**Comment by vegesnam** [comment]
Thank you for your answer! How are the PG.Quantity and Precursor.Quantity columns in the main report calculated? I assumed that they are derived from the fragment.quant.raw column, but when I add up the intensity values it doesn't match the precursor.quantity value:

![image](https://user-images.githubusercontent.com/87665957/153967050-e61bd58a-3d4e-4c26-b230-e08182d10f83.png)

**Comment by vdemichev** [comment]
Using selected fragments, please see the DIA-NN paper for the algorithm description.
