### ISSUE TITLE
Mass correction model in DIA-NN

### ISSUE THREAD

**Issue by cjhjhj** [vdemichev/DiaNN#305]
Hello Vadim,

According to the source file, it seems that the mass correction is performed by a linear model Ax = b, where A = [# precursors x 3] matrix, x = [3 x 1] vector, and b = [# precursors x 1] vector. The each row of A = [1, 1 / (fragment m/z) ** 2, 1 / (fragment m/z)], and every element of b = delta m/z / (fragment m/z) ** 2. Could you please tell me what this linear model really means and why it can be used to calibrate mass?

Thank you.

**Comment by vdemichev** [comment]
Hi, there's more complex mass correction in addition to this, but yes, the basic one is linear: this is because the 'drift' in masses is usually proportional to the mass.

Vadim
