### ISSUE TITLE
warning: unrecognized modification

### ISSUE THREAD

**Issue by msmedus** [vdemichev/DiaNN#31]
Hi Vadim,
I had a question regarding the deep learning feature in DIA-NN. I am analyzing PTM data and specify the respective UniMod with the --var-mod command. When using library-free deep learning, I get the following error message in the log: Encoding peptides for spectra and RTs prediction
WARNING: skipping 3738390 precursors; unrecognised modifications?
Has this to do with the variable modification I specified? does it have any negative impact on the analysis in general?
Thanks for clarifying!

best wishes,
Martin

**Comment by vdemichev** [comment]
Hi Martin,

Deep learning spectra/RTs prediction only works for methionine oxidation and for isotopic labels. Peptides with other modifications will not have their spectra/RTs predicted with deep learning. As a consequence, the resulting search will likely be strongly biased towards identifying properly predicted spectra. So when considering variable modifications it might make sense to disable deep learning. ID numbers will drop dramatically though. What can also be done is adding a spectral library while keeping FASTA digest option, this might speed up search and keep ID numbers of unmodified peptides good. But that's an experimental mode that hasn't been tested extensively.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
Hi Martin,

For now, deep learning spectra/RTs prediction only works for methionine oxidation and for isotopic labels. Peptides with other modifications will not have their spectra/RTs predicted with deep learning. As a consequence, the resulting search will likely be strongly biased towards identifying properly predicted spectra. So when considering variable modifications it might make sense to disable deep learning. ID numbers will drop dramatically though. What can also be done is adding a spectral library while keeping FASTA digest option, this might speed up search and keep ID numbers of unmodified peptides good. But that's an experimental mode that hasn't been tested extensively.

Hope this helps!

Best wishes,

Vadim

**Comment by msmedus** [comment]
Thanks for your prompt reply! that what I was thinking, too! Surprisingly, IDs for PTM modified peptides are much higher when ticking deep learning..
What I did to include modified peptides was to add a training library (using --learn-lib). With this +deep learning enabled, the numbers are further boosted. Would you recommend such an approach? 

thanks again!
Martin

**Comment by vdemichev** [comment]
I've actually never tried using training lib + deep learning at the same time. I think what's going to happen is that modified peptides will be assumed to have the same fragmentation pattern (predicted with --learn-lib) as unmodified ones. Which is often not far from reality, although such a spectrum will never be ideal. RT prediction for modified peptides will not be very accurate either. So you might be able to get more IDs this way, but there still will be a strong bias in detection towards unmodified peptides. Might want to try using --no-rt-window (disables RT window - a lot slower search but peptides with highly inaccurate predicted RTs will still have a chance to be detected). I am not an expert in PTM analysis using DIA, we ourselves have never tried it (only isotopic labels, which don't affect spectra or RTs, and methionine oxidation).

Best wishes,

Vadim

**Comment by msmedus** [comment]
Ok, thanks a lot! I will simply try out everything and see what I get :-)

cheers!

**Comment by msmedus** [comment]
Hello once again, I told you that deep learning was better than no deep learning in library-free mode when looking at PTMs. Actually, this is not true and contrary, with deep learning enabled I get less modified peptides, as anticipated by you. What I was to say is that when including a PTM learning library, I boost the IDs massively, and this gets even a little bit better with deep learning enabled. Sorry for the confusion and thank you for the suggestions, I will try them out one by one!

Best,
Martin

**Comment by johnpleid** [comment]
Dear Vadim is the deep learning still limited to Met Ox?
I created an unimod number for my modification and imported it in the unimod library and I get the same warning than above .
Have I to disable deep learning? 
Is the modification still researched if I let the analysis go?
Regards
