### ISSUE TITLE
protein database with or without decoys? => no error, just a question 

### ISSUE THREAD

**Issue by ihorrible** [vdemichev/DiaNN#310]
Hi everyone! 

Do I need to use protein database with decoys or without decoys? (see picture of my run in DIA-NN) 
![Снимок](https://user-images.githubusercontent.com/63013549/153795367-fff72f73-3a17-4a5f-b76b-ede5afad4ea9.PNG)

There is a version that DIA-NN can create decoys sequences by his own algorithms? 
What is the impact on the output if I will use the same protein database with or without decoys?  

Thank you,

Ivan

**Comment by vdemichev** [comment]
Hi Ivan,

Please don't use external decoys with DIA-NN, it always generates decoys automatically.

Best,
Vadim
