### ISSUE TITLE
Questions for diaPASEF data analysis by DIA-NN 

### ISSUE THREAD

**Issue by Liang-aaaaa** [vdemichev/DiaNN#32]
Dear Vadim,

we are building timsTOF peptide library using spectronaut 13.200430. However, it's time-consuming for the mass-spec aquisition and library generation from Pulsar. We wonder if we can analyze diaPASEF data on DIA-NN without library. Have you compare the results of libray searching and library free searching for diaPASEF data? If a library is recommended, which format of library should be imported to analyze DIA data acquired timsTOF? Can you send the recommended parameters you appliedin analyzing diaPASEF data to my emailbox: yueliangwias@126.com

Thanks a lot 
Liang

**Comment by vdemichev** [comment]
Hi Liang,

Yes, DIA-NN can analyse any DIA data in library-free mode, including diaPASEF data (those acquisition schemes that are supported by DIA-NN). In terms of identification numbers, it's always like this: Good spectral library > library-free > mediocre spectral library. When doing quantitative analysis, it's recommended to build a spectral library directly from the runs being analysed first and then rerun the analysis with this library. For diaPASEF I recommend setting both MS1 and MS2 mass accuracies to 10 ppm, everything else - default. But please note that diaPASEF support is alpha-stage and DIA-NN's performance when analysing diaPASEF runs will improve significantly in the future.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
On library format: all the same for diaPASEF as other DIA methods: Spectronaut, Peakview, OpenSWATH formats are supported without any modifications, experimental support for SpectraST and NIST.

**Comment by Liang-aaaaa** [comment]
Dear Vadim,

Thanks again for you quick feedback.

Best wishes,
Liang
