### ISSUE TITLE
Waters DIA data

### ISSUE THREAD

**Issue by muzafferarikan** [vdemichev/DiaNN#320]
Dear Vadim,

We have Waters SYNAPT G2-Si raw data and I am planning to use DIA-NN for protein identifications but I first wanted to ask if Waters data can be analyzed with DIA-NN. I am planning to convert it to mzml using msconvert (checked "combine ion mobility scans" and used two filters (lockmassRefiner(mz=785.842, tol=0.2) and then peakPicking (CWT, msLevel=1-) in msconvertgui ) and then analyze with DIA-NN. Would that be a correct approach?

Thank you.

**Comment by vdemichev** [comment]
Hi, I've heard that it's possible to analyse Waters data, but haven't done it myself. So would be great if you try and write here if it works.

Best,
Vadim
