### ISSUE TITLE
DiaNN1.8 - Random "Segmentation Fault" when running library-free analysis

### ISSUE THREAD

**Issue by hromanoc** [vdemichev/DiaNN#327]
Hi DiaNN team,

First of all, thank you for sharing this great tool. I wanted to report an issue that we constantly see when running DiaNN on our HPC for library-free based analysis. As shown in the attached image, we keep receiving randoms "Segmentation fault" just after the "Predicting spectra and IMs" step.

![DiaNN reporting Issue 1](https://user-images.githubusercontent.com/6304631/156698110-c3dea0e5-c125-4624-948c-9e2b1de00a79.png)

I hope someone could help debug this; if further information is needed, please feel free to ask.

**Comment by vdemichev** [comment]
Hi, this has been fexed by PyTorch update, the fix will be included in the next DIA-NN release.

Best,
Vadim

**Comment by Munchic** [comment]
@vdemichev Thank you so much for your work! I also had the same segfault issues as the OP. I wanted to ask: is there an approximate timeline on when we can expect the next DIA-NN release?

**Comment by vdemichev** [comment]
Days/weeks, but no promises.
