### ISSUE TITLE
specLib does not store info about what raw file(s) entries came from?

### ISSUE THREAD

**Issue by chambm** [vdemichev/DiaNN#33]
I'm working on a reader for BiblioSpec to convert the specLib format to blib format. Looking at the data structures in diann.cpp, it appears that Library (and thus the specLib format) does not keep track of which raw runs had evidence of which precursors. Have I missed something or was that linkage just not important for DiaNN?

**Comment by vdemichev** [comment]
Hi Matt,

Yes, this is indeed the case, there's no best run information in .speclib. 

Best wishes,

Vadim
