### ISSUE TITLE
`--fasta` vs `--reannotate`

### ISSUE THREAD

**Issue by fcyu** [vdemichev/DiaNN#330]
Hi Vadim,

May I ask some questions regarding `--fasta` and `--reannotate` when I am using a pre-built spectral library for DIA-NN?

1. Does `--reannotate` let DIA-NN digest the fasta file based on the provided digestion rules, filter out the peptides not following the digestion rules from the spectral library, and annotate the proteins? 
2. With `--fasta`, DIA-NN only annotate the proteins but does not perform digestion or peptide filtering. Am I understand it correctly?

Thanks,

Fengchao

**Comment by vdemichev** [comment]
Hi Fengchao,

It's the opposite: --fasta initiates the FASTA digest, while --reannotate is there to reannotate a spectral library. In the latter case, all peptides which could be obtained with given enzyme specificity, with unlimited number of missed cleavages, are considered.

Best,
Vadim

**Comment by fcyu** [comment]
Hi Vadim,

Thanks for your reply. What about the peptide length, mass, and modification constrains? Would they be applied to `--reannotate`?

Thanks,

Fengchao
