### ISSUE TITLE
Parellel processing in large datasets?

### ISSUE THREAD

**Issue by llniu** [vdemichev/DiaNN#331]
Hi Vadim,
We are processing a large dataset in library-free mode using dia-nn (also a relatively large FASTA database). Expectedly it is running slow. To speed it up, we are specifying --threads to 40 (the maximum on our computing platform). Are there any other ways to further speed it up? Would a GPU node help? Thanks a lot in advance!
Best,
Lili

**Comment by vdemichev** [comment]
Hi Lili,

Can consider restricting the precursor charge range (e.g. not considering charge 1 precursors), disabling variable modifications if enabled. 

Best,
Vadim
