### ISSUE TITLE
DiaNN for linux centos

### ISSUE THREAD

**Issue by apelin20** [vdemichev/DiaNN#332]
Hi,

I am stuck with glibc 2.17 on my CentOS system and from what I am reading it is not really possible to upgrade glibc.

I tried installing DiaNN from source code but it seems to be an older version - DIA-NN 1.7.12.

From what I read in a different post, only the .rpm package has the newer diaNN and that one requires a new glibc. Can you recommend a container or how to build one with a newer glibc so I can run disNN?

Thanks, Adrian

**Comment by vdemichev** [comment]
Hi Adrian,

I think one needs just a Docker container based on Ubuntu 18.04 - it's one of the standard ones.

Best,
Vadim

**Comment by apelin20** [comment]
I finally succeeded and wanted to share steps in case someone else needs to do this. I am by no means an expert in creating containers, but I was able to trim down an alphafold docker instruction file and add diaNN. Just save the following to a file called dockerfile_diaNN:

`FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04
ARG CUDA=11.1
SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential \
      cmake \
      git \
      hmmer \
      kalign \
      tzdata \
      wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/vdemichev/DiaNN/releases/download/1.8/diann_1.8.deb
RUN dpkg -i diann_1.8.deb

RUN chmod u+s /sbin/ldconfig.real

WORKDIR /usr/diann/1.8/
ENTRYPOINT ["/usr/diann/1.8/diann-1.8"]
` 
After which:
`sudo docker build -f dockerfile_diaNN .
sudo docker images
sudo docker save 8f51b697ba74 -o diann_8f51b697ba74.tar`

docker images tells you the name of the image you built, so need to substitute 8f51b697ba74 for that. After this, I convert the docker archive into a singularity container:
`sudo singularity build diann_8f51b697ba74.sif docker-archive://diann_8f51b697ba74.tar`
which allows me to run it on a cluster without sudo privileges. Usage:
`export LC_ALL=C; unset LANGUAGE; \
singularity run \
-B .:/data/apelin/ComplexFractionation/Exp01_A549_Vaccinia_03-08-2022/diaNN_1.8_trial1 \
--pwd /data/apelin/ComplexFractionation/Exp01_A549_Vaccinia_03-08-2022/diaNN_1.8_trial1 \
/home/apelin/programs/DiaNN/diann.sif \
--f Mock_SEC_F10_RB2_1_9935.d \
...
`
-B is needed for each directory where singularity needs to read from or write to. Hope this helps.
