### ISSUE TITLE
Protein Inference

### ISSUE THREAD

**Issue by Maithy15** [vdemichev/DiaNN#335]
Hi,

I accidentally set protein inference to genes in the DIA-NN search but the fasta sequence I provided did not have any gene name in it. Would DIA-NN automatically use other available options to group or would you recommend to re-run the analysis with another option?

Thanks

**Comment by vdemichev** [comment]
Hi, if there are no gene names, protein inference will probably work somewhat worse than it could, but still should be OKish. Makes sense to rerun though.

Best,
Vadim
