### ISSUE TITLE
relaxed protein inference not performed

### ISSUE THREAD

**Issue by AnStaes** [vdemichev/DiaNN#343]
Dear Vadim,
We wanted to use the relaxed protein inference and used the command line option --relaxed-prot-inf.
On the result file however, we still see teh same protein inference (with the proteotypic ones as separate). Also in the log file it states that inference was done with proteotypicity. Do we need to add something extra in order to have the relaxed rotein inference?
This was only 1 file, with 3 fasta file off which one is quite a large fasta file. We used the library free option. On FDR 0.01 there was no result (the log stated not using NN, but linear instead because of no results).

Thank you for your time.

Kind regards,
An

**Comment by vdemichev** [comment]
Hi An,

If no precursor are identified at 1% FDR, then protein inference will not be performed.

Best,
Vadim

**Comment by AnStaes** [comment]
Hi Vadim,

Very clear! Thank you!

Best,
An
