### ISSUE TITLE
pg_matrix and maxLFQ intensity: diann_maxlfq (function from diannR package) vs. pg_matrix

### ISSUE THREAD

**Issue by KR-15** [vdemichev/DiaNN#349]
Hi Vadim,

In the main report matrix, there is 3 PG intensity columns:
- PG.Quantity
- PG.Normalized
- PG.MaxLFQ

After checking, I can see that the maxLFQ is the intensity reported in the pg_matrix.

However, whan I run the following script:

`protein.groups <- diann_maxlfq(df[df$Q.Value <= 0.01 & df$PG.Q.Value <= 0.01,], group.header="Protein.Group", id.header = "Precursor.Id", quantity.header = "Precursor.Normalised")
`

I did not get the same dimension (i.e. same number of proteins: around 20 proteins less with the script) as the pg_matrix output. Moreover when I compare both matrices, the intensity values are not exactly the same.

Thank you for the clarification.

Best,

KR

**Comment by vdemichev** [comment]
Hi KR,

Please see the docs, they describe exactly what filtering is applied to generate the matrices. Also, the MaxLFQ algorithm in the R package is slightly different from that in DIA-NN itself, thus different intensities.

Best,
Vadim

**Comment by KR-15** [comment]
Ok thanks for the specification.

Best,

KR

**Comment by chrisfmontes** [comment]
Hi Vadim!
Sorry to bring this issue back to life, but I'm confused about why when I filter using the main report file at 1% FDR, using global q-values for protein groups (as is stated on the docs). I do not get the same number of protein groups as the pg_matrix file (there is a difference of ~100 protein groups, with the matrix reporting more than the main report file). Am I missing something, or juts not understanding the docs correctly?

Thanks for such a great software!
Christian
