### ISSUE TITLE
DIA-NN use only one physical CPU

### ISSUE THREAD

**Issue by mickaelleclercq** [vdemichev/DiaNN#351]
Hi,
I have 2 physical CPUs on my windows server and DIA-NN is only able to use one. 

More details: I have 2 times 44 threads available, DIA-NN can see 44 and other software are able to see 88. I tried to run two DIA-NN at the same time, only the first 44 threads of one physical CPU are used by both instances. 

Is there a way that DIA-NN sees all available threads from multiple physical CPUs ?

Thank you

**Comment by vdemichev** [comment]
Looks like some problem with Windows scheduling. Sorry, cannot help here. DIA-NN just uses the C++11 std::thread interface, should in theory use all available cores.
