### ISSUE TITLE
Differences between v1.7 and v1.8 regarding identified precursors/proteins

### ISSUE THREAD

**Issue by frankfreiburg** [vdemichev/DiaNN#356]
Hi,
we recently collected protein expression from tumour tissues using MS and analysed the raw data with both DIA-NN v1.7 and v1.8. With v1.7, 28,955 precursors (1% FDR) were identified, but 4,627 unique proteins (1% protein-level FDR) were found. This ratio was reversed with v1.8: there were 32,525 precursors (1% FDR) and 4,191 unique proteins (1% protein-level FDR). Do you have an explanation for why less precursor but more proteins are found with v1.7?
The analysis settings were identical in both runs:
 
- Library generation: FASTA digest for library-free search (yes); deep learning-based spectra and RTs prediction (yes).
- Peptide length range: 7 to 30; precursor m/z range: 300 to 1,800; fragment ion m/z range: 200 to 1,800
- Precursor FDR: 1 %
- in v1.7: RT-profiling (yes); in v1.8: MBR (yes)
- Neural network classifier: Double-pass mode
- Protein inference: Genes
- Quantification strategy: any LC (high accuracy)
- cross-run normalisation: RT-dependent
- Library generation: Smart profiling
- Speed and RAM usage: Optimal results
 
Many thanks in advance!
 
Kind regards
Frank

**Comment by vdemichev** [comment]
Hi Frank,

1.8 is a lot better than 1.7. Most likely, this is due to more stringent FDR control when uisng MBR in 1.8. If you wish, please share the logs & pg_matrix files, and I will take a look. Please don't use the double-pass mode.

Best,
Vadim

**Comment by frankfreiburg** [comment]
Hi Vadim,

thank you for you're immediate answer! I re-worked the analysis without double-pass mode and will share the logs and pg_matrix (the latter one was generated only with v1.8). I'd be glad if you could take a look at the files and maybe suggest some improvements for settings to use with v1.8.

[DIA-NN logs and pg_matrix.zip](https://github.com/vdemichev/DiaNN/files/8404212/DIA-NN.logs.and.pg_matrix.zip)

Best wishes
Frank

**Comment by vdemichev** [comment]
OK, results are logical. Looks like you are using a DIA-based library with MBR. Which is not expected to work well: the library is already highly project-specific, MBR is unnecessary. So can just use the first pass results as the final output here - and first pass clearly yields more proteins than 1.7 analysis.  

Also, please fix mass aaccuracies and scan window as described here: https://github.com/vdemichev/DiaNN#changing-default-settings

**Comment by frankfreiburg** [comment]
Yes, it is a DIA-based library. When using single-pass mode and turning off MBR more entries in the resulting expression matrix can be found, but also overall missingness increases compared to v1.7. Is there a way to optimize the results with focus on that? Thank you very much! (PS: For not changing to many parameters at once I did not fix mass accuracies and scan window yet.)
[v18Singlepassmode_noMBR.txt](https://github.com/vdemichev/DiaNN/files/8407547/v18Singlepassmode_noMBR.txt)
![DIANN](https://user-images.githubusercontent.com/102861705/161493077-2b333f91-0b5d-4274-86cc-ab4d8d09f59b.jpg)

Best wishes
Frank

**Comment by vdemichev** [comment]
That's most likely because 1.8 has stricter FDR control. Also, libraries were different, right? Maybe there's something about how they were created? Also, not sure how you filter the output matrix, there's a long discussion in DIA-NN's docs on this.

Best,
Vadim

**Comment by frankfreiburg** [comment]
Libaries were also created and refined separately with v1.7 and v1.8. Nevertheless, thanks for mentioning FDR control in v1.8.

However, thank you for your quick help and support regarding DIA-NN!

Best wishes
Frank
