### ISSUE TITLE
Error when installing diann-rpackage?

### ISSUE THREAD

**Issue by andyzim111** [vdemichev/DiaNN#36]
> install_github("https://github.com/vdemichev/diann-rpackage")
WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo vdemichev/diann-rpackage@master
WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Failed to install 'diann' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
> library(diann)
Error in library(diann) :

**Comment by vdemichev** [comment]
Yes, one does need Rtools, please install using the link http://cran.r-project.org/bin/windows/Rtools/ as indicated in the message
