### ISSUE TITLE
Implementation of other Modifications

### ISSUE THREAD

**Issue by MarST07** [vdemichev/DiaNN#364]
Hello Mr. Demichev,
Is it possible to implement other modifications than listed in DIA-NN?
I want to add methylene and methylol Modification on lysines to the workflow for processing FFPE tissues.
Is there an option for me to manually add these modifications?
Kind regards,
Stella

**Comment by vdemichev** [comment]
Hi Stella,

Yes, using --mod, --fixed-mod and --var-mod commands, also --strip-unknown-mods.

Best,
Vadim

**Comment by MarST07** [comment]
Thank you very much for the quick response! 
Also thank you for such a great software!

I also liked your presentations at proteomic forum 2021 and EuPa 2022. It was a pleasure to discovere these new tools like DIA-NN!

**Comment by vdemichev** [comment]
Thank you Stella!
