### ISSUE TITLE
External predicted library

### ISSUE THREAD

**Issue by jalew188** [vdemichev/DiaNN#365]
Dear Vadim,

This is not an issue but just a query:)

I am now using pDeep-predicted fasta libraries to analyze raw data with DiaNN (v1.8), and compare the IDs with DiaNN’s built-in (predicted) library.
 
For pDeep, I only predict the library for targets, and feed it to DiaNN. For DiaNN-built-in library, I provide the fasta file in the GUI. The predicted library (.speclib) sizes are similar but the results are quite different.
 
So, I have several questions about the behavior of DiaNN for built-in and external libraries.
 
1. Will DiaNN predict MS2/RT/IM for decoys in built-in or external libraries? Or all decoy generation steps are the same and will not involve any prediction steps?
2. Will DiaNN treat built-in and external libraries differently in the searching steps? If so, what are the differences?
3. How many fragments are kept in the DiaNN-built-in fasta libraries? Can I change it in GUI?
 
BTW, thank you very much for the wonderful software, it is super-fast when doing fasta library search. I have tried many others when I was developing pDeep from 2015 to 2017, and all of them failed to search with such a huge library for speed issues or memory issues.
 
Best regards,
Wen-Feng Zeng

**Comment by vdemichev** [comment]
Hi Wen-Feng,

1. Decoys are generated by DIA-NN internally in an automatic manner which is invisible to the user. No prediction involved therein.
2. No, all the same.
3. Max 12 fragments. No, cannot change.

Best,
Vadim

**Comment by jalew188** [comment]
Thank you for your quick replies
