### ISSUE TITLE
Incorrect Unimod ID for dioxidation

### ISSUE THREAD

**Issue by matthewhuebsch** [vdemichev/DiaNN#368]
Hi there,

It appears that there is a typo for the dioxidation modification here: https://github.com/vdemichev/DiaNN/blob/63b9b33ae0177fa75d09128afb41fd32d68fb575/src/diann.cpp#L462

Unimod 325 is FP-biotin of mass 572.316129 Da (https://www.unimod.org/modifications_view.php?editid1=325)

I suspect that this line should reference Unimod **425** instead, which has mass 31.989829 Da (https://www.unimod.org/modifications_view.php?editid1=425)

Thanks!
Matt

**Comment by vdemichev** [comment]
Hi Matt, indeed, many thanks for letting me know!

Best,
Vadim
