### ISSUE TITLE
Error loading a previously saved .pipeline

### ISSUE THREAD

**Issue by tuvanasatar** [vdemichev/DiaNN#39]
Hi Vadim,

I'm contacting you about a problem that I have encountered with the .pipeline format from DiaNN. 
I could save and re-open my pipeline without problem, but when I click on one of the steps (for example to verify the settings that were saved), I get the following error : "StartIndex cannot be less than zero" (please see the screenshot below). 

Where could this error come from?
Additionnally, when I click on "Continue" DiaNN stays open, but I can see that the settings that are shown in the interface are not the ones I saved into my pipeline. 

Thank you in advance for your response.

Best regards,
Tuvana 

![DiaNN_error_pipeline](https://user-images.githubusercontent.com/66627057/84034825-25f41680-a99b-11ea-89dd-d2c275bca79a.png)

**Comment by vdemichev** [comment]
Hi Tuvana,

Thank you for reporting this! I guess it only happens with this specific pipeline? Would you be able to share the .pipeline file? I will then try to debug this.

Best wishes,

Vadim

**Comment by tuvanasatar** [comment]
Hi Vadim,

It seems to happen with any .pipeline that I save.
Here's an example. 
[test-pipeline.zip](https://github.com/vdemichev/DiaNN/files/4746645/test-pipeline.zip)

Thanks again.

Best regards,
Tuvana

**Comment by vdemichev** [comment]
Thank you, will look into this

Vadim

**Comment by vdemichev** [comment]
Found the cause of the problem, thank you so much for reporting this! I will fix it in the next DIA-NN version. Meanwhile, please save the pipeline in such a way that (i) the number of threads is not greater than the number of logical CPU cores on the target PC (ii) Precursor FDR value is a decimal with a dot: e.g. '100.0' is OK, while just '100' will cause an error.

Please let me know if this works.

Best wishes,

Vadim

**Comment by tuvanasatar** [comment]
Hi Vadim,

It seems to work with your recommandations!

Thank you for your quick response.

Best regards,
Tuvana
