### ISSUE TITLE
Behavior of spectrum generation when it uses both spectral library and sequence database.

### ISSUE THREAD

**Issue by progistar** [vdemichev/DiaNN#391]
Hello, I am Seunghyuk Choi from Hanyang University, Seoul, Korea.
I have a quick question about spectrum generation.

Some peptides are included in both spectral library and fasta sequence db.
In this case, redundant spectra could exist. I ask the behavior of DIA-NN (e.g. use both or use one of them)

Thanks in advance.

**Comment by vdemichev** [comment]
Hi Seunghyuk, DIA-NN should not be used with both a spectral library specified and a FASTA digest enabled.

Best,
Vadim
