### ISSUE TITLE
Problem installing on Parallels

### ISSUE THREAD

**Issue by wolski** [vdemichev/DiaNN#393]
I am trying to install DiaNN on Windows 11 running with Parallels on a mac m1 with no success.

![image](https://user-images.githubusercontent.com/1926513/170001682-e240f23b-90e9-4a68-a755-a3edaa60eeaa.png)

Did read this issue but did this did't help.
https://github.com/vdemichev/DiaNN/issues/97

the setup exe is in 
C:\Users\<username>\Downloads\DIA-NN.1_8_1.Setup.exe

**Comment by vdemichev** [comment]
Problem with Parallels / file permissions? Try creating a folder C:/Temp/ and running the installer from it?

Vadim

**Comment by vdemichev** [comment]
If installer does not work, can just install on Windows & copy all installed files to some folder on Parallels manually. The DIA-NN installer just unpacks stuff + installs VC++ distributable if necessary, but the latter can also be done manually.
