### ISSUE TITLE
Can't work out why the parameters passed to diann.exe differ

### ISSUE THREAD

**Issue by wolski** [vdemichev/DiaNN#396]
To me the GUI settings seem very similar:

Gui Session 1:
![image](https://user-images.githubusercontent.com/1926513/170283015-ea5c10ec-a50f-43b5-8101-9b1b0c8ee22a.png)
Gui session 2:
![image](https://user-images.githubusercontent.com/1926513/170283336-4f852001-2f13-4841-aefc-017f0251181a.png)
Diff
![image](https://user-images.githubusercontent.com/1926513/170283578-04d6f257-2ffd-4fad-b5a4-35bf8763fd17.png)

Why in session 1 (right of the diff) these parameters are passed : 

 --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 

, but not in session 2 (left of the diff).

**Comment by vdemichev** [comment]
FASTA digest was somehow deselected for the first session

**Comment by wolski** [comment]
Thanks
