### ISSUE TITLE
I want to  (have to) filter for two peptides per protein.

### ISSUE THREAD

**Issue by wolski** [vdemichev/DiaNN#398]
When reporting protein IDs or Quant's, journals require at least two peptides to identify a protein.

I am thinking of using the "report.tsv" and implementing as follows:
  * Compute the number of "Stripped.Sequence" per "Protein.Group" then filter "Protein.Group" where the number of Stripped.Sequence > 1.
  * Afterward, filter proteins for Q-value:
    * Lib.PG.Q.Value < 0.01
    * PG.Q.Value < 0.05

Since I used MBR, I should use Lib.PG.Q.Value instead of Global.PG.Q.Value, according to the documentation,

However, you describe more options for filtering, e.g., using PG.Q.Value in:
- How to choose the FDR/q-value threshold?

Is the answer applicable to MBR runs? That is, can I use PG.Q.Values when MBR is enabled and Lib.PG.Q.Value instead of Global.PG.Q.Value?

**Comment by vdemichev** [comment]
I would suggest:
- Filter report.tsv at global precursor FDR 1% and global protein FDR 1%, in addition to 1% run-specific precursor FDR.
- Determine proteins for which there are at least two stripped sequences (in the filtered data).
But I don't think this journal request makes sense for most analyses, so to formally comply with it can also calculate the number of stripped sequences matching the protein before the filtering.

With or without MBR, using PG.Q.Value filters at run-specific protein FDR. 

Vadim

**Comment by wolski** [comment]
Thank you.
