### ISSUE TITLE
Wrong spectral library headers 

### ISSUE THREAD

**Issue by fossatiA** [vdemichev/DiaNN#4]
Hi, 
I'm trying to run DIA-NN using a spectral library generated from SpectraST. I renamed all columns according to the docs 

`
rn = {
'PrecursorMz': 'Precursor m/z',
'ProductMz': 'Fragment ion m/z',
'PrecursorCharge' : 'Precursor charge',
'ModifiedPeptideSequence' : 'Modified peptide sequences',
'NormalizedRetentionTime': 'Reference retention time',
'LibraryIntensity': 'Relative intensity of the fragment ion',
'UniprotId' : 'UniProt identifiers',
'ProteinId' : 'Protein names',
'GeneName': 'Gene name',
'ProductCharge' : 'Fragment ion charge',
'PeptideGroupLabel' : 'Elution group',
'FragmentType' : 'Fragment ion type'
}
`
However,  the error raised is
WARNING: cannot find column  ModifiedPeptide LabeledSequence FullUniModPeptideName "FullUniModPeptideName" 
There is no mention of this column in the manual
https://github.com/vdemichev/DiaNN/blob/master/DIA-NN%20GUI%20manual.pdf

After checking the source code is clear that Modified peptide sequences (from the manual) is not present in the headers, so for most of the other headers. Is the doc outdated?

`
std::vector<std::string> library_headers = {
	" ModifiedPeptide LabeledSequence FullUniModPeptideName \"FullUniModPeptideName\" modification_sequence ",
	" PrecursorCharge Charge \"PrecursorCharge\" prec_z ",
	" PrecursorMz \"PrecursorMz\" Q1 ",
	" iRT iRT RetentionTime NormalizedRetentionTime Tr_recalibrated \"Tr_recalibrated\" RT_detected ",
	" FragmentMz ProductMz \"ProductMz\" Q3 ",
	" RelativeIntensity RelativeFragmentIntensity RelativeFragmentIonIntensity LibraryIntensity \"LibraryIntensity\" relative_intensity ",
	" UniprotId UniProtIds UniprotID \"UniprotID\" uniprot_id ",
	" Protein Name Protein.Name ProteinName \"ProteinName\" ",
	" Genes Gene Genes \"Genes\" ",
	" IsProteotypic Is.Proteotypic Proteotypic ",
	" Decoy decoy \"Decoy\" \"decoy\" ",
	" FragmentCharge frg_z \"FragmentCharge\" ",
	" FragmentType frg_type \"FragmentType\" ",
	" FragmentNumber frg_nr FragmentSeriesNumber \"FragmentSeriesNumber\" ",
	" FragmentLossType \"FragmentLossType\" ",
	" Q.Value QValue Qvalue qvalue \"Q.Value\" \"QValue\" \"Qvalue\" \"qvalue\" ",
	" ElutionGroup ModifiedSequence ",
};
`

**Comment by vdemichev** [comment]
Hi fossatiA, what you interpreted as header names (in the manual) are not actual header names but explanations of what the respective columns should contain. I have now updated the manual to make this clear. Also gave an example of how to use the --library-headers command - this is the approach which I suggest for using libraries not in PeakView, Spectronaut, OpenSWATH or DIA-NN format.
