### ISSUE TITLE
About library building

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#43]

**Comment by Clovernana** [comment]
Hi，
I used proteome discoverer to build a library based on DDA ,and then import the result to the skyline and then export the report(.tsv).I have refined the column name according to the DINNN GUI mannual. I have tried many times using DIANN ,and all produce no result.I have put the labrary file here and could you please help me check it out?



Thanks!
Best Wishes！
clover

**Comment by vdemichev** [comment]
Hi Clover,

Maybe this can help: https://skyline.ms/announcements/home/support/thread.view?rowId=38631
Also, if you email me the library or attach it to a post here (cannot see any attachments at the moment), I can have a look - it's very easy for me to troubleshoot such things, so please don't hesitate to contact me if something is not working. In general, any .tsv/.csv/.txt/.xls library compatible with Spectronaut/OpenSWATH/Peakview should work with DIA-NN.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
You mean Skyline fails to save the library using the spectronautlibrary.skyr template? Can also try the OpenSWATH template as described here http://openswath.org/en/latest/docs/skyline.html

Vadim

**Comment by Clovernana** [comment]
Yes.I also tried the openswath.skyr.And all failed to run.
![image](https://user-images.githubusercontent.com/50875585/88053637-b1fa8000-cb8e-11ea-9b1f-f157d5959fe3.png)

**Comment by vdemichev** [comment]
Sorry, not getting what's going on :) You've attached a screenshot on which DIA-NN succesfully loaded some library and analysed a run with it. What's not working then?

**Comment by Clovernana** [comment]
It‘s the whole process in the DIANN run that I use a spectranaut.skyr based library.And normally，this will produce the relavant result files.But there’s nothing. What's more,there is no wrong with my computer.And the memory is fully enough.

**Comment by vdemichev** [comment]
OK, I think I know what the problem is. Please add a column 'UniprotID" to the library (using R/Python/Excel). Alternatively, add a FASTA database when analysing and select the option 'Reannotate'. I think this is likely to solve it, will be able to say for sure if you share the library (293T_lib.tsv). Also, I don't think it makes sense using deep learning spectra/RTs prediction when analysing with this library. I also wonder, if you are analysing regular human cell lysate, without looking for PTMs, why not just use a large publicly-available HeLa/HEK library, for example? This will give a lot more identificaitons.

Hope this helps,
Best wishes,
Vadim

**Comment by Clovernana** [comment]
Ok,let me try it.By the way,have you used the skyline to export the library result ?I have been confusing with a ploblem that different transition settings(different MS range in isolation scheme )causes different libararies.And default transition setting produce less protein number library.Is that normal ？but proteome discoverer identifies more than all the different transition settings.And is there publicaly available HEK libraries or website?Could you please recommand that for me?I have only downloaded one from one article.

**Comment by vdemichev** [comment]
Sorry, I am really not an expert in using Skyline. I only discovered it today that it can export libraries :) 
Yes, there are good libraries out there. In general, spectral library built for one human cell line will be pretty good for other cell lines, so can also use HeLa, etc. For example, ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2019/08/PXD013658/HeLa_Hybrid-Project-Library_final.xls or https://db.systemsbiology.net/sbeams/cgi/downloadFile.cgi?name=phl004_canonical_sall_pv.csv;format=tsv;tmp_file=749c2c7f428a980081cf1d33dd12a387;raw_download=1

Vadim

**Comment by Clovernana** [comment]
OK,your help really works.Which condition is recommanded  for using deep learning spectra/RTs prediction ?when a big library is imported?

**Comment by vdemichev** [comment]
Please see the library links above. For these I don't think there's a need to use deep learning spectra/RTs prediction - this feature is only useful when the library is bad.

Vadim

**Comment by Clovernana** [comment]
Ok,thank you so much.
