### ISSUE TITLE
cores used

### ISSUE THREAD

**Issue by juliehamon** [vdemichev/DiaNN#44]
Hi Vadim,

we noticed that on one of our server with 96 logical processor (2 sockets, 48 cores) we are only allow to select 48 threads in DiaNN. We had the same "issue" with Spectronaut and they explained us that it's a bug but even if it shows only 48, it runs on 96 cores. Is it the same kind of bug for DiaNN?
On another server with 56 cores it allows us to select the 56th but apparently the bug arise when we are working with a server with more than 64 cores.

Thanks for your help,

**Comment by vdemichev** [comment]
Hi Julie,

That should not happen, actually. The GUI should limit the number of threads to the number of logical cores, not physical cores. Maybe indeed some bug in the GUI. I would suggest just overriding the GUI setting by typing "--threads 96" (without quotes) in the Additional options text box.

Best wishes,

Vadim

**Comment by juliehamon** [comment]
ok we will do this, thanks!

Best
Julie
