### ISSUE TITLE
Warning in DIA-NN

### ISSUE THREAD

**Issue by MarST07** [vdemichev/DiaNN#445]
Hey Vadim,

I have a new Issue from my current DIA-NN search. I get the following warning:
WARNING: more than 1000 different windows - is this intended?

I actually do not understand what that means, because I used the same DIA method as before and I did not have this warning before?
Did I do a mistake in the Settings for DIA-NN?

Thank you very much and kind regards,
Stella

**Comment by vdemichev** [comment]
Hi Stella,

Was this solved? You could look up what kind of DIA windows DIA-NN sees in the data using --export-windows: it will save a .txt file to the same location as the raw file being analysed. 

Best,
Vadim

**Comment by MarST07** [comment]
Hey Vadim,

 

Yes I already solved the problem. It was a DDA measurement what caused this warning and the RAW files were named so similar that I used the wrong RAW files for the DIA-NN search.

Now with the DIA RAW files it runs as perfect as always!

Thank you very much for responding.

 

Kind Regards,

Stella
