### ISSUE TITLE
About DDA library building

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#45]
Hi Vadim，
I wonder that if there is no iRT addition in the DDA run but  I also want to use proteome discoverer or Maxquant to build a DDA librray,it means that I can't use skyline to export the compatible format with DIANN(I have tried to import the PD result without iRT but it failed to run).How  could I get a available format with DIANN?
Thank you ！
Clover

**Comment by vdemichev** [comment]
Hi Clover,

Sorry, I don't really know what are the requirements of Skyline to be able to load a PD report. Maybe it's not the lack of iRT that is the issue? If I remember correctly, Skyline is able to use any peptides for the alignment, e.g. CiRT peptides or any other set of peptides you specify. I would suggest maybe asking on the Skyline forum, why that PD report cannot be loaded?

DIA-NN itself does not use iRT peptides in any way. 

Best wishes,

Vadim

**Comment by Clovernana** [comment]
Hi,
Thanks  for you apply. I have already known that DIA-NN itself does not use iRT peptides in any way. I just wonder whether DIA-NN support the reesult (.txt or .tsv)of PD or Maxquant?

Best wishes,

Clover

**Comment by vdemichev** [comment]
No, no direct support for PD/MaxQuant Reports yet...

Vadim

**Comment by Clovernana** [comment]
OK.Thank you. Is ther any other avalible open-source softwares  for the DDA analysis?

**Comment by vdemichev** [comment]
Yes, FragPipe (with integrated MSFragger) https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html. It can built spectral libraries in the OpenSWATH format, which is compatible with DIA-NN.

Vadim

**Comment by Clovernana** [comment]
OK,thank you very much.

Clover

**Comment by vdemichev** [comment]
Btw, if you are looking for identifying peptides without fancy modifications, you can just supply DIA-NN with a peptide list formatted as a FASTA file. And then use deep learning based spectra/RTs prediction in DIA-NN, which will produce an in silico generated spectral library.

I usually format peptide lists like this:
>AAAATGTIFTFR
AAAATGTIFTFR
>AAANQMR
AAANQMR
...

So the FASTA header (after '>' sign) is just the peptide sequence.

If you don't want DIA-NN to further digest this peptide list, add "--cut-after X" (without quotes) to the 'Additional options' text box.

Vadim

**Comment by Clovernana** [comment]
Hi,
Thanks for your kind help.So you mean that DIA-NN is designed to identify protein groups mainly by its sequence and the detected peptides in DDA  and the retention time alignment is not so important.Right？ I have tried to use the MSFragger to build the spectra library but it seems didn't produce what I want.The log file is here.
[PBMC_fail.txt](https://github.com/vdemichev/DiaNN/files/4970876/PBMC_fail.txt)
Actually,I want to merge many DDA runs(lable free and no fancy PTM) to only one spectra library,but it seems that there are seperarte results in the MSFragger.All the output is here.
![image](https://user-images.githubusercontent.com/50875585/88372882-5ec04180-cdc9-11ea-906d-72dcc61d2669.png)
The combined.prot should be the merged result.But the format .XML is not suitable for DIANN.Have you met the similar problems?
Really sorry,I'm new to proteomics and always have some basic questions.Thanks for your reply with patience  everytime.

Best wishes!
Clover

**Comment by vdemichev** [comment]
Hi Clover,

It's good to have empirical spectra & RTs, but predicted ones are almost as good :) 

Please try selecting 'Generate spectral library from search results' option in the report tab of FragPipe. 
This will produce a spectral library in .tsv format, the file name should be con_lib.tsv or something like that.
When using this library, please add ' --library-headers *,*,*,*,*,*,Protein ID,Entry Name' (without quotes) to the 'Additional options' text box in DIA-NN.

Hope this helps!
Best wishes,

Vadim

**Comment by Clovernana** [comment]
Hi Vadim,
I have already selected the  'Generate spectral library from search results' option in the report tab of FragPipe.But it seems no con_lib.tsv or  something like that.

Best wishes,

Clover

**Comment by vdemichev** [comment]
Really strange... It does work for me like this. I would suggest asking about this on the FragPipe github.

Vadim

**Comment by Clovernana** [comment]
Well, this is the only way now.


On 7/24/2020 20:53，Vadim Demichev<notifications@github.com> wrote：

Really strange... It does work for me like this. I would suggest asking about this on the FragPipe github.

Vadim

**Comment by Clovernana** [comment]
Oh，I just want to build a hybrid library based on the existed literature ,but the LC condition ，MS intrument and gradient are different.In this condition,I think I can adopt the method as you told me that compile a FASTA file.Is it that OK?




On 7/24/2020 20:54，姜娜<16622080827@163.com> wrote：
Well, this is the only way now.


On 7/24/2020 20:53，Vadim Demichev<notifications@github.com> wrote：

Really strange... It does work for me like this. I would suggest asking about this on the FragPipe github.

Vadim

**Comment by vdemichev** [comment]
Yes, that should be fine.

Vadim

**Comment by Clovernana** [comment]
OK,thank you !

**Comment by She1111** [comment]
> Hi Vadim,

Can I add peptides sequences into fasta file with its protein annotation? I do not want DIA-NN to cleave the digested peptides I have added, but I want it to cleave the other protein sequences. How can I achieve this?

Thank you very much!

Best regards,
Shel
