### ISSUE TITLE
Questions about files for. quant results

### ISSUE THREAD

**Issue by betsyfriend** [vdemichev/DiaNN#452]
Hello! There is a question would like to ask you, I want to know the general look .quant results of which software to see? Is this quantitative result normalized? If there is no corresponding software to open it, I can compare them directly, right? What is better if they are compared directly in proteome?

**Comment by vdemichev** [comment]
No, .quant files acannot be accessed

**Comment by betsyfriend** [comment]
&nbsp;Dear&nbsp;vdemichev,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Hello！Thankyou for your reply!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; I would like to ask you, we want to see the proteomic quantitative file is to see report.tsv? I read some articles, they used your software, they said with DIA-NN quantitative results have normalized, there is no comparison between samples, I would like to ask the current version is also need to compare themselves?
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; I am looking forward to your reply!I wish you all the best!

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Miss Li


李珂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vdemichev/DiaNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vdemichev/DiaNN] Questions about files for. quant results (Issue #452)





 
No, .quant files acannot be accessed

**Comment by betsyfriend** [comment]
Thankyou for your reply!
 I would like to ask you, we want to see the proteomic quantitative file is to see report.tsv? I read some articles, they used your software, they said with DIA-NN quantitative results have normalized, there is no comparison between samples, I would like to ask the current version is also need to compare themselves?
