### ISSUE TITLE
Protein group FDR control while generating DIA-based DiaNN library

### ISSUE THREAD

**Issue by tuvanasatar** [vdemichev/DiaNN#46]
Hi Vadim, 

I'm wondering if there's a protein group FDR control that is applied when we generate a DIA-based library in DiaNN, similarly to maxQuant for example? If this is not done by default, is there any additionnal command line to specify while running DiaNN? 

Thanks in advance.

Best,
Tuvana

**Comment by vdemichev** [comment]
Hi Tuvana,

There's global precursor-level FDR control, but no protein one yet. 
In general, protein level FDR estimation has been significantly improved in the development version of DIA-NN - yielding more proteins at 1% FDR (this is not yet on github), I am not sure yet if implementing protein FDR for the library is a good idea (one does get protein FDR when using this library anyway).

Vadim
