### ISSUE TITLE
Missing instructions how to build from source

### ISSUE THREAD

**Issue by paulmenzel** [vdemichev/DiaNN#465]
Could you please point me to instructions how to build the software from source in a GNU/Linux environment?

Are the packaging scripts – like Debian package `rules` file – available?

**Comment by vdemichev** [comment]
Sorry, DIA-NN is closed source, building is impossible.

**Comment by paulmenzel** [comment]
Thank you for the quick answer. A bigger notice in the README, that Dia-NN is proprietary, closed source software would be nice to have, as most GitHub project are FLOSS – especially science software.

Also, I have not read GitHub’s usage terms, but on their [pricing page](https://github.com/pricing) they write for the free plan:

> Host open source projects in public GitHub repositories, accessible via web or command line. Public repositories are accessible to anyone at GitHub.com.

No idea, if you have the free plan though.
