### ISSUE TITLE
Fragment Data

### ISSUE THREAD

**Issue by Naadir-Ganief** [vdemichev/DiaNN#47]
Is it possible to work out which fragments are listed in the columns Fragment.Quant.Raw/Corrected and Fragmetn.Correlations columsn?

Also, for all identical precursors identified during the search are the same fragments llisted in each row? (If the library has more than 6 transitions/precursor)

Thanks a lot, for the great software

**Comment by vdemichev** [comment]
Hi, yes please add "--report-lib-info" (without quotes) to the Additional options textbox and DIA-NN will add fragment annotation to its report.

Yes, fragments are always the same. 

Vadim

**Comment by Naadir-Ganief** [comment]
Thanks!
