### ISSUE TITLE
How to generate a .tsv library in silico?

### ISSUE THREAD

**Issue by ludgergoeminne** [vdemichev/DiaNN#48]
Dear Vadim

I really like DIA-NN; it is quite impressive what you managed to create!

I have an MSX dataset, which unfortunately is not yet supported in DIA-NN, according to the error message.
Therefore, I tried to use DIA-NN to generate an _in silico_ library based on the mouse FASTA proteome, which I obtained from Uniprot. I would then try to use this library in e.g. Skyline, to search my data.
I did manage to create a ".speclib" file, but DIA-NN does not output a ".tsv" library.
I've tried quite a few variations on the following already, but without succes:

`.\diann.exe --lib "D:\Documents\output_DIA-NN_2\lib.predicted.speclib" --threads 4 --out-lib "D:\Documents\output_DIA-NN_3\lib.tsv"`

What can I do to create a ".tsv" library output?

Many thanks!

Best regards

Ludger

**Comment by vdemichev** [comment]
Hi Ludger,

Please add "--gen-spec-lib" to the command line or use the "Generate spectral library" option in the GUI.
Please note that the .tsv file will be significantly larger than .speclib and might take lots of time to load in Skyline.

Hope this helps!

Best wishes,

Vadim

**Comment by ludgergoeminne** [comment]
Hi Vadim

This seems to work, indeed.
Many thanks for your swift reply!

Best wishes

Ludger
