### ISSUE TITLE
Precursor Quantification Question

### ISSUE THREAD

**Issue by FloBay** [vdemichev/DiaNN#499]
Hello, 

I am new to DIA-NN and have a very basic question to the Precursor.Quantity: 

How do you optain the Precursor.Quantity based on your fragment ions (which are also present the report.tsv)? 
I got quite close but, there appears to be some filtering of fragment ions when rolling up to the Precursor.Quantity.

In the plot below i summed up the first 6 fragment ions. But, as you can see, in many cases the Precursor.Quantity is less than summing up the top 6 fragments. That's why i think there is some (advanced?) filtering happening..
![image](https://user-images.githubusercontent.com/14998394/190674107-c3611610-608d-4ed3-a06b-866e289241d4.png)

Thank you
Florian

**Comment by vdemichev** [comment]
Hi Florian,

Sum of 3 fragment ions out of top 12 selected based on average correlation score (Fragment.Correlations) across all runs.

Best,
Vadim

**Comment by FloBay** [comment]
Thanks for the lightning fast response :) 

So the fragments get sorted by the correlation score (1 is good, 0 is bad) and the intensities of the 3 best correlating ones will be summed to make one precursor, correct ?

**Comment by vdemichev** [comment]
Average correlation score across all runs - yes.

**Comment by FloBay** [comment]
I see. Thank you :) 

Then, i guess its not possible to reconstruct them from the report.tsv, or is perhaps the order of the ';'-fragments preserved in all other runs ?

**Comment by vdemichev** [comment]
Order of the fragments is the same in all runs
