### ISSUE TITLE
mzML mscovert option

### ISSUE THREAD

**Issue by nathemie** [vdemichev/DiaNN#5]
We tested two types of mzML file to run DIANN. The one without write index selected is not working for `No MS2 spectra: aborting.` since the sentence in the manual confused us  'vendor centroiding enabled and all other options except “Write index” disable" which actually means write index should be selected.

![image](https://user-images.githubusercontent.com/51101922/70391427-1b6abb80-1a10-11ea-98de-68b0cf7f0b99.png)
Here we would to confirm if this is the recommended option to use msconvert? Thanks

![image](https://user-images.githubusercontent.com/51101922/70391444-55d45880-1a10-11ea-961c-d2fd28271a20.png)

**Comment by vdemichev** [comment]
Hi nathemie, yes, write index should be enabled. I agree, it's written in a way that is a bit confusing :)
