### ISSUE TITLE
About False Positive

### ISSUE THREAD

**Issue by August-j** [vdemichev/DiaNN#50]
Dear Vadim,
I would like to ask how to filter out the false positive proteins with the method library-based and library-free respectively. I have tried to filter out the false positive proteins with the method library-based, which is consistent with the number of proteins identified in the DIANN report, but the method library-free  filtering out the false positive proteins is different from  the report(Q value is 0.01), so I would like to ask how to filter out the false positive proteins with the method library-free.

Best wishes,

August-j

**Comment by vdemichev** [comment]
Hi, please use filtering based on either PG.Q.Value or GG.Q.Value. Library-free and library-based reports can be analysed the same way. Can you please explain in more detail what was inconsistent in your tests?

Vadim

**Comment by August-j** [comment]
Hi,
I did use PG.Q.Value to filter.Library-free reports identified 6000+protein.When I filter false positive protein, proteins are 7000+(I set PG.Q.Value<0.01)

**Comment by vdemichev** [comment]
"I did use PG.Q.Value to filter.Library-free" and "When I filter false positive protein" - what do exactly is being done and what's the difference? Can you please provide a step-by-step description of what you are doing in each case?

**Comment by August-j** [comment]
Sorry, I didn't make it clear before
I used library-free method to test the data by DIANN, the report showed that the number of protein groups are 6000+.I imported the report into R to filter out the false positive protein, but the result showed that the number is 7000+(I set  PG.Q.Value<0.01).So I want to know if 0.01 is correct value.

Thanks

**Comment by vdemichev** [comment]
OK, I think I got it. You mean when analysing DIA-NN reported 6000 unique proteins at 1% protein-level FDR? That figure is always lower than the number of protein groups, because only proteins identified with proteotypic (i.e. specific) peptides are counted.

Vadim

**Comment by August-j** [comment]
Ok.Thank you
