### ISSUE TITLE
linux error: terminate called after throwing an instance of 'std::invalid_argument'   what():  stoi Aborted (core dumped)

### ISSUE THREAD

**Issue by Naadir-Ganief** [vdemichev/DiaNN#51]
Hi, 
I am trying to run DIA-NN on ubuntu 18.04. but i get the error below:

Compiled on Aug 25 2020 13:05:41
Logical CPU cores: 12
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

below are the commands used: 

$diann --f /home/naadir/Mouse_Infections/linux-diann/010720_NG_43min_SWATH_MouseInfections_MPI-0hrs_1_2.mzML.dia --lib $SpecLib --threads  --verbose 1 --out $MainOut --out-gene $GeneOut --qvalue 0.01 --matrices  --temp $tempDir --out-lib $SpecLibOut --gen-spec-lib --prosit --reannotate --fasta $fasta --met-excision --cut-after KR --missed-cleavages 2 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 350 --max-pr-mz 1050 --unimod4 --var-mods 2 --unimod35 --individual-mass-acc --individual-windows --rt-profiling --pg-level 0 --report-lib-info

thanks

**Comment by Naadir-Ganief** [comment]
I should note, all the these commands are from a bash script, below are the variables defined:

DataDir=/home/naadir/Mouse_Infections/linux-diann/
tempDir=/home/naadir/Mouse_Infections/linux-diann/temp/
SpecLib=/home/naadir/Mouse_Infections/linux-diann/DB/BCG_Mouse_lib.tsv
fasta=/home/naadir/Mouse_Infections/linux-diann/DB/uniprot-MycoBCG_MusMusculus_Contam_April_2020.fasta
SpecLibOut=/home/naadir/Mouse_Infections/linux-diann/Output/240820_MPIvsRAW_BCG_Infection.GenLib.tsv
MainOut=/home/naadir/Mouse_Infections/linux-diann/Output/240820_MPIvsRAW_BCG_Infection.tsv
GeneOut=/home/naadir/Mouse_Infections/linux-diann/Output/240820_MPIvsRAW_BCG_Infection.genes.tsv

#diann executable
diann=~/diann/./diann-linux

**Comment by vdemichev** [comment]
Hi, this is probably because the threads number is not specified. Need to have some integer after --threads. Also, please note that deep learning spectra/RTs prediction is not supported on Linux, therefore library-free search will be significantly less efficient. Might be a fold-change difference in terms of the numbers of peptides. 

Best wishes,

Vadim

**Comment by Naadir-Ganief** [comment]
Thanks, 
that seems to have done the trick, 
now i see that "--report-lib-info" and "--matrices" are unrecognised options? 
is that expected for linux?

**Comment by vdemichev** [comment]
No, not expected. Please try the latest version, it should print 'DIA-NN 1.7.11".

**Comment by Naadir-Ganief** [comment]
okay, thanks

**Comment by Naadir-Ganief** [comment]
Thanks, all sorted
appreciate your help
