### ISSUE TITLE
Alignment between RT (in raw) and iRT (in spectral library)

### ISSUE THREAD

**Issue by progistar** [vdemichev/DiaNN#513]
Hello,

I am Seunghyuk Choi from Hanyang University.
I have a quick question about how to align between RT (from RAW) and iRT (from spectral library).
In the manuscript, the author says that "performing retention time alignment using endogenous peptides."
1) what is the list of endogenous peptides?
2) if there are no endogenous peptides in a spectral library, how DIA-NN deals with the alignment?

Thanks for your efforts, in advance.

**Comment by vdemichev** [comment]
It just identifies a number of peptides without using the RT information. Then aligns library and observed RTs for these peptides. And uses this transform to predict RTs for other peptides.

**Comment by progistar** [comment]
@vdemichev Thanks very much!
