### ISSUE TITLE
Semi Tryptic Support

### ISSUE THREAD

**Issue by Naadir-Ganief** [vdemichev/DiaNN#52]
Hi, 

Does Diann have some support for semi-tryptic peptides?

I have a library constructed(using iprohet and spectrast) from DDA runs, that contain semi-tryptic peptides. 
When reanotating the fasta for protein inference, --cut-after KR is set. My understanding is this setting will negate semi-tryptic peptides being associated with any protein groups?

if so, can i set anything to allow for the use of semi-tryptic peptides in protein grouping?

Thanks

**Comment by vdemichev** [comment]
Hi, yes, in general peptides with arbitrary sequence are supported, however reannotation (which simply matches proteins to the peptides founds in the library) does indeed require correct digest to be specified, and it's currently not possible to specify a semi-tryptic digest for this. But reannotation is only necessary if the library is not properly annotated by the search engine that generated it. In that case the only solution would be to annotate manually in R/Python.

Vadim

**Comment by vdemichev** [comment]
P.S. If there protein IDs associated with the peptides in the library, no need to select 'reannotate', DIA-NN will correctly pull information from the FASTA based on these ids provided.

**Comment by Naadir-Ganief** [comment]
okay, thanks.

That clears things up and helps a lot
