### ISSUE TITLE
Library RTs in minutes seems to be interpreted as iRT values the output tsv-report

### ISSUE THREAD

**Issue by MarcIsak** [vdemichev/DiaNN#53]
Hello, 

I have used DIA-NN 1.7.11 in windows through the commandline, to run a DIA analysis. The library I supported was in TSV-format (as given by OpenSwathAssayGenerator) and in the _NormalizedRetentionTime_ column of that library I had retention times in minutes (predicted). However, when I look at the output TSV-file from DIA-NN, it seems like the retention times in the library are interpreted as iRT values in the report. Since this is not the case (unless iRT values by chance happens to be soewhat equal to RT in minutes), I wonder if there is any way of instructing DIA-NN that the library retention times are in minutes? 

By the way, I really like DIA-NN, it is impressively fast and it can handle large libraries without any problems. 

Best,

Marc

**Comment by vdemichev** [comment]
Hi Marc,

DIA-NN will always call reference retention times 'iRT' in its report, regardless of how these are encoded in the library. This is just for convenience (many libraries do use iRT scale) and does not affect functionality.

Best wishes,

Vadim

**Comment by MarcIsak** [comment]
Aha, thanks for the clarification. So I guess the RT column in the TSV-report is the actual retention time in minutes for the MS/MS scan where the library precursor was identified? I also noticed that the report has columns for predicted RT in minutes as well as predicted iRTs. 

Best,

Marc

**Comment by vdemichev** [comment]
Yes, RT is in the same units as in the raw file - that's usually minutes. Predicted RT and iRT are calculated from library reference retention times and observed retention times in the data, respectively, using an alignment between these which DIA-NN calculates for each run.

Vadim
