### ISSUE TITLE
Contradictory information on decoys

### ISSUE THREAD

**Issue by kevinkovalchik** [vdemichev/DiaNN#541]
Hello,

We are experimenting with libraries that have enriched sequence motifs in them. These motifs are disrupted by the decoy generation approach used by DIA-NN such that the target and decoy libraries no longer "look similar". Thus, we are somewhat concerned about what is happening with the target-decoy competition when using these libraries and we would like to compare DIA-NN's decoy generation with some libraries built using custom decoys that contain the same motif as the targets.

According to the spectral library format indicated in the readme, this is possible (though advised against):
- **Decoy** - Indicates whether the peptide is a decoy. If there are decoy peptides in the library, DIA-NN uses these and does not generate its own decoys. It is strongly recommended **not** to include any decoy peptides in the library.

However, according to issue #310, this is not possible:
> Please don't use external decoys with DIA-NN, it always generates decoys automatically.

#310 refers to a protein database, so it isn't clear to me if this also applies to spectral libraries or if we can supply our own decoys in our spectral library for testing purposes.

Can we provide decoys in our library, or is DIA-NN going to treat them as part of the target library and generate decoys for both target and decoy entries?

Best regards,
Kevin

**Comment by vdemichev** [comment]
Hi Kevin,

'motifs are disrupted' - how does this manifest?
It is possible for DIA-NN to be supplied with the decoys in the library, just not recommended for 99.99% applications.

Best,
Vadim

**Comment by kevinkovalchik** [comment]
Hi Vadim,

Thanks for clearing up my confusion regarding the decoys. I'll close this issue, and if we decide to look into using custom decoys and have problems, I'll open another.

To answer your question, there are certain amino acids enriched at the positions that DIA-NN mutates, so the decoys end up having different motifs. But truly bad spectra won't look like the targets or decoys, so it might not actually matter.

Best,
Kevin
