### ISSUE TITLE
Segmentation fault on Linux compiled version

### ISSUE THREAD

**Issue by markcelo** [vdemichev/DiaNN#55]
Dear Vadim,

I have compiled diann in CentOS and I keep getting crashes at the end of a run, after sample analysis and during the stage of preparing protein groups and output tables.
Crashes can be avoided if certain samples are removed from the analysis, but the bottom line reason is unknown, **is this something you have heard of?** .

The compilation method seems to play a factor, at least partly. Compilation **without** "-static" flag gives so far the best executable, which works in most cases, yet still crashes with some samples. Keeping the "-static" flag results in an executable that crashes in all tests, and always at the final stage of building protein groups.  Lastly for completeness,  the windows version from the repository does not crash with any of these samples.

Fingers crossed !
Marcelo

**Comment by vdemichev** [comment]
Hi Marcelo,

Segmentation fault on Linux has been reported before https://github.com/vdemichev/DiaNN/issues/23
I will try analyse different files and see if this can be reproduced.

Best wishes,

Vadim

**Comment by vdemichev** [comment]
Would you be able to share the spectral library with which it crashes? (in .speclib format)

**Comment by markcelo** [comment]
I need to double check but hopefully yes . 
Just for understanding, why do you suspect on the library rather than the sample files themselves? Just to mention that the segmentation fault error happens only at the end,  **after** all individual samples get processed.   Here I copy the stdout from console. The error here is exactly the same happening consistently.

[7:35] Cross-run analysis
[7:35] Reading quantification information: 13 files
[7:36] Quantifying peptides
[7:40] Assembling protein groups
./diann_call_linux.sh: line 10: 78675 Segmentation fault      (core dumped) ./library/diann-linux_1711_recompiled --f MYSAMPLE_8_B.raw.dia --f MYSAMPLE_8_A.raw.dia --f MYSAMPLE_8_C.raw.dia --f MYSAMPLE_7_10.raw.dia --f MYSAMPLE_7_09.raw.dia --f MYSAMPLE_7_08.raw.dia --f MYSAMPLE_7_07.raw.dia --f MYSAMPLE_7_06.raw.dia --f MYSAMPLE_7_05.raw.dia --f MYSAMPLE_7_04.raw.dia --f MYSAMPLE_7_03.raw.dia --f MYSAMPLE_7_02.raw.dia --f MYSAMPLE_7_01.raw.dia --lib library/mylib.tsv.speclib --threads 30 --verbose 1 --out reportUX.tsv --out-gene report-genesUX.tsv --reannotate --fasta library/myfasta.fasta --met-excision --cut-after KR --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --unimod4 --peak-center --mass-acc-cal 30 --top 6

**Comment by vdemichev** [comment]
This used to happen when protein annotation is missing in the library. I don't think that's the reason here, but might be something similar. Also, it would be easier for me to track the bug, if it's library-specific.

**Comment by markcelo** [comment]
Thanks Vadim, that last guess might be indeed related. In any case I am providing the library through a separate channel (more on email ) . Is speclib essential or could it be the text format?

**Comment by vdemichev** [comment]
Hi Marcelo, please send either, just thought .speclib would be easier to email due to lower file size.

**Comment by markcelo** [comment]
Hi Vadim, 

Maybe to rule out issues related to compilation, would it be possible to provide the versions of dependencies you used in your tests? . I am thinking in particular on glibc , but if rather easy to dump all dependencies that would be great. 

BEst 
Marcelo

**Comment by vdemichev** [comment]
Hi Marcelo,

if not for the glibc licensing restrictions, I would just distribute a statically compiled binary. But GPL does not allow this... What you can always do though is compile it with static linking on one machine and then use on another.

Best wishes,

Vadim

**Comment by ewail** [comment]
@markcelo 

Hi Marcelo, It is recommended to use conda to compile DIA-NN (gcc > 5.0, updating gcc or system should solve the problem. 
). #23 The possible cause is that some of the system's library files are **Not compatible**. 
I solved this dependency problem with conda, you can try the following command, maybe it can help you too：`conda create -n gcc -c tsnyder gcc_linux-cos6-x86_64 gxx_linux-cos6-x86_64` .

Best wishes,
Hao

**Comment by markcelo** [comment]
Hi Hao , 

Thanks for the tip. Actually I have been compiling via conda (Centos7/8), but the **-static** flag still results in no compilation. 

The workaround without static linking works well though, except that prot inference has to be switched off.

**Comment by ewail** [comment]
@markcelo 

Hi Marcelo. I have been compiling 1.7.12 with -static flag (gcc9): 
https://github.com/ewail/DiaNN/releases/tag/1.7.12

Best wishes,
Hao
