### ISSUE TITLE
Some questions before starting

### ISSUE THREAD

**Issue by ttessie2** [vdemichev/DiaNN#552]
Hello, 
I'm just getting started with DiaNN for the first time and I am unfamiliar with processing DIA data at the moment. I have a few questions I'd like to ask before getting started, just so I'm clear.
1) I would like to run DiaNN using an insilico predicted spectral library. Do I need to include decoy sequences in the FASTA database file or is that built in? 
2) I also have DDA data for building a spectral library. Assuming I generate the DDA speclib in MSFragger, do I need to include decoy sequences at that step or are decoys incorporated while processing everything in DiaNN.

**Comment by vdemichev** [comment]
1. No, don't include decoys
2. No, decoys should never be included

**Comment by ttessie2** [comment]
Great, thank you! Looking forward to getting started with DiaNN!
