### ISSUE TITLE
Deep learning functionality for Linux version?

### ISSUE THREAD

**Issue by markcelo** [vdemichev/DiaNN#56]
Hi Vadim, 

Regarding lib free search for library construction,  is in your roadmap to provide the Deep learning functionality for the linux version ? 

MArcelo 

ps. Apologies for filing so many issues at once, this all comes from a period of testing and observations.

**Comment by vdemichev** [comment]
Hi Marcelo,

It might be possible to implement this, but I don't expect to do that in the near future.

Best wishes,

Vadim
