### ISSUE TITLE
DIA PASEF data analysis on DIA-NN

### ISSUE THREAD

**Issue by Wenhhao** [vdemichev/DiaNN#57]
Dear Vadim,

I tried to analyze DIA PASEF data on DIA-NN 1.7.11 by CentOS 6.8 command line, but all the efforts failed. 
First I directly added `analysis.tdf` file under `.d` folder in DIA-NN, and the command is `diann --f FILE --lib SPECLIB --threads 20 --verbose 1 --out "*.tsv" --out-gene "*.genes.tsv" --qvalue 0.01 --out-lib "*.lib.tsv" --gen-spec-lib --fasta FASTA --met-excision --individual-mass-acc --individual-windows --rt-profiling --pg-level 1`, but the process stopped with a waning: `invalid raw MS data forma`.

Then, I tried to convert the `.d` data to `.mzML` using [Mobi-DIK](http://openswath.org/en/latest/docs/mobi-dik.html#) (an extension of the OpenSWATH workflow), after `.mzML` used DIA-NN stopped with another error as `No index list offset found. File will not be read`. 

Finally I used msConvert (provided by [ProteoWizard](http://proteowizard.sourceforge.net/index.html)) to convert the raw file to `.mzML` format, but DIA-NN emerged another error as `No MS2 specrea: aborting`.

Is the command that I entered right? And whether `.tdf` format can be directly loaded into DIA-NN now as #27 ? If not, which format is work, and which software/script could be able to convert the raw files?

Best wishes,
Hao

**Comment by vdemichev** [comment]
Hi Hao,

diaPASEF in DIA-NN is currently alpha-stage and Windows-only. DIA-NN does
not support diaPASEF on Linux, neither .tdf nor .mzML obtained from .tdf.
You can however convert .tdf to .dia using DIA-NN on Windows and then do
the analysis of these .dia files on Linux.

Best wishes,

Vadim

**Comment by Wenhhao** [comment]
Dear Vadim,

Thanks for your prompt reply. We have installed a DIA-NN 1.6.0 on Windows and a DIA-NN 1.7.11 on Linux. But I am not sure whether version 1.6.0 can be used for DIA PASEF data analysis. That's why I choose the one on Linux finally.

Does version 1.6.0 support on converting `.tdf` to `.dia`? Moreover, which version of DIA-NN can be used for DIA PASEF data analysis, so that we could make a comparison in operating speed between DIA-NN on different servers?

Best wishes,
Hao

**Comment by vdemichev** [comment]
1.6.0 does not support diaPASEF. In general, I recommend to always use the latest version (1.7.11, also the next one will be released fairly soon), as it's very substantially better than 1.6.0. And you can always install multiple DIA-NN versions on the same PC.

Vadim

**Comment by Wenhhao** [comment]
Thanks, I will have a try.
