### ISSUE TITLE
differential expression analysis

### ISSUE THREAD

**Issue by Aintzane99** [vdemichev/DiaNN#574]
Hello, 

I am currently processing the output of DIA-NN for the first time. My goal is to perform differential expression analysis (DEA) on the proteins from the latter output. From what I understood from the README.md, only the MaxLFQ protein intensity columns should be employed for downstream analyses. I looked up several tools for the DEA but I'm not exactly sure how i could fit  the DIA-NN output characteristics (main report table) to the different input requirements of each software. My question here is if you have any reccomendations on the methods that I could use to process the DIA-NN output for DEA (maybe DEP, msqrob2, MSStats...?), or if you would consider additional processing steps on the main report table before jumping into DEA (such as some kind of filtering or normalization, although the README.md file claims that the MaxLFQ intensities have been normalized).  

Many thanks!!

Aintzane

**Comment by vdemichev** [comment]
Hi Aintzane,

Yes, only PG.MaxLFQ or Genes.MaxLFQ or Genes.MaxLFQ.Unique.
We ourselves usually use custom scripts and simple tests like t-test or Wilcoxon test. Also, diann R package can help transforming the data to the 'wide' format (diann_matrix function).

Best,
Vadim

**Comment by Aintzane99** [comment]
Hi Vadim,

Thank you so much for your help! 

For anyone with the same issue, I was able to process the DIA-NN output with DEP and msqrob2.

Best,

Aintzane
