### ISSUE TITLE
Recommended cores and RAM 

### ISSUE THREAD

**Issue by jessegmeyerlab** [vdemichev/DiaNN#590]
Sorry if I missed this info somewhere else. I searched the documentation and the issues for recommendations for cores and RAM to get library free search done faster. Asking because I'm getting our IT to setup a VM. I think I saw you tweet something about the best number of cores and RAM?

**Comment by vdemichev** [comment]
Hi Jesse,

16+ cores (ideally with high core performance) and 128Gb RAM are good.

Best,
Vadim
