### ISSUE TITLE
Which DIA isolation window setups are supported for library free search?

### ISSUE THREAD

**Issue by chhh** [vdemichev/DiaNN#594]
Hi,
I could not find any description of which isolation window setups are supported by DIA-NN.
The closest I've found is [Raw data formats -> Technology support](https://github.com/vdemichev/DiaNN#raw-data-formats) section, but it doesn't go into details.

Could you please confirm which configurations out of the list are OK to process with DIA-NN 1.8.1?

1) All isolation windows are of same size (e.g. 25Da), no overlaps (I guess this is called SWATH in "Technology support")
2) All isolation windows are of same size (e.g. 25Da), with overlaps
3) Isolation windows have different widths, stay the same over time, no overlaps (is this referred to as DIA in "Technology support"?)
4) Isolation windows have different widths, stay the same over time, with overlaps
5) Isolation windows have different widths and change over time, they cover the same overall mz range, and the number of windows in each cycle stays the same e.g.:
    At t0 the set of windows can be [300-400], [400-600], [600-1000]
    At t1 the set of windows can be [300-500], [500-700], [700-1000]
6) Like 5, but the number of windows can change over time and the overall mz range that the windows cover also changes

Thank you for making a great tool!

**Comment by vdemichev** [comment]
Basically, anything is supported, except MSX and multi-CV FAIMS (the latter is supported if you split the files using some third-party tool). All scenarious you mentioned are supported.

Best,
Vadim

**Comment by chhh** [comment]
Thank you for clarification!
