### ISSUE TITLE
It is better to support maxquant or proteome discoverer software directly when importing the library

### ISSUE THREAD

**Issue by apologize965** [vdemichev/DiaNN#60]

**Comment by vdemichev** [comment]
It's possible to import these into Skyline and I think someone reported that it's possible to export a "transition list" from Skyline that DIA-NN can read. For example, here http://openswath.org/en/latest/docs/skyline.html it's mentioned that Skyline can export libraries to the OpenSWATH-compatible format, which DIA-NN also supports. I have not done this myself but plan to try in the future.

**Comment by apologize965** [comment]
@vdemichev Thank you so much, dear vdemichev. I have one more question to disturb you. If we use thermo's obitrap instrument, we will find that if we run a 100 m/z GPF, it is difficult to create a 4m / Z width window due to the scanning speed limitation of this type of instrument. I read a literature, "Generating high quality libraries for DIA MS with empirically corrected peptide predictions". They adopt the SIM acquisition mode and set the isolation window to 4Da, but I find that DIA-NN does not support SIM data. Will you consider improving this situation when using SIM acquisition mode to establish library? Thank you very much.

**Comment by vdemichev** [comment]
OK, first, making spectral libraries out of MaxQuant output has now been implemented in the development version of DIA-NN. If you wish, you can email me and I will send it to you.

About GPF on Thermo. This is a nice example of such a dataset, which is fully supported by DIA-NN https://www.nature.com/articles/s41467-018-07454-w. I haven't looked at the data from that paper you mentioned, but their Methods section does not mention the SIM mode and most likely DIA-NN support that dataset too. Please give it try and let me know if it does not work.

Vadim

**Comment by apologize965** [comment]
Hi vdemichev, thank you for your reply. I will email you immediately and provide you with the information of the file I mentioned. I hope it can help you
