### ISSUE TITLE
Effect on mass / MS1 accuracy on protein quantification / abundance

### ISSUE THREAD

**Issue by pchirania** [vdemichev/DiaNN#603]
Hello,

I am new to DIA-NN and have a basic question about how the protein group abundances or quantifications change as a function of mass and MS1 accuracy settings for a diaPASEF run.

In the plot below, I ran DIA-NN on the same file by just changing the MS1 and mass accuracy to either 15 or 20 ppm from 0ppm and plotted the resulting abundance ranks in each run for the identified protein groups against each other. 
Param1 = mass and MS1 accuracy left at 0. 
Param 4 = mass and MS1 accuracy set to 15ppm 
Param 5 = mass and MS1 accuracy set to 20ppm
Param 9 = mass and MS1 accuracy left at 0 with some other parameters changed.

I am seeing differences in number of identified protein groups by changing the mass/MS accuracies, which would be expected. However, while some variation in the abundance ranks are expected, I am observing very vast differences in abundances of some protein groups. For example, some proteins which are top abundant (rank <100) in one case are quantified to be relatively low abundant (rank >1000) in another case. 

Can you please help as to which setting to use and why are there such large differences for some proteins?

![image](https://user-images.githubusercontent.com/35818015/215534714-3c6ee470-0e1a-40aa-ac55-134ccebf6058.png)

![image](https://user-images.githubusercontent.com/35818015/215534745-9306eca6-0ab5-4026-a58c-0b6bb0ddb362.png)

![image](https://user-images.githubusercontent.com/35818015/215534783-651efbe3-0898-4d2b-8457-dca245a740ec.png)

![image](https://user-images.githubusercontent.com/35818015/215534807-27404783-14d7-4f07-b265-17f7fe412cff.png)

Let me know if you need more information or clarification. Thank you and looking forward to hearing back!

Best,
Payal

**Comment by vdemichev** [comment]
Hi Payal,

Yes, this kind of result is expected. Label-free protein quantification is designed to compare the quantities of a protein between different runs in the experiment, that are supposed to be acquired with the same LC-MS settings and analysed with the same DIA-NN parameters. Of course, LC-MS performance can drift and this can then necessitate batch correction. But the quantities obtained with different settings just cannot be compared. Even the quantities obtained by running DIA-NN with the same settings on different sets of files cannot be compared, unless you follow special steps for incremental analysis (described in DIA-NN docs). Specifically in the case above, what happens is that different peptides are used to quantify the same proteins when analysed with different settings. 

Best,
Vadim

**Comment by pchirania** [comment]
Hi Vadim,

Thank you for the clarification, it is very helpful!! I have 2 follow up questions:

1. In the example here, I did see that different peptides were being used to provide the quantity of proteins - as such new peptides were being identified /quantified for a protein group with the change in mass accuracy settings. For timsTOF data or other in general, what mass /ms1 accuracy would you recommend using then? Should I use the recommended accuracy by DIANN on few files?

2. What type batch correction would you recommend? And should it be performed at the protein group level?

Thanks again,
Payal

**Comment by vdemichev** [comment]
1. For timsTOF both mass accuracies are ideally set in the rane 10-15ppm.
2. Please see our covid papers for an example. We did on precursor level. Can also do on the protein level if still batch effects remaining and/or include batch info as covariates in statistical models.

Best,
Vadim

**Comment by pchirania** [comment]
Hi Vadim,

Thank you so much for the clear response, its very helpful! 

Best,
Payal
