### ISSUE TITLE
Combining outputs 

### ISSUE THREAD

**Issue by ttessie2** [vdemichev/DiaNN#606]
I'm analyzing some PPI  data that I processed in two ways. 1) fraggerDIA with a hybrid speclib generated from DDA and DIA runs and 2) DIA data was processed in DIANN using an insilico library. Do you recommend a way to combine these results? Is this wise? Or should I just present data from each processing pipeline separately?

**Comment by vdemichev** [comment]
No, I don't think makes sense to combine.

**Comment by ttessie2** [comment]
Thank you.
