### ISSUE TITLE
Match between runs (MBR)

### ISSUE THREAD

**Issue by jessegmeyerlab** [vdemichev/DiaNN#619]
In the popup help for MBR it says that it just uses the spectral library from the first search for the second analysis. That makes it sound like it just tries again to get ids without forcing integrations.  I just want to check that its not doing something like the MBR definition from maxquant or ionquant in trying to integrate where there isn't necessarily an ID in other runs?

**Comment by vdemichev** [comment]
Yes, it does exactly that.

**Comment by st-pf** [comment]
hello, 
I have an additional question to this: 
is there a way to discriminate between prot IDs found in the first search and those found via MBR, e.g. is there an indicator added to those in one of the output files of DIA-NN? 
thank you in advance
s

**Comment by vdemichev** [comment]
No, the second search (MBR) affects all q-values of all precursors and proteins.

**Comment by kwebber3** [comment]
@vdemichev What are the first_pass matrices? Could I consider these pre-MBR identifications?
