### ISSUE TITLE
Mass accuracies

### ISSUE THREAD

**Issue by andrewlai** [vdemichev/DiaNN#621]
Great software.

I am analysing some files acquired on a  TripleTOF 5600 and ran some files through DIA-NN.  It recommended a range of values with the MS1 mass accuracy (18,16,21,24 ppm) and Optimised mass accuracy (MS2, 29, 32, 23, 37 ppm).

Should I take the average values and fixed the MS1/MS2 values? Or set it to something like 20/20 ppm? or is there a problem with the data acquisition itself?

Thanks

**Comment by vdemichev** [comment]
Yes, taking approximately the average makes sense. There's no problem, these values are realistic for 5600.
