### ISSUE TITLE
MSX-DIA supported in 1.8.1?

### ISSUE THREAD

**Issue by k-p4** [vdemichev/DiaNN#628]
Hi Vadim,

Thanks very much for the tool. I was just seeing the release notes for DIANN 1.8.1 and noticed multiplexing is supported. Just want to ask if 
1) does this mean the same as an MSX-DIA experiment or rather means multiplexing through isobaric labeling (TMT etc)
2) if MSX-DIA, are there any recommendations for the number of ions one should specify to multiplex in the method?

Thanks,
Karl

**Comment by vdemichev** [comment]
Hi Karl,

No, MSX-DIA is not supported.

Best,
Vadim

**Comment by k-p4** [comment]
Thanks Vadim. Sorry for the confusion
