### ISSUE TITLE
Retention time reporting

### ISSUE THREAD

**Issue by LeeSCantrell** [vdemichev/DiaNN#638]
Hi Vadim, 

Thank you for the nice software that you have developed. I have been working with it for a while and I noticed that in 1.8.1, there is inaccurate reporting of the retention time start and stop - at least according to prior releases. Can you help me to understand what changed between 1.8 and 1.8.1 and comment on how to get equivalent results to calculating length of elution profile (RT.Stop - RT.Start) in 1.8.1?

I am able to produce this difference in both 1.8 and 1.8.1 with several different searches. Most precursors are measured with the same RT length except for the most abundant which have ~2x the retention time calculated. 

As a side feature request, is it possible to request an integer of the number of scans used in quantitation for a given precursor? 

Thanks!

Lee

**Comment by vdemichev** [comment]
Hi Lee,

The length will only depend on the precursor if you analyse in high accuracy quant mode.

Best,
Vadim

**Comment by LeeSCantrell** [comment]
Hi Vadim,

Thank you. Does this mean that peak integration is only done, for all precursors, on the middle-most 4 scans (unless it reaches 8)? Also, is scoring of peptides prior to FDR control done with the correlation scores generated exclusively from those 4 scans or from the entirety of the precursor elution width? I.e., is the score distribution of long eluting peptides made more homogenous to the score profile of short eluting peptides by filtering the tails of the peak? 

Is it possible to get an RT.Length column in the final report? I find this useful in diagnosing instrument method conditions. 

Thank you,

Lee

**Comment by vdemichev** [comment]
The peak integration window is proportional to the 'Scan window', in high-precision mode, yes.
No, scoring for FDR is not affected by this setting.
In theory yes, but not implemented yet.

**Comment by LeeSCantrell** [comment]
Hi Vadim, two quick questions
1) is the reported rt start and stop in 1.8 the FWHM start and stop or width start and stop? 
2) is quantitation based on the sum of peak heights in 1 scan, extrapolated to intensities in neighboring windows, or is the integral of each peak calculated across the entire integration range? In High precision mode this would then be the intensity extrapolated to measured peakwidth/shape and in high accuracy mode would be unextrapolated, if I understand things correctly for 1.8.1.

**Comment by tomthun** [comment]
> Hi Vadim, two quick questions
> 
> 1. is the reported rt start and stop in 1.8 the FWHM start and stop or width start and stop?
> 2. is quantitation based on the sum of fragment peak heights in 1 scan, extrapolated to intensities in neighboring windows, or is the integral of each fragment peak calculated across the entire integration range? In High precision mode this would then be the intensity extrapolated to measured peakwidth/shape (MS1 profile?) and in high accuracy mode would be unextrapolated, if I understand things correctly for 1.8.1.

I would also like to know the answers :)
