### ISSUE TITLE
GUI bug on display

### ISSUE THREAD

**Issue by AFOXCOW** [vdemichev/DiaNN#64]
latest version of diann is installed on windows 10.
but somewhere on the GUI are covered, making setting parameters difficult.(precursor ion generation panel)
here is the screenshot.
![屏幕截图 2020-11-23 142705](https://user-images.githubusercontent.com/25144365/99934105-ffcf0100-2d97-11eb-8e65-910cd1161d04.png)

**Comment by vdemichev** [comment]
Hi, yes, I noticed that some users have this display problem, probably some Windows settings. Maybe some font is missing in the system? I don't know what exactly causes it, cannot fix it for now, but will look into this.

Vadim
