### ISSUE TITLE
Generating spectral library only with FASTA file (no data files)

### ISSUE THREAD

**Issue by CelieDs** [vdemichev/DiaNN#652]
Hi Vadim, 

First I would like to thank you for the great tool! 
I am currently using the command line version of DiaNN to incorporate it in a workflow for an automatic processing of my data and I was wondering if it could be possible to generate a spectral library based on a provided FASTA file, without providing any data files? 

Thanks in advance for you reply, 

Best Regards

Célie

**Comment by TTCooper-PhD** [comment]
Here is some code I have written for running DIA-NN from a python script. 

`def generate_spectral_library(dia_nn_exe_path, fasta_file):
    """
    Generates a spectral library from a given FASTA file using DIA-NN.

    Args:
        dia_nn_exe_path (str): Path to the DIA-NN executable.
        fasta_file (str): Path to the FASTA file.

    Returns:
        str: Path to the generated spectral library file ('spec-lib-predicted.dlib').
    """
    if not os.path.exists(fasta_file):
        print(f"FASTA file '{fasta_file}' not found.")
        return ""

    output_file = "spec-lib-predicted.dlib"

    cmd = f"{dia_nn_exe_path} \
    --lib \"\" \
    --threads 30 \
    --verbose 3 \
    --out \"report.tsv\" \
    --qvalue 0.01 \
    --matrices \
    --out-lib \"report-lib.tsv\" \
    --gen-spec-lib \
    --predictor \
    --fasta \"{fasta_file}\" \
    --fasta-search"

    # Execute the command
    subprocess.run(cmd, shell=True, check=True)

    if os.path.exists(output_file):
        return list(os.path.abspath(output_file))
    else:
        print("Spectral library file not found.")
        return ""`

**Comment by vdemichev** [comment]
Hi Celie,

Yes, it's possible. Please try this in the GUI and then just copy-paste the command it prints in the log to the command line script.

Best,
Vadim

**Comment by CelieDs** [comment]
Hi Vadim,

Thank you for your prompt reply and the solution described. It worked perfectly! :)

Best Regards,

Célie
