### ISSUE TITLE
conversion from WIFF to .dia format stalls

### ISSUE THREAD

**Issue by ftwkoopmans** [vdemichev/DiaNN#66]
DIA-NN gets stuck while trying to convert WIFF files to the .dia format. After I see "Loading run <filename>" in the console, there is quite a lot of CPU activity which stops after a few minutes and then nothing else happens for hours (so I assume the process is stuck). Running the process as administrator doesn't help. The raw data I'm trying to convert is available on https://www.ebi.ac.uk/pride/archive/projects/PXD002952 . I'm using 64bit Windows 10 and have installed DIA-NN 1.7.12 in the ProteoWizard (64bit with vendor support) folder, this is my Windows PowerShell log;

```
PS C:\temp> & 'C:\Program Files\ProteoWizard\ProteoWizard 3.0.20328.25a49f6da\diann.exe' --verbose 5 --threads 22 --convert --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_008.wiff --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_009.wiff --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_010.wiff --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_011.wiff --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_012.wiff --f C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_013.wiff
DIA-NN 1.7.12 (Data Independent Acquisition by Neural Networks)
Compiled on Oct  1 2020 21:36:38
Current date and time: Tue Nov 24 02:00:57 2020
CPU: AuthenticAMD AMD Ryzen 9 3900X 12-Core Processor
SIMD instructions: AVX AVX2 FMA SSE4.1 SSE4.2 SSE4a
Logical CPU cores: 24
Thread number set to 22
MS data files will be converted to .dia format

6 files will be processed
[0:00] Loading run C:\temp\HYE124_TTOF6600_64var_lgillet_I150211_008.wiff
```

**Comment by vdemichev** [comment]
Hi Frank,

I've recently identified a bug in the .wiff-reading module of DIA-NN which can lead to this (basically, one of the threads reading the file gets locked). The problem manifests, rarely, on specific systems. There's a simple fix, I will include it in the next DIA-NN version. Meanwhile, please email me and I will send you an updated version of DIA-NN.Wiff.dll, placing it in DIA-NN folder will solve the problem. Alternatively, can either (i) convert the file using a single thread or (ii) convert to .mzML using MSConvert.

Best wishes,

Vadim
