### ISSUE TITLE
Settings for analysing mDIA samples

### ISSUE THREAD

**Issue by Maithy15** [vdemichev/DiaNN#660]
Dear Vadim,

I have some mDIA samples and tried using DIA-NN version 1.8.1 available from github for the analysis. Can this version deal with dimethyl labeling? 

Should I set the --fixed-mod setting as {--fixed-mod Dimethyl, 28.0313, nK} or as {--fixed-mod Dimethyl, 28.0313, nK, label}.

Thanks
Maithy

**Comment by vdemichev** [comment]
Hi Maithy,

I think M Mann and colleagues used 1.8.1, so should work as described in their preprint?

Best,
Vadim

**Comment by Maithy15** [comment]
Dear Vadim,

Thanks for your quick response. It seems that they did not generate a predicted library in DIA-NN. When I try to predict the library I get the following error.

[0:00] Loading FASTA D:\Analysis\FASTA\Homo_sapiens\20221214_UP000005640_9606_human.fasta
[0:11] Processing FASTA
[0:18] Assembling elution groups
[0:23] 4364281 precursors generated
[0:23] Gene names missing for some isoforms
[0:23] Library contains 20566 proteins, and 20339 genes
[0:23] Encoding peptides for spectra and RTs prediction
WARNING: skipping 4364281 precursors, unrecognised modifications? If these precursors are important, consider forcing prediction of spectra/RTs/IMs for these precursors anyway, using the --strip-unknown-mods option
[0:24] Predicting spectra and IMs
WARNING: no valid peptides; all the peptides provided have unrecognised modifications?
[0:24] Predicting RTs
WARNING: no valid peptides; all the peptides provided have unrecognised modifications?
[0:24] Decoding predicted spectra and IMs
[0:24] Decoding RTs
[0:24] Saving the library to D:\Analysis\FASTA\Homo_sapiens\DIA-NN-3plex_library\3plex_library.predicted.speclib
[0:28] Initialising library

Here are the command line settings

--fixed-mod Dimethyl, 28.0313, nK
--channels Dimethyl, 0, nK, 0:0; Dimethyl, 4, nK,4.0251:4.0251; Dimethyl, 8, nK, 8.0444:8.0444
--original-mods
--peak-translation
--ms1-isotope-quant
--report-lib-info
--mass-acc-quant 10.0

Should I do anything differently? Should I simply load the predicted library without the modifications and then just put the modifications in the command line, is this what --strip-unknown-mods option do?

Thanks
Maithy

**Comment by Maithy15** [comment]
Dear Vadim,

It seems first generating the library by using --strip-unknown-mods and then using that library have worked. But I cannot distinguish between different channels. Where Can I get that info?

Thanks
Maithy

**Comment by vdemichev** [comment]
Hi Maithy,

The Precursor.Id column should contain the channel info.
If not, how does the log look like?

Best,
Vadim

**Comment by Maithy15** [comment]
Dear Vadim,

Thanks for the quick reply. I only see Dimethyl in the precursor.id column, it does not say which dimethyl channel. I have attached the log for you.

This is how the precursor.id column look

(Dimethyl)AAAAAWEEPSSGNGTAR2
(Dimethyl)AAAAAWEEPSSGNGTAR2
(Dimethyl)AAAAAWEEPSSGNGTAR3
(Dimethyl)AAAAAWEEPSSGNGTAR3
(Dimethyl)AAAAAWEEPSSGNGTAR4
(Dimethyl)AAAAAWEEPSSGNGTAR4

[report.log.txt](https://github.com/vdemichev/DiaNN/files/11269421/report.log.txt)

Thanks
Maithy

**Comment by vdemichev** [comment]
--channels command not used

**Comment by Maithy15** [comment]
is this correct? "{--channels Dimethyl, 0, nK, 0:0; Dimethyl, 4, nK, 4.0251:4.0251; Dimethyl, 8, nK, 8.0444:8.0444}"

**Comment by Maithy15** [comment]
The space is an issue, I should not leave space within the channel info! It seems to work now thanks!

**Comment by vdemichev** [comment]
The options quoted here https://github.com/vdemichev/DiaNN/issues/660#issuecomment-1512782437 look correct
