### ISSUE TITLE
Match Between Runs Library Search

### ISSUE THREAD

**Issue by LeeSCantrell** [vdemichev/DiaNN#668]
Hi Vadim, thank you for being so on top of answering questions in the community. It's wonderful to have such great engagement from developers. 

1) During a normal MBR lfq quant search, my understanding is that a library is generated and then used to search the data again in entirety. When all data is loaded the second time with this new library, are all data searched against only the target library, the target library with the mutant decoy peptides, or the target library combined with the best empirical spectra of decoy matched peptides?

2) Could you share the list of contaminant proteins such as CONP12035_HUMAN? I take it that there is a fasta list added by default to all searches. Is there a way to turn this off?  

3) Does an inward facing flag exist to add the decoys to your tsv export libraries? I feel that this may give the best chance for DIANN be efficiently compared to other methods. I realize there is the 0:1 method in tsv file that can take an existing decoy containing report, but I want to integrate diann's exact decoys for reproducibility.

**Comment by vdemichev** [comment]
Hi Lee,

1. Decoys are always generated on the fly for the specific library at the moment when it's loaded into memory. So there's effectively no connection to the first pass of MBR.
2. DIA-NN just searches against the FASTA you provide, no extra stuff is added.
3. As far as I remember - no. For comparison, I would suggest to use two-species searches (e.g. searching human samples against human + E.coli database, or against human-Arabidopsis library).

Best,
Vadim
