### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nuan604** [vdemichev/DiaNN#687]
Dear DiaNN developer,

We are the MS group in NIH. We want to package the DiaNN in our pipeline for DIA MS data analysis. And this is only used for academic studies. If possible,  could we publish this pipeline and make more people to know DiaNN is the most suitable software for DIA-MS data analysis? Thanks

**Comment by vdemichev** [comment]
I would suggest to check the DIA-NN license packaged in its distribution, to see what can/cannot be done.
