### ISSUE TITLE
diann_1.8.1.rpm contains version 1.8, not 1.8.1

### ISSUE THREAD

**Issue by jalew188** [vdemichev/DiaNN#689]
Hi Vadim,

I currently tried diann linux, and I found that diann in diann_1.8.1.rpm is in version 1.8, not 1.8.1. In the log file, the compiled time was in 2021, not 2022. I also tried .deb, and this contains the correct version. I did not test diann_1.8.1.tar.gz yet. 

Hope it helps if anyone encountered some issues when using rpm in linux.

Best,
Feng

**Comment by vdemichev** [comment]
Hi Feng,

Thank you for spotting this, I've removed the .rpm for now.

Best,
Vadim
