### ISSUE TITLE
How and add variable modification of dimethyaltion and methyaltion?

### ISSUE THREAD

**Issue by Hanqing1205** [vdemichev/DiaNN#692]
Hello, 
I now add two variable modifications about lysine methylation. 
-var-mod UniMod : 199,32.0564, K 
-var-mod UniMod : 284, 16.0282, K 
Is this setting correct ? Why does ' WARNING : skipping 10707429 precursors, unrecognised modifications ? If these precursors are important, consider forcing prediction of spectra / RTs / IMs for these precursors anyway, using the-strip-unknown-mods option '****
<img width="1274" alt="屏幕截图 2023-05-10 220549" src="https://github.com/vdemichev/DiaNN/assets/133129481/3ed2256f-6bd1-4978-b41e-3a8d7e3032ed">

**Comment by Hanqing1205** [comment]
OK, I have solved this problem. Thanks.

**Comment by diosphenol** [comment]
Hi Hanqing, I wonder if you can give me insights on how you processed with this and did you tried --strip-unknown-mods?

**Comment by Hanqing1205** [comment]
Hello Alsherbiny, I have tried "--strip-unknown-mods". It's useful and can search for any modification when available in Unimod. You can find the same information in the user manual also.
for example 
--full-unimod
--strip-unknown-mods
--var-mod UniMod:284,16.028204,K
Best,Hanqing        
            
                
                    
                            
                                
                            
                            
                                ZhangHanqing
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- Replied Message ----FromMuhammad ***@***.***>Date1/24/2024 ***@***.***>***@***.***>,State ***@***.***>SubjectRe: [vdemichev/DiaNN] How and add variable modification of dimethyaltion and methyaltion? (Issue #692)Hi Hanqing, I wonder if you can give me insights on how you processed with this and did you tried --strip-unknown-mods?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
