### ISSUE TITLE
DiaNN linux (1.8.1.deb version) does not recognize FragmentSeriesNumber/FragmentNumber in tsv lib

### ISSUE THREAD

**Issue by jalew188** [vdemichev/DiaNN#693]
[DIANN version]
1.8.1 from .deb file

[OS]
linux (opensuse)

[LOG]
1 files will be processed
[0:00] Loading spectral library /fs/pool/pool-mann-projects/Feng/speclib_for_people/fragger.speclib.tsv
WARNING: no fragment number information found in the library; it's essential to use a properly annotated library for reliable analysis; make sure only detectable fragments are included, these consist of at least three residues, and unfragmented precursors are NOT annotated as fragments; here, consider using --no-lib-filter to prevent fragments being filtered out

Both FragmentNumber and FragmentSeriesNumber did not work.

The windows version works well for the two fragment number headers.

**Comment by vdemichev** [comment]
This is strange, maybe formatting problem with specifically that file? Have you tried public libs that are around?

Vadim

**Comment by jalew188** [comment]
But I have tested windows, it worked very well

**Comment by jalew188** [comment]
Hi @vdemichev , this is due to "\r\n" issue in the tsv, which is similar to #688 . Thanks anyway.
