### ISSUE TITLE
Add species information

### ISSUE THREAD

**Issue by Allen188** [vdemichev/DiaNN#7]
In the output file, how do I add species information to the protein name?

**Comment by vdemichev** [comment]
Hi Allen188, if you use a sequence database (UniProt FASTA) to annotate the spectra library, then protein names in the output report would look like SOCS4_HUMAN, i.e. there's gonna be a species identifier after the '_' symbol. If you select "Implicit protein grouping = genes (species-specific)" in DIA-NN options, a species identifier will also be added to the gene names. Finally, if you don't use a sequence database and disable "Protein inference", precursor ion annotation in the report will be the same as in the spectral library (i.e. with the same protein names).
