### ISSUE TITLE
missing value increases

### ISSUE THREAD

**Issue by Allen188** [vdemichev/DiaNN#70]
Hello,
I recently found that the missing value of the new version 1.7.12 has increased to about 50%, while the missing value of the old version 1.6.0 is only about 20%. Is this normal?

**Comment by vdemichev** [comment]
Hi, 1.7.12 is very significantly better in all aspects than 1.6.0. If you are unsure if it analyses an experiment well, please share with me full details about the experiment, including full logs.

Vadim
