### ISSUE TITLE
About library building in the article"DIA-NN: neural networks"

### ISSUE THREAD

**Issue by Clovernana** [vdemichev/DiaNN#71]
Hi,Vadim
From this article “DIA-NN: neural networks and interference correction enable deep proteome coverage in high throughput”，I have noticed  that the library built in this study is by GPF  not DDA . Have you compare the difference between DDA and GPF about  the spectra library building?Such as retention time shift , the difference of identified proteins and peptide by this two libraries?Actually，I‘m curious why you use GPF for spectra library building in this library.

**Comment by vdemichev** [comment]
Hi Clover, we suspect but have no experimental proof yet that libraries should ideally always be produced with DIA, unless looking for certain types of PTMs, whether it's GFP or offline fractionation. The rationale for using GFP is explained in detail here: https://www.nature.com/articles/s41467-018-07454-w

Vadim

**Comment by Clovernana** [comment]
OK，does DIANN cope identically for GPF-based spectra library and  DDA-based library ?


| |
姜娜
|
|
16622080827@163.com
|
签名由网易邮箱大师定制
On 12/11/2020 21:36，Vadim Demichev<notifications@github.com> wrote：

Hi Clover, we suspect but have no experimental proof yet that libraries should ideally always be produced with DIA, unless looking for certain types of PTMs, whether it's GFP or offline fractionation. The rationale for using GFP is explained in detail here: https://www.nature.com/articles/s41467-018-07454-w

Vadim

**Comment by vdemichev** [comment]
We never tested this directly

**Comment by Clovernana** [comment]
OK.Looking forward to your further testing about DDA-based and GPF-based spectra library in DIANN!
| |
姜娜
|
|
16622080827@163.com
|
签名由网易邮箱大师定制
On 12/11/2020 21:46，Vadim Demichev<notifications@github.com> wrote：

We never tested this directly
