### ISSUE TITLE
Import DIA-NN result into Skyline

### ISSUE THREAD

**Issue by without1102** [vdemichev/DiaNN#72]
Hi Vadim,

DIANN is a great software for large-scale analysis. I have two questions. First, I'm analyzing Arabidopsis DIA data. Most of the Arabidopsis samples use TAIR10 database to do proteomics database search instead of the UniProt database. I'm wondering if DIANN can use TAIR10 database to do DIA analysis. Second, I want to use Skyline software to visualize the MS1 and MS2 peaks of my interested target. Would you please tell me which DIANN output files can be used to import into Skyline for further analysis? Thank you very much.

Chuan-Chih

**Comment by vdemichev** [comment]
Hi Chuan-Chih,

TAIR should probably be fine, please let me know if there are any issues.
Sorry, I don't have much experience working with Skyline, Brett Phinney did some tutorial on this though https://video.ucdavis.edu/playlist/details/0_4jkc4swu.
Also, you can always use the --vis function in DIA-NN for visualisation of peptides of interest.

Vadim

**Comment by without1102** [comment]
Hi Vadim,

Thank you for your support. I'll try it.

Chuan-Chih

**Comment by vdemichev** [comment]
Hi Chuan-Chih,

If something is not working as expected, please email me with all the details. I will need to see the log (please use the "Save log" button in DIA-NN) and the final output report.

Best wishes,

Vadim

**Comment by without1102** [comment]
Hi Vadim,

I have email you the details you mentioned above. Thank you for your time.

Best,

Chuan-Chih
