### ISSUE TITLE
Add DiaNN as bioconda recipe

### ISSUE THREAD

**Issue by npinter** [vdemichev/DiaNN#727]
Hello,

we want to add DiaNN (linux) as a bioconda recipe (https://github.com/bioconda/bioconda-recipes/pull/41491) and we are not sure if we are allowed to (licence..). The recipes are open source and it's just another way to redistribute your software to services/tools like usegalaxy.org or nextflow. Thanks for making DiaNN freely available. :)

Best,
Niko

**Comment by vdemichev** [comment]
Hi Niko,

In general, I personally probably would not mind this per se, however there's one difficulty, which is that it places extra requirements on us for testing things, specifically the Linux version, which is a bit challenging. Also, the .deb and .rpm distros don't properly install dependencies atm. So I would suggest not to bother with this, everyone can get .tar.gz from this website and just unpack it.

Best,
Vadim
