### ISSUE TITLE
the order of protein IDs in Protein Group

### ISSUE THREAD

**Issue by lyumengge** [vdemichev/DiaNN#750]
Here is the backgroud of the question:
I used the spectral library generated by Fragpipe, it contained "protein group" already.
And I used DIAnn 1.7.11 on Linux, here is my command line in the log file:

_**/var/spool/slurmd/job10982929/slurm_script: line 11: 939424 Segmentation fault      (core dumped) /storage/soft/diann-linux-1.7.11 --f filename1.mzML --f filename2.mzML --f filename3.mzML --lib library.tsv --verbose 1 --out report1.tsv --out-gene report1.genes.tsv --qvalue 0.01 --out-lib libtest1.tsv --gen-spec-lib --fasta uniprot.fasta --met-excision --use-quant --individual-mass-acc --individual-windows --rt-profiling --pg-level 1 --threads 16**_

And I did not find the "protein inference" setting in the above log file, I got protein matrix finally, it contained "Protein groups" column.

The question is 
“Is the order of protein IDs in the Protein Group sorted alphabetically by protein ID? Or do proteins that score higher come first?"

**Comment by vdemichev** [comment]
It's alphabetical sorting. I replied by email, but your email server blocked it.
