### ISSUE TITLE
Out of memory for DIA phospho dataset

### ISSUE THREAD

**Issue by rolivella** [vdemichev/DiaNN#753]
Hello, we're trying to run DIANN for a phosphoproteome with 30 raw files with this additional config params: 

```
--var-mods 2
--var-mod UniMod:21,79.966331,STY
--no-norm
```

At the moment I tested DIANN allocating 64GB but failed. 

Do you know how mem should be allocated in order to run this job? Thanks!

**Comment by vdemichev** [comment]
How does the log look like and how much RAM do you have in the system?

Vadim

**Comment by rolivella** [comment]
This is the log: [rsDIANNsubmission.output.log.zip](https://github.com/vdemichev/DiaNN/files/12030053/rsDIANNsubmission.output.log.zip)

I send this job to a cluster queue were I allocated 64GB of mem. After some hours running, the scheduler automatically killed the job: `cgroup/OOM: Killed because of memory limit`

**Comment by vdemichev** [comment]
Two comments:
- I suggest to run in silico prediction in a separate step.
- Mass accuracy setting is strange and is likely having a negative effect on performance & RAM consumption
- Are you sure nothing else eats memory there? One of the EOF is after just 15% of the data analysed - this is strange. But the whole analysis can indeed potentially go above 64Gb, yes.

**Comment by vdemichev** [comment]
Also, can maybe monitor the RAM consumption of the DIA-NN process. DIA-NN itself did not issue a warning, apparently it did not detect potential out of memory event.

**Comment by rolivella** [comment]
@vdemichev at the end we found a misconfiguration of the mass accuracy that caused the out of memory, as you suggested. I close the issue. Thank you!
