### ISSUE TITLE
How to add protein IDs to "unique_genes_matrix.tsv" in DIANN1.8

### ISSUE THREAD

**Issue by clubmann** [vdemichev/DiaNN#763]
Dear Demichev,

Unlike ver1.7, in ver1.8, only gene names are assigned to "unique_genes_matrix" in addition to quantitative values. Therefore, if I would like to get protein ID information, I need to use ex. vlookup function to link protein IDs from "pg.matrix" or "pr.matrix" relying on gene names. In doing so, there may be cases where two protein IDs are not assigned properly for the same gene name, although this is rare. Please let me know how to solve this problem.

Thank you very much for your support.
Best regards,
clubmann

**Comment by vdemichev** [comment]
Hi clubmann,

Can you please describe the issue in mode detail with screenshots of how things look & should look? In general, if there's any problem with the matrices, please just use the main report.

Best,
Vadim

**Comment by clubmann** [comment]
Hi Vadim,

Thank you for your quick reply.
Here is an example of pg.matrix which has a redundant in gene name.
![Ex_pg_matrix](https://github.com/vdemichev/DiaNN/assets/140150778/1746dd49-c6ec-4d8c-a402-2e649136a212)


The vlookup function in excel picks up either gene name.
![Ex_vlookup](https://github.com/vdemichev/DiaNN/assets/140150778/c1a09975-181a-44e2-91fb-aa97c7687cec)


Should I choose one gene name and delete the another one in the pg_matrix before performing vlookup?
The main report was too big to open in the excel in this case.

Best regards,
clubmann

**Comment by vdemichev** [comment]
'Protein.Names' and 'Genes' refer to different things, the first one is not a gene name but rather a 'protein name' as encoded in UniProt. For example, there are over >70k unique protein names in human proteome but just over 20k genes. Does this clarify the question?

**Comment by clubmann** [comment]
The Uniprot accession number is suitable for us to use for our downstream analysis. However, the first output file "unique_genes_matrix" doesn't provide the Uniprot accession number but give us gene name. So, my question is what is the best way to connect their information?

**Comment by vdemichev** [comment]
If you are only interested in gene names, you can use unique_genes matrix. Otherwise use pg_matrix that has both?

**Comment by clubmann** [comment]
That would be an alternative way, but the quantification values are different between pg file and unique file. Does pg file have MaxLFQ values?

**Comment by vdemichev** [comment]
Yes, all quantities are MaxLFQ

**Comment by clubmann** [comment]
Thank you for your clarification! Let me have one more question. What makes the difference of quantification value btw pg file and unique gene file?

**Comment by vdemichev** [comment]
Unique genes are quantified using precursors that match only to these genes and not other genes.
Protein groups are quantifies using precursors allocated to these groups by the protein inference algorithm.

**Comment by clubmann** [comment]
I appreciate your clear answer. Thank you so much for sparing your time for me!
