### ISSUE TITLE
DIA-NN results differ depending on the file processing order

### ISSUE THREAD

**Issue by MarcIsak** [vdemichev/DiaNN#79]
Hi, 

 I am using DIA-NN 1.7.12 on Windows machine, where I use the command-line-interface for processing. 

By accident, I noticed that the number of precursor and protein identifications seem depend on the order of RAW file processing. At least, it seems like it is critical what file is processed first in a series, as it sets the optimized mass accuracy right? The RAW-files are derived from biological replicates of similar samples. I made a plot to show the number of identification for the different files,  the same library, but changing the processing order in 3 cases. The identifications are affected more for some raw-files than others. You can also see the determined optimized mass accuracy for the 3 different cases. The data was pulled from the output stats files(TSV) that was generated. 

![identifications_diann Rplot_inkscaped](https://user-images.githubusercontent.com/47174270/104722396-0b063380-572e-11eb-86f0-1079aeaedef3.png)

I guess it shouldn't really matter in which order I process the files right? 

Unfortunately, I cannot share the MS data with you (yet) as the files might part of a coming publication for me. But I think it is interesting to mention this to you, as you might see a similar trend using other MS files. 

Best,

Marc

**Comment by vdemichev** [comment]
Hi Marc,

Yes, this is how it's supposed to be. If you would like the results to be independent of the file order, just fix the mass accuracies and the scan window or use the "Unrelated runs" option. In general, it is recommended to fix settings anyway, while automatic inference is there to just simplify things for quick initial analyses, when you don't yet know which settings are optimal for a particular LC-MS setup.

Best wishes,

Vadim
