### ISSUE TITLE
How to use Proteome Discoverer search results as a DIA-NN library?

### ISSUE THREAD

**Issue by wabash2011** [vdemichev/DiaNN#8]
Is there an easy way to use the Proteome Discoverer search results as a DIA-NN library ? We are using PD2.4. Thanks!

**Comment by vdemichev** [comment]
Hi wabash2011, not that I am aware of. However, you can easily generate libraries from DDA data using [FragPipe](https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html) - it's a nice GUI that automatically runs MSFragger and SpectraST (for library generation). Also, I think MSFragger and SpectraST are available as Proteome Discoverer nodes, not sure if PD allows to generate spectral libraries with these though.

I have now updated the manual to indicate how to use FragPipe libraries in DIA-NN (need to add "--library-headers *,*,*,*,*,*,Protein ID,Entry Name" to the "Additional options" text box).

**Comment by wabash2011** [comment]
Hi, Vdemichev, thanks for the quick response. Skyline or Spectronaut generates spectrum libraries from different search engines, for example, from PD search results (. pdResult file)  or from MaxQunant output .msms files. So is there an easy way to generate DIA-NN compatible spectrum libraries from PD search results (. pdResult files)? 
MSFragger and PD Sequest are different search engines, which would likely generate slightly different results.

**Comment by vdemichev** [comment]
Hi wabash2011, I have never looked at PD output, so there is no support for this in DIA-NN. I will take a look, maybe it would indeed be easy to implement.

**Comment by wabash2011** [comment]
Hi, vdemichev, that would be great!

**Comment by vdemichev** [comment]
OK, looks like this is possible, but will take some time to implement. Don't think I will be able to do this in the near future.
