### ISSUE TITLE
Fragment m/z

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#80]
Could we have fragment m/z info printed in the output .tsv file as well, There are the extracted fragment peak quantities printed in the output file but I couldn't find any info to link back which fragment ion the extracted intensity came from. Is there any way to know the fragment type or fragment m/z for each extracted fragment intensity?

**Comment by vdemichev** [comment]
Yes, please use the --report-lib-info command, and then reference masses and annotation information will be printed for the top 6 fragments (based on library intensities) in the Fragment.Info column.

**Comment by cctsou** [comment]
Thanks a lot!!
