### ISSUE TITLE
What's the expected format of protein header in FASTA

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#81]
I am using the Ensembl FASTA which has the following header format

>>ENSG00000001460|ENST00000003583|ENSP00000003583|ENSE00001879255;ENSE00003692979;ENSE00003516207;ENSE00003688858;ENSE00003539806;ENSE00003638911;ENSE00003692602;ENSE00003631141|1;2;6;4;7;3;8;5|STPG1|Q5TH74

From the result I got, it seems like DIA-NN did not recognize protein and gene names correctly. What is the expected format for protein name/ gene name so the protein grouping would be done properly?

**Comment by vdemichev** [comment]
Yes, UniProt format is supported (protein IDs specified like this: ">sp|P06396|GELS_HUMAN"), most other formats - not supported.

Vadim

**Comment by cctsou** [comment]
> Yes, UniProt format is supported (protein IDs specified like this: ">sp|P06396|GELS_HUMAN"), most other formats - not supported.
> 
> Vadim

What is the info required from UniProt format? or only the order of attributes matters?
For example if I reformat it like sp|ENSP00000003583|ENSG00000001460, would it work?

**Comment by vdemichev** [comment]
Probably it will. You can easily try it on a FASTA file consisting of a single entry, see what kind of formatting produces the correct result
