### ISSUE TITLE
Unable to Open Custom Library in Dia-NN

### ISSUE THREAD

**Issue by Vectolyser** [vdemichev/DiaNN#815]
[library.zip](https://github.com/vdemichev/DiaNN/files/12791958/library.zip)
Hello, I used a deep learning model to predict a library with new library intensities based on the sequences from the original library. The format of the predicted library is consistent with Easypqp, but Dia-NN is unable to handle it. It exits within a few seconds of startup. Do you know what might be causing this issue? I have attached the problematic file for reference.

**Comment by vdemichev** [comment]
Looks like formatting problem & empty fields:
![image](https://github.com/vdemichev/DiaNN/assets/30595084/f427372c-60ea-4596-bdd9-94f55607eb85)

**Comment by Vectolyser** [comment]
> Looks like formatting problem & empty fields: ![image](https://user-images.githubusercontent.com/30595084/272326573-f427372c-60ea-4596-bdd9-94f55607eb85.png)
I've corrected it and now it can generate analysis files successfully. I have another question: In a library, is it more advantageous for DIA-NN analysis to have a greater number of fragments for each precursor, or should the number be controlled within a reasonable range?

**Comment by vdemichev** [comment]
For predicted libraries default is 12 and this is rather optimal. In general, going beyond 12 yields very little benefit in most cases.

**Comment by Vectolyser** [comment]
> For predicted libraries default is 12 and this is rather optimal. In general, going beyond 12 yields very little benefit in most cases.

That helps a lot.Thanks for your reply!!
