### ISSUE TITLE
diann.exe has stopped working

### ISSUE THREAD

**Issue by gukongxin** [vdemichev/DiaNN#816]
Hi,

When I try to convert to dia file, I get the error message 'diann.exe has stopped working.' 
I've attempted to uninstall and reinstall the software, but it didn't work.
![图片1](https://github.com/vdemichev/DiaNN/assets/134674162/6d225d80-2482-44e6-8fb8-803180f91813)

**Comment by vdemichev** [comment]
Did you copy the DLLs as described in the docs?

**Comment by gukongxin** [comment]
Thank you.
It's solved.
