### ISSUE TITLE
Is it possible to rerun only protein quant without rerun everything

### ISSUE THREAD

**Issue by cctsou** [vdemichev/DiaNN#85]
I have all data processed but now I want to change TopN parameter, is it possible to do it without rerun everything?

**Comment by vdemichev** [comment]
Yes, please select the option "Use existing .quant files when available". Please make sure all the settings are exactly the same.

Vadim

**Comment by vdemichev** [comment]
Also, I strongly recommend to not use Top N protein quantification, but rely on MaxLFQ. Also, Top N works best with N = 1 in almost all scenarios. Also, you can easily do protein quant with either MaxLFQ or Top N using the diann R package, don't even need to rerun DIA-NN itself to do that.

**Comment by cctsou** [comment]
> Also, I strongly recommend to not use Top N protein quantification, but rely on MaxLFQ. Also, Top N works best with N = 1 in almost all scenarios. Also, you can easily do protein quant with either MaxLFQ or Top N using the diann R package, don't even need to rerun DIA-NN itself to do that.

I have all individual run processed by DIA-NN already, I imagine I could then use diann R package to combine multiple runs to perform MaxLFQ, is it correct. How do I combine them, would simply merging multiple .tsv files then calling df <- diann_load("merged_report.tsv") work?

**Comment by vdemichev** [comment]
Yes, can perform MaxLFQ using the diann R package. Merging like that will work, can also just do diann_load() on all the reports, and the rbind() on the resulting data frames. But if you processed them separately, they probably need normalisation before MaxLFQ.
