### ISSUE TITLE
No output file when Log level is 5

### ISSUE THREAD

**Issue by Maithy15** [vdemichev/DiaNN#86]
Hello, 

I want a detailed output from DIA-NN, and if I am right this can be done by setting the log level to 5. But when I keep the log level to 5, no output file is written on the specified output directory. Am I doing something wrong? Also, I have 6 files, but at the end of the search, I can only see 3 .quant files. What could be the problem here? I am new to DIA-NN and we are trying to establish a proper DIA acquisition method in our lab, it would be great if we could get a detailed report.

**Comment by vdemichev** [comment]
Hi,

Can you please share the full output printed by the GUI? For this can use the "Save log" button.

Best wishes,

Vadim

**Comment by Maithy15** [comment]
Hi please find the attached log file. The identifications are very few for the files that I used and I repeated the search with more or less the same settings to get the log file, still did not get a detailed report.
[DIA-NN_log.txt](https://github.com/vdemichev/DiaNN/files/6038815/DIA-NN_log.txt)

**Comment by vdemichev** [comment]
OK, what happens is that DIA-NN struggles to identify anything in the data. Basically, the larger the search space (and here it's 6 million) and the less peptides are actually detectable, the more likely this is too happen. This leads to it requiring more memory than there is in the system. Windows then shuts it down. With any spectral library that would be very unlikely. 

With DIA-NN 1.7.12 things can be improved by using --mass-acc-cal 30 and selecting the "Reduce memory usage" option. But better use DIA-NN 1.7.14 https://github.com/vdemichev/DiaNN/releases/tag/1.7.14, which I released today, together with the "Reduce RAM usage" option.

**Comment by Maithy15** [comment]
Thanks for a prompt reply, it indeed occupied the whole 128GB of RAM during the analysis.
