### ISSUE TITLE
cross-run normalisation details

### ISSUE THREAD

**Issue by martinPasen** [vdemichev/DiaNN#860]
Hello,

thanks for the great effort and nice software.

I am trying to understand in more detail what which cross-run normalisation is doing. The best resource i could find up to now was question "What is normalisation and how does it work?" in the FAQ. Could you please point me towards paper/supplementary/documentation/code/... where i could find more information about what exactly is happening under the hood?

Thanks a lot,
Martin

**Comment by michaelsteidel86** [comment]
Hi Martin,

this is what I found in the Nature methods paper:

_All the precursor intensities corresponding to identifications with q-values above a given threshold are replaced with zeros and preliminary cross-run normalization based on the total signal (that is, the sum of the intensities of all precursors) is performed. Precursors are then ordered by their coefficients of variation. Top pN precursors are selected, where N is the average number of identifications passing the q-value threshold and p is between 0 and 1. Sums of the intensities of these precursors are calculated and used for normalization (that is, the levels of all precursors are scaled to make these quantities equal in different acquisitions)._

Does this help?
Michael

**Comment by martinPasen** [comment]
Thanks for the info Michael,

All the best,
Martin
