### ISSUE TITLE
Discrepancy between number of entries and number of proteins found by diann for spectral library free search

### ISSUE THREAD

**Issue by kwebber3** [vdemichev/DiaNN#864]
When running DIANN there are only 1327 genes/proteins found in the FASTA file, but there are 6054 entries when I open the file or load it into Proteome discoverer or Fragpipe. Can you please explain why DIANN gets so many less proteins per the same fasta file? We have found this to be true for other FASTA files from different species such as Yeast.

DIANN LOG OUTPUT
`diann.exe` --lib "" --threads 10 --verbose 1 --out "C:\DIA-NN\1.8.1\report.tsv" --qvalue 0.01 --matrices  --out-lib "C:\DIA-NN\1.8.1\report-lib.tsv" --gen-spec-lib --predictor --fasta "X:\tools\FASTA\Escherichia coli (strain K12) (sp_canonical TaxID=83333_and_subtaxonomies).fasta" --fasta-search --min-fr-mz 200 --max-fr-mz 1800 --met-excision --cut K*,R* --missed-cleavages 1 --min-pep-len 7 --max-pep-len 30 --min-pr-mz 300 --max-pr-mz 1800 --min-pr-charge 1 --max-pr-charge 4 --unimod4 --reanalyse --relaxed-prot-inf --smart-profiling --peak-center --no-ifs-removal 
DIA-NN 1.8.1 (Data-Independent Acquisition by Neural Networks)
Compiled on Apr 14 2022 15:31:19
Current date and time: Mon Nov 13 14:38:03 2023
CPU: GenuineIntel Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
SIMD instructions: AVX AVX2 AVX512CD AVX512F FMA SSE4.1 SSE4.2 
Logical CPU cores: 20
Thread number set to 10
Output will be filtered at 0.01 FDR
Precursor/protein x samples expression level matrices will be saved along with the main report
A spectral library will be generated
Deep learning will be used to generate a new in silico spectral library from peptides provided
Library-free search enabled
Min fragment m/z set to 200
Max fragment m/z set to 1800
N-terminal methionine excision enabled
In silico digest will involve cuts at K*,R*
Maximum number of missed cleavages set to 1
Min peptide length set to 7
Max peptide length set to 30
Min precursor m/z set to 300
Max precursor m/z set to 1800
Min precursor charge set to 1
Max precursor charge set to 4
Cysteine carbamidomethylation enabled as a fixed modification
A spectral library will be created from the DIA runs and used to reanalyse them; .quant files will only be saved to disk during the first step
Highly heuristic protein grouping will be used, to reduce the number of protein groups obtained; this mode is recommended for benchmarking protein ID numbers; use with caution for anything else
When generating a spectral library, in silico predicted spectra will be retained if deemed more reliable than experimental ones
Fixed-width center of each elution peak will be used for quantification
Interference removal from fragment elution curves disabled
Exclusion of fragments shared between heavy and light peptides from quantification is not supported in FASTA digest mode - disabled; to enable, generate an in silico predicted spectral library and analyse with this library
WARNING: MBR turned off, two or more raw files are required

0 files will be processed
[0:00] Loading FASTA X:\tools\FASTA\Escherichia coli (strain K12) (sp_canonical TaxID=83333_and_subtaxonomies).fasta
[0:00] Processing FASTA
[0:01] Assembling elution groups
[0:02] 509880 precursors generated
[0:02] Gene names missing for some isoforms
[0:02] Library contains 1327 proteins, and 1327 genes
[0:02] Encoding peptides for spectra and RTs prediction
[0:03] Predicting spectra and IMs
`

FASTA FILE FIRST FEW LINES
>ProteinCenter:sp_canonical|C4ZS91 Cell division topological specificity factor [OS=Escherichia coli (strain K12 / MC4100 / BW2952)]
MALLDFFLSRKKNTANIAKERLQIIVAERRRSDAEPHYLPQLRKDILEVICKYVQIDPEMVTVQLEQKDGDISILELNVT
LPEAEELK
>ProteinCenter:sp_canonical|P0A734 Cell division topological specificity factor [OS=Escherichia coli (strain K12)]
MALLDFFLSRKKNTANIAKERLQIIVAERRRSDAEPHYLPQLRKDILEVICKYVQIDPEMVTVQLEQKDGDISILELNVT
LPEAEELK
>ProteinCenter:sp_canonical|B1XA61 Cell division topological specificity factor [OS=Escherichia coli (strain K12 / DH10B)]
MALLDFFLSRKKNTANIAKERLQIIVAERRRSDAEPHYLPQLRKDILEVICKYVQIDPEMVTVQLEQKDGDISILELNVT
LPEAEELK
>ProteinCenter:sp_canonical|B1XA63 Probable septum site-determining protein MinC [OS=Escherichia coli (strain K12 / DH10B)]
MSNTPIELKGSSFTLSVVHLHEAEPKVIHQALEDKIAQAPAFLKHAPVVLNVSALEDPVNWSAMHKAVSATGLRVIGVSG
CKDAQLKAEIEKMGLPILTEGKEKAPRPAPTPQAPAQNTTPVTKTRLIDTPVRSGQRIYAPQCDLIVTSHVSAGAELIAD
GNIHVYGMMRGRALAGASGDRETQIFCTNLMAELVSIAGEYWLSDQIPAEFYGKAARLQLVENALTVQPLN
>ProteinCenter:sp_canonical|P18196 Septum site-determining protein MinC [OS=Escherichia coli (strain K12)]
MSNTPIELKGSSFTLSVVHLHEAEPKVIHQALEDKIAQAPAFLKHAPVVLNVSALEDPVNWSAMHKAVSATGLRVIGVSG
CKDAQLKAEIEKMGLPILTEGKEKAPRPAPTPQAPAQNTTPVTKTRLIDTPVRSGQRIYAPQCDLIVTSHVSAGAELIAD
GNIHVYGMMRGRALAGASGDRETQIFCTNLMAELVSIAGEYWLSDQIPAEFYGKAARLQLVENALTVQPLN
>ProteinCenter:sp_canonical|C4ZS93 Probable septum site-determining protein MinC [OS=Escherichia coli (strain K12 / MC4100 / BW2952)]
MSNTPIELKGSSFTLSVVHLHEAEPKVIHQALEDKIAQAPAFLKHAPVVLNVSALEDPVNWSAMHKAVSATGLRVIGVSG
CKDAQLKAEIEKMGLPILTEGKEKAPRPAPTPQAPAQNTTPVTKTRLIDTPVRSGQRIYAPQCDLIVTSHVSAGAELIAD
GNIHVYGMMRGRALAGASGDRETQIFCTNLMAELVSIAGEYWLSDQIPAEFYGKAARLQLVENALTVQPLN
>ProteinCenter:sp_canonical|C4ZUK3 Protein SlyX [OS=Escherichia coli (strain K12 / MC4100 / BW2952)]
MQDLSLEARLAELESRLAFQEITIEELNVTVTAHEMEMAKLRDHLRLLTEKLKASQPSNIASQAEETPPPHY
>ProteinCenter:sp_canonical|B1X6J7 Protein SlyX [OS=Escherichia coli (strain K12 / DH10B)]
MQDLSLEARLAELESRLAFQEITIEELNVTVTAHEMEMAKLRDHLRLLTEKLKASQPSNIASQAEETPPPHY
>ProteinCenter:sp_canonical|P0A8R4 Protein SlyX [OS=Escherichia coli (strain K12)]
MQDLSLEARLAELESRLAFQEITIEELNVTVTAHEMEMAKLRDHLRLLTEKLKASQPSNIASQAEETPPPHY
>ProteinCenter:sp_canonical|P0A823 Sugar fermentation stimulation protein A [OS=Escherichia coli (strain K12)]
MEFSPPLQRATLIQRYKRFLADVITPDGRELTLHCPNTGAMTGCATPGDTVWYSTSDNTKRKYPHTWELTQSQSGAFICV
NTLWANRLTKEAILNESISELSGYSSLKSEVKYGAERSRIDFMLQADSRPDCYIEVKSVTLAENEQGYFPDAVTERGQKH
LRELMSVAAEGQRAVIFFAVLHSAITRFSPARHIDEKYAQLLSEAQQRGVEILAYKAEISAEGMALKKSLPVTL
>ProteinCenter:sp_canonical|C4ZRN9 Sugar fermentation stimulation protein A [OS=Escherichia coli (strain K12 / MC4100 / BW2952)]
MEFSPPLQRATLIQRYKRFLADVITPDGRELTLHCPNTGAMTGCATPGDTVWYSTSDNTKRKYPHTWELTQSQSGAFICV
NTLWANRLTKEAILNESISELSGYSSLKSEVKYGAERSRIDFMLQADSRPDCYIEVKSVTLAENEQGYFPDAVTERGQKH
LRELMSVAAEGQRAVIFFAVLHSAITRFSPARHIDEKYAQLLSEAQQRGVEILAYKAEISAEGMALKKSLPVTL
>ProteinCenter:sp_canonical|B1XCC1 Sugar fermentation stimulation protein A [OS=Escherichia coli (strain K12 / DH10B)]
MEFSPPLQRATLIQRYKRFLADVITPDGRELTLHCPNTGAMTGCATPGDTVWYSTSDNTKRKYPHTWELTQSQSGAFICV
NTLWANRLTKEAILNESISELSGYSSLKSEVKYGAERSRIDFMLQADSRPDCYIEVKSVTLAENEQGYFPDAVTERGQKH
LRELMSVAAEGQRAVIFFAVLHSAITRFSPARHIDEKYAQLLSEAQQRGVEILAYKAEISAEGMALKKSLPVTL
>ProteinCenter:sp_canonical|C4ZXI2 L-seryl-tRNA(Sec) selenium transferase [OS=Escherichia coli (strain K12 / MC4100 / BW2952)]
MTTETRFLYSQLPAIDRLLRDSSFLSLRDTYGHTRVVELLRQMLDEAREVIRGSQTLPAWCENWAQEVDARLTKEAQSAL
RPVINLTGTVLHTNLGRALQAEAAVEAVAQAMRSPVTLEYDLDDAGRGHRDRALAQLLCRITGAEDACIVNNNAAAVLLM
LAATASGKEVVVSRGELVEIGGAFRIPDVMRQAGCTLHEVGTTNRTHANDYRQAVNENTALLMKVHTSNYSIQGFTKAID
EAELVALGKELDVPVVTDLGSGSLVDLSQYGLPKEPMPQELIAAGVSLVSFSGDKLLGGPQAGIIVGKKEMIARLQSHPL
KRALRADKMTLAALEATLRLYLHPEALSEKLPTLRLLTRSAEVIQIQAQRLQAPLAAHYGAEFAVQVMPCLSQIGSGSLP
VDRLPSAALTFTPHDGRGSHLESLAARWRELPVPVIGRIYDGRLWLDLRCLEDEQRFLEMLLK
>ProteinCenter:sp_canonical|P75895 Putative aminoacrylate hydrolase RutD [OS=Escherichia coli (strain K12)]
MKLSLSPPPYADAPVVVLISGLGGSGSYWLPQLAVLEQEYQVVCYDQRGTGNNPDTLAEDYSIAQMAAELHQALVAAGIE
HYAVVGHALGALVGMQLALDYPASVTVLISVNGWLRINAHTRRCFQVRERLLYSGGAQAWVEAQPLFLYPADWMAARAPR
LEAEDALALAHFQGKNNLLRRLNALKRADFSHHADRIRCPVQIICASDDLLVPTACSSELHAALPDSQKMVMPYGGHACN
VTDPETFNALLLNGLASLLHHREAAL

**Comment by kwebber3** [comment]
I figured out it is because we used a fasta file downloaded by PD

**Comment by KunathBJ** [comment]
Hello,

How did you fix the issue?
I have the same issue with a custom made fasta file.

Thanks
