### ISSUE TITLE
Input of the neural network ensemble classifer of DIA-NN

### ISSUE THREAD

**Issue by wenronchen** [vdemichev/DiaNN#877]
Dear Vadim,

I recently read your insightful paper on DIA-NN and was particularly intrigued by the method involving 73 characteristics of the putative elution peaks used as input for the neural network. However, I seem to have difficulty locating the source code that calculates these scores. Could you kindly assist me in accessing this information? It would be greatly appreciated if you could share the relevant code or guide me to where I might find it in the GitHub repository.

Thank you very much for your time and assistance.

**Comment by vdemichev** [comment]
Please see the older commits on the github, e.g. the one corresponding to the 1.7.12 version - it contains the source code. Also, I think DIA-NN 1.6 source is in the supplementary data for the original Nature Methods paper.

Best,
Vadim

**Comment by wenronchen** [comment]
Thank you for your suggestion. :)
