### ISSUE TITLE
"Peak width" in the log 

### ISSUE THREAD

**Issue by Kokoushin** [vdemichev/DiaNN#890]
Hi Vadim,

A quick question, the "peak width" shows the data points per peak in log?

Is there more detailed information available in the main report?

Ko

**Comment by vdemichev** [comment]
Hi Ko,

In the log, yes, mean dp/peak at FWHM
The recent 1.8.2 beta 27 reports a proxy for peak width (as start/stop RT) in te .parquet output file for each precursor - but this is not at FWHM.

Best,
Vadim

**Comment by Kokoushin** [comment]
How to calculate the dp/peak.  (RT.stop-RT.start)*60/cycle time?
Sorry, I'm the beginner in proteomics.
