### ISSUE TITLE
semi specific cleavages

### ISSUE THREAD

**Issue by tobiasko** [vdemichev/DiaNN#90]
Dear @vdemichev ,

is it possible to define a semi-specific cleavage pattern in Dia-NN GUI for a library free search? How would semi tryptic specificity be coded using `--cut`

I am trying to re-analyse LiP-MS data, so this would be essential.

Best,
Tobi

**Comment by vdemichev** [comment]
Hi Tobi,

Unfortunately this is not supported. In theory it's possible to implement this in DIA-NN (but not very easy), if you are interested in collaborating on this and there's a strong motivation to do that for LiP-MS, please contact me by email. Also, one workaround would be to simply supply DIA-NN with a list of semi-tryptic peptides produced by some other means, and then normal library-free search would then work just fine.

Best wishes,

Vadim

**Comment by tobiasko** [comment]
ok. Let me first check how the quantification with the published libs performs.
