### ISSUE TITLE
SILAC in DiaNN 1.8.2

### ISSUE THREAD

**Issue by Giu-F** [vdemichev/DiaNN#924]
Hi, 
I searched some SILAC-DIA runs in the new beta version of DiaNN 1.8.2. 
In report.tsv, the column "Precursor.translated" is missing, and I was using that quantity for SILAC with the older version 1.8.1. 
Shall I use "
Precursor.Quantity" now?
Thanks

**Comment by michaelsteidel86** [comment]
yes - but would use the normalised ones ('Precursor.Normalised')
