### ISSUE TITLE
SILAC with experimental library

### ISSUE THREAD

**Issue by Giu-F** [vdemichev/DiaNN#926]
Hi, I generated a library from DDA runs in Spectromine. I used it to search DIA runs in DiaNN and it works, no problems. 
Now I am trying to use the same library to search DIA SILAC runs. 
I have successfully used DIANN to search DIA SILAC runs in the past, using a predicted spectral library generated in DiaNN and these commands: 
--fixed-mod SILAC,0,0,KR,label
--lib-fixed-mod SILAC
--channels SILAC,L,KR,0:0; SILAC,M,KR,4.025107:6.020129;SILAC,H,KR,8.014199:10.008269
--peak-translation
--original-mods
And it worked very well. 
Now I am doing the same with the experimental library, but I can't get it to work. 
It does the first pass, generates the library, searches the files again, and then stops at this step: "Quantifying peptides". 
I opened the first pass report, and the precursors do not contain SILAC at all. 
Thanks in advance!

**Comment by michaelsteidel** [comment]
Would you mind sharing logs?

**Comment by Giu-F** [comment]
[report-for-2-files.log.txt](https://github.com/vdemichev/DiaNN/files/14156728/report-for-2-files.log.txt)
Now it actually finished, but SILAC did not work anyway

**Comment by vdemichev** [comment]
This is indeed strange, settings seem correct.
So what do you see in 'Precursor.Id' column in the main report? Can you please share the first several entries? 

Btw, we did a major overhaul of SILAC, PTM scoring & also did some Astral optimisations in the development version (soon to be released).

**Comment by Giu-F** [comment]
Precursor.Id
(UniMod:1)AAAAAAAAAAGAAGGRGS(UniMod:21)GPGR3
(UniMod:1)AAAAAALSGAGT(UniMod:21)PPAGGGAGGGGAGGGGSPPGGWAVAR3
(UniMod:1)AAAAAALSGAGT(UniMod:21)PPAGGGAGGGGAGGGGSPPGGWAVAR3
(UniMod:1)AAAAAALSGAGT(UniMod:21)PPAGGGAGGGGAGGGGSPPGGWAVAR4
(UniMod:1)AAAAAALSGAGT(UniMod:21)PPAGGGAGGGGAGGGGSPPGGWAVAR4
(UniMod:1)AAAVAAAGAGEPQS(UniMod:21)PDELLPK2
(UniMod:1)AAAVAAAGAGEPQS(UniMod:21)PDELLPK2
(UniMod:1)AAAVAAAGAGEPQS(UniMod:21)PDELLPK3
(UniMod:1)AAAVAAAGAGEPQS(UniMod:21)PDELLPK3
(UniMod:1)AAAVAAPLAAGGEEAAATTSVPGS(UniMod:21)PGLPGR3
(UniMod:1)AAAVAAPLAAGGEEAAATTSVPGS(UniMod:21)PGLPGR3

**Comment by vdemichev** [comment]
--fixed-mod SILAC,0,0,KR,label -> --fixed-mod SILAC,0.0,KR,label
Typo :)

**Comment by Giu-F** [comment]
great, it works now, thanks!
