### ISSUE TITLE
phosphopeptide DIA

### ISSUE THREAD

**Issue by franziskavoellmy** [vdemichev/DiaNN#93]
Hi Vadim,

I have a question regarding use of DIA-NN for phosphopeptide analysis. Is there some kind of PTM site localization score in the output of DIA-NN to use for confident site selection ? Or would you suggest another approach?

Best,
Franziska

**Comment by vdemichev** [comment]
Hi Franziska,

Yes, there's a special localisation score. Let's discuss this via email (see mine at the bottom of the first page of the manual https://github.com/vdemichev/DiaNN/blob/master/DIA-NN%20GUI%20manual.pdf).

Best wishes,

Vadim
