### ISSUE TITLE
phosphopeptide DIA library free search

### ISSUE THREAD

**Issue by Peilou** [vdemichev/DiaNN#94]
Dear Vadim,

I would like to do a phosphopeptide DIA library free search for diaPASEF data, I wonder if current DIA-NN version 1.7.15 support it? If yes, how to set up the parameters? Thank you!

Pei

**Comment by vdemichev** [comment]
Hi Pei,

Yes, let's discuss this via email (see mine at the bottom of the first page of the manual https://github.com/vdemichev/DiaNN/blob/master/DIA-NN%20GUI%20manual.pdf).

Best wishes,

Vadim
