### ISSUE TITLE
predicted library created by MS2PIP

### ISSUE THREAD

**Issue by Kokoushin** [vdemichev/DiaNN#946]
Hi,

I imported the library predicted by sofware named MS²PIP into DIA-NN, and ended up with an empty matrix report. 
However, when I use the library-free mode (DIA-NN) alone, the results are normal. My library is derived from a custom FASTA.
DIA-NN doen't support the .MSP format?

Ko
[Mix1_MS2PIP.log.txt](https://github.com/vdemichev/DiaNN/files/14371797/Mix1_MS2PIP.log.txt)

**Comment by vdemichev** [comment]
Hi Ko,

I am not familiar with MS2PIP output format.
You can try converting this library to .tsv using DIA-NN and then see if that .tsv file makes sense.

Best,
Vadim
