### ISSUE TITLE
DIA-NN tried but failed to load the following files

### ISSUE THREAD

**Issue by rnirujogi** [vdemichev/DiaNN#95]
Hi Vadim,

Generated spectral library using Fragpipe (easyPQP). However, I can't process DIA runs using this library. Please see the log. Any suggestions or help is greatly appreciated. Had a luck in processing a different set of data with a library generated by Spectronaut.
[03_22_2021 10_23_48.txt](https://github.com/vdemichev/DiaNN/files/6181403/03_22_2021.10_23_48.txt)

Many thanks.

Best,
Raja

**Comment by vdemichev** [comment]
Hi Raja,

The library is loaded fine. DIA-NN cannot load the .raw files though. Are these MSX-DIA? If yes, MSX is not supported by DIA-NN.

Best wishes,

Vadim

**Comment by rnirujogi** [comment]
Hi Vadim,

Thanks for a quick reply. These are not msx but a variable DIA windows. In the past they worked with a different set of files with the same acquisition strategy. Please let me know what could be the issue. Happy to share MS raw data with you.

Best,
Raja

**Comment by vdemichev** [comment]
Yes, please share the smallest of these files (only need one).

**Comment by vdemichev** [comment]
OK, it works perfectly fine on my PC. Please install MSFileReader using the link in the readme / manual - need exactly that version. This will likely solve the problem.

Vadim

**Comment by vdemichev** [comment]
Btw, DIA-NN recomments MS1 mass accuracy for that run ~5ppm, the optimal MS2 mass accuracy is probably also quite tight.

**Comment by vdemichev** [comment]
Did it work?

**Comment by rnirujogi** [comment]
Hi Vadim,

Yes, it did work. I greatly appreciate your help, what a great software suite. I currently generating libraries with Frag pipe and DIA analysis using DIA-NN. Many thanks.

Best,
Raja
