### ISSUE TITLE
SPECLIB file

### ISSUE THREAD

**Issue by gukongxin** [vdemichev/DiaNN#950]
Hi,

I merged the FASTA of human and arabidopsis (from UniProt) and used DIA-NN to generate a spectral library. I want to discard peptides that are shared between human and arabidopsis proteins. I attempted to read the generated TSV file using R, but the file was too large to handle easily. Is there a way to read the SPECLIB file directly?

GU

**Comment by vdemichev** [comment]
Hi GU,

No, need to convert to .tsv. I would suggest to try either data.table or arrow R packages for this.
Another option, just filter out those peptides from the final report.

Best,
Vadim
