### ISSUE TITLE
The results of converted .raw and .mzML files have a huge gap

### ISSUE THREAD

**Issue by Peggyying** [vdemichev/DiaNN#96]
hi，
For a .raw file, using DIA-NN searching, I got 76068 unique Sripped.sequences. Then, I converted the format, using MsConvert, from .raw to .mzML. However, using DIA-NN to search on the .mzML file, I got 104642 unique Sripped.sequences. Overlap of both of two results is about 35237 sequences, not reach 50%. 
Since it is converted from one file, the search results should not have such a wide gap.

**Comment by vdemichev** [comment]
Hi, yes, that's quite strange.
Did you use peak-picking when converting? Can you please (i) make a screenshot of the MSConvert settings, (ii) share the analysis logs (using the "Save log" button in DIA-NN) and (iii) share the .raw file and the spectral library used? My email is at the bottom of the first page of the DIA-NN manual here:  https://github.com/vdemichev/DiaNN/blob/master/DIA-NN%20GUI%20manual.pdf

Best wishes,

Vadim
