### ISSUE TITLE
Re-searching SILAC

### ISSUE THREAD

**Issue by Giu-F** [vdemichev/DiaNN#963]
Hi, I have performed some SILAC searches using the following commands in the 'Additional options' textbox:
--fixed-mod SILAC,0.0,KR,label
--lib-fixed-mod SILAC
--channels SILAC,L,KR,0:0; SILAC,M,KR,4.025107:6.020129;SILAC,H,KR,8.014199:10.008269
--peak-translation
--original-mods
Now I would like to re-search some of my runs with the library generated after the first pass. Which commands should I keep, if any?
Thanks.

**Comment by vdemichev** [comment]
All commands except --lib-fixed-mod need to remain, while --lib-fixed-mod now needs to be removed.

**Comment by vdemichev** [comment]
Filter as for MBR-like searches - this is a general recommendation when using DIA-based spectral libraries, as is the case here.
