### ISSUE TITLE
Setup error: could not read package

### ISSUE THREAD

**Issue by animesh** [vdemichev/DiaNN#97]
![image](https://user-images.githubusercontent.com/21457/112616490-178cc380-8e24-11eb-850b-e345bc53d0d9.png)

I thought may be the issue is home directory? So I tried on Desktop folder "C:\Users\animeshs\Desktop\DIA-NN"
![image](https://user-images.githubusercontent.com/21457/112616450-093ea780-8e24-11eb-8c56-44888e30c00f.png)
![image](https://user-images.githubusercontent.com/21457/112616483-12c80f80-8e24-11eb-974d-a792646f65af.png)

without success, any ideas why?

**Comment by vdemichev** [comment]
Hi Ani, 

Please make sure the installer itself is located on a local hard drive, not a network drive. Please also keep the destination folder default (better not change). If it still does not work, I would right click on the installer and select "Run as administrator".

Please let me know if this solves the problem.

Best wishes,

Vadim

**Comment by animesh** [comment]
Thanks @vdemichev  , install-as-admin works it seems 

![image](https://user-images.githubusercontent.com/21457/112633304-7a3c8a00-8e39-11eb-9c91-c972e1b979c9.png)

👍🏼 but i don't see it using the GPU, is there some switch or this program is hardcoded to use CPU?

**Comment by vdemichev** [comment]
It's CPU only. The whole thing is designed to be able to run fast even on old PCs :)

**Comment by animesh** [comment]
Sounds fair 👍🏼 was wondering is there is some way to make it use the GPU too :)

**Comment by vdemichev** [comment]
Specifically for what it is doing now on the screenshot (predicting spectra), I might add GPU support eventually. But no timeline for this yet.
