### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by L4ft2di3** [vdemichev/DiaNN#98]
Dear All,

I have encountered a problem using DiaNN. I tried to emulate the pipeline described in the DiaNN Tutorial, where first a library is generated and second this library is searched. The Library generation worked flawlessly and also the processing of the first DIA file was finished. However, DiaNN just stopped working during the processing of the second DIA file. 
I only got the log message that DiaNN exited and that a PDF report would be generated in the background. However, there was no such report.pdf file in the specified filepath.
DiaNN then restarted the pipeline automatically.

I did notice that the 64 Gb memory of our analysis machine were almost fully occupied. I dont know if that might be the reason why DiaNN stopped working.

I have atteached the log text. I would love to get some insight in this issue, as the software seems to be quite promising.

Kind regards
Thorben

[DIANN_Log.txt](https://github.com/vdemichev/DiaNN/files/6221783/DIANN_Log.txt)

**Comment by vdemichev** [comment]
Hi Thorben,

Yes, apparently DIA-NN ran out of memory. This can happen when DIA-NN struggles to identify things in the data, when the search space is also large. Please use 
DIA-NN 1.7.16 and it's "Reduce RAM usage" mode - this mode is specifically designed to prevent this from happening. It will also warn you if it's about to run out of RAM. Also, 1.7.16 is in general A LOT better than 1.7.12.

Please don't hesitate to contact me by email if something doesn't work!

Best wishes,

Vadim

Best wishes,

Vadim

**Comment by L4ft2di3** [comment]
Thank you Vadim, I will try that right away.
All the best!
Thorben
